async function api(path,opts={}){const r=await fetch(path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Request failed');return j}
const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#39;'}[m]));
const fmtDate=v=>v?new Date(v).toLocaleDateString('en-IN'):'—';
async function login(e){e.preventDefault();document.getElementById('error').textContent='';const btn=e.target.querySelector('button');btn.disabled=true;btn.textContent='Verifying...';try{const r=await api('/api/admin',{method:'POST',body:JSON.stringify({action:'login',email:document.getElementById('email').value.trim().toLowerCase(),password:document.getElementById('password').value})});if(r.ok){showPanel();if(r.defaulted)document.getElementById('error').textContent='Default admin credentials are active. Set ADMIN_EMAIL and ADMIN_PASSWORD in Vercel before public launch.'}}catch(err){document.getElementById('error').textContent=err.message;document.getElementById('password').value=''}finally{btn.disabled=false;btn.textContent='Login Securely'}}
async function logout(){try{await api('/api/admin',{method:'POST',body:JSON.stringify({action:'logout'})})}catch{}location.replace('/admin.html')}
async function showPanel(){document.getElementById('login').classList.add('hidden');document.getElementById('panel').classList.remove('hidden');await loadPaymentConfig();await render();await loadPayments()}
async function show(){try{await api('/api/admin?action=session');await showPanel()}catch{document.getElementById('login').classList.remove('hidden');document.getElementById('panel').classList.add('hidden')}}
async function loadPaymentConfig(){try{const r=await api('/api/admin?action=payment-config');document.getElementById('upiId').value=r.upiId||'';document.getElementById('upiName').value=r.upiName||'NR BizPro'}catch(err){document.getElementById('upiConfigStatus').textContent=err.message}}
async function savePaymentConfig(){const upiId=document.getElementById('upiId').value.trim(),upiName=document.getElementById('upiName').value.trim();try{const r=await api('/api/admin',{method:'POST',body:JSON.stringify({action:'payment-config',upiId,upiName})});document.getElementById('upiConfigStatus').textContent='UPI settings saved successfully.';document.getElementById('upiId').value=r.upiId;document.getElementById('upiName').value=r.upiName}catch(err){document.getElementById('upiConfigStatus').textContent=err.message}}
function actionButtons(u){const id=encodeURIComponent(u.id),active=u.status==='active';return `<div class="actions"><button class="view" onclick="viewBusiness('${id}')">View</button>${active?`<button class="warn" onclick="changeStatus('${id}','suspended')">Suspend</button>`:`<button class="success" onclick="activateBusiness('${id}')">Activate</button>`}<button class="danger" onclick="deleteBusiness('${id}')">Delete</button></div>`}
function pendingActions(u){const id=encodeURIComponent(u.id);return `<div class="actions"><button class="success" onclick="approveBusiness('${id}')">Approve / Activate</button><button class="danger" onclick="rejectBusiness('${id}')">Reject</button></div>`}
async function render(){try{const r=await api('/api/admin?action=businesses'),users=r.businesses||[],q=(document.getElementById('search')?.value||'').toLowerCase(),pending=users.filter(u=>u.status==='pending');document.getElementById('total').textContent=users.length;document.getElementById('active').textContent=users.filter(u=>u.status==='active').length;document.getElementById('pending').textContent=pending.length;document.getElementById('expired').textContent=users.filter(u=>['expired','suspended'].includes(u.status)).length;const pendingTb=document.getElementById('pendingUsers');pendingTb.innerHTML=pending.length?pending.map(u=>`<tr><td><b>${esc(u.business)}</b><br><small>User ID: ${esc(u.user_id)}</small></td><td>${esc(u.owner)}</td><td>${esc(u.email)}<br>${esc(u.mobile)}</td><td>${esc(u.category)}</td><td><span class="pill pending">Pending</span></td><td>${u.created_at?new Date(u.created_at).toLocaleString('en-IN'):'—'}</td><td>${pendingActions(u)}</td></tr>`).join(''):'<tr><td colspan="7">No pending business approvals.</td></tr>';const rows=users.filter(u=>`${u.user_id} ${u.business} ${u.owner} ${u.email} ${u.mobile} ${u.category}`.toLowerCase().includes(q));document.getElementById('users').innerHTML=rows.length?rows.map(u=>`<tr><td><b>${esc(u.business)}</b><br><small>User ID: ${esc(u.user_id)}</small></td><td>${esc(u.owner)}</td><td>${esc(u.email)}<br>${esc(u.mobile)}</td><td>${esc(u.category)}</td><td><span class="pill ${esc(u.status)}">${esc(u.status)}</span></td><td>${esc(u.plan||'—')}</td><td>${fmtDate(u.subscription_ends)}</td><td>${actionButtons(u)}</td></tr>`).join(''):'<tr><td colspan="8">No business accounts found.</td></tr>'}catch(err){if(err.message==='Admin login required')location.replace('/admin.html');else document.getElementById('error').textContent=err.message}}
async function openCreateBusiness(){const userIdRaw=prompt('User ID (unique for this person):','');if(userIdRaw===null)return;const userId=userIdRaw.trim().toLowerCase();if(!/^[a-z0-9._-]{3,50}$/.test(userId))return alert('User ID must be 3-50 characters: a-z, 0-9, dot, underscore or hyphen.');const business=prompt('Business Name:');if(business===null)return;const owner=prompt('Person / Owner Name:');if(owner===null)return;const mobile=prompt('Mobile Number:');if(mobile===null)return;const email=prompt('Email:');if(email===null)return;const category=prompt('Business Category:','SERVICE');if(category===null)return;const gst=prompt('GSTIN (optional):','');if(gst===null)return;const password=prompt('Business Login Password (minimum 6 characters):');if(password===null)return;if(password.length<6)return alert('Password must be at least 6 characters.');try{await api('/api/admin',{method:'POST',body:JSON.stringify({action:'create-business',userId,business,owner,mobile,email,category,gst,password})});await render();alert(`Business user created successfully as Pending. User ID: ${userId}. Same business name can be used for other people with different User IDs.`)}catch(err){alert(err.message)}}
async function viewBusiness(id){try{const r=await api('/api/admin?action=businesses'),u=(r.businesses||[]).find(x=>x.id===decodeURIComponent(id));if(!u)return alert('Business not found.');alert(`BUSINESS DETAILS\n\nUser ID: ${u.user_id}\nBusiness: ${u.business}\nPerson / Owner: ${u.owner}\nEmail: ${u.email}\nMobile: ${u.mobile}\nCategory: ${u.category}\nGST: ${u.gst||'—'}\nStatus: ${u.status}\nPlan: ${u.plan||'—'}\nExpiry: ${u.subscription_ends?new Date(u.subscription_ends).toLocaleString('en-IN'):'—'}`)}catch(err){alert(err.message)}}
async function activateBusiness(id){const days=prompt('Activate this business for how many days?','365');if(days===null)return;const n=Number(days);if(!Number.isInteger(n)||n<1||n>3650)return alert('Enter a whole number from 1 to 3650 days.');try{await api('/api/admin',{method:'POST',body:JSON.stringify({action:'business-status',businessId:decodeURIComponent(id),status:'active',days:n,plan:'admin'})});await render();alert(`Business activated for ${n} days.`)}catch(err){alert(err.message)}}
async function approveBusiness(id){if(!confirm('Approve and activate this business for 365 days without requiring a payment?'))return;try{await api('/api/admin',{method:'POST',body:JSON.stringify({action:'approve-business',businessId:decodeURIComponent(id)})});await render();alert('Business approved and activated.')}catch(err){alert(err.message)}}
async function changeStatus(id,status){const label=status==='suspended'?'Suspend':'Set Pending';if(!confirm(`${label} this business? Its business login will be blocked.`))return;try{await api('/api/admin',{method:'POST',body:JSON.stringify({action:'business-status',businessId:decodeURIComponent(id),status})});await render();alert(`Business ${status}.`)}catch(err){alert(err.message)}}
async function rejectBusiness(id){if(!confirm('Reject this business registration?'))return;try{await api('/api/admin',{method:'POST',body:JSON.stringify({action:'reject-business',businessId:decodeURIComponent(id)})});await render();alert('Business rejected.')}catch(err){alert(err.message)}}
async function deleteBusiness(id){if(!confirm('DELETE this business permanently? Its business data, sessions and payment records will also be deleted. This cannot be undone.'))return;try{await api('/api/admin',{method:'POST',body:JSON.stringify({action:'delete-business',businessId:decodeURIComponent(id)})});await render();await loadPayments();alert('Business deleted permanently.')}catch(err){alert(err.message)}}
async function approvePayment(id){if(!confirm('Confirm UTR/payment verification and activate this membership?'))return;try{await api('/api/admin',{method:'POST',body:JSON.stringify({action:'approve-direct-payment',paymentId:id})});await loadPayments();await render();alert('Payment approved and membership activated.')}catch(err){alert(err.message)}}
async function rejectPayment(id){const note=prompt('Reason for rejection (optional):','Payment could not be verified.');if(note===null)return;try{await api('/api/admin',{method:'POST',body:JSON.stringify({action:'reject-direct-payment',paymentId:id,note})});await loadPayments();await render();alert('Payment request rejected.')}catch(err){alert(err.message)}}
show();setInterval(()=>{render();loadPayments()},30000);
