const USERS_KEY='nr-bizpro-users-v1';
const SESSION_KEY='nr-bizpro-session-v1';
const DATA_PREFIX='nr-bizpro-data-v2:';
const PLAN_MONTHLY=199;
const PLAN_YEARLY=1999;
let currentUser=null;
let state=null;
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n)||0);
const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#39;'}[m]));
const readUsers=()=>JSON.parse(localStorage.getItem(USERS_KEY)||'[]');
const writeUsers=u=>localStorage.setItem(USERS_KEY,JSON.stringify(u));
const save=()=>{if(currentUser&&state)localStorage.setItem(DATA_PREFIX+currentUser.id,JSON.stringify(state));};
const loadData=id=>JSON.parse(localStorage.getItem(DATA_PREFIX+id)||'null')||{items:[],bills:[],customers:[],settings:{name:'Your Business',category:'General Business',mobile:'',gst:'',address:''}};
const getSession=()=>localStorage.getItem(SESSION_KEY);
function renderAuth(mode='login',message=''){
 const el=document.getElementById('authContent');
 if(mode==='login')el.innerHTML=`<div class="auth-title"><h1>Login</h1><p>Access your NR BizPro business workspace.</p></div>${message?`<div class="notice">${esc(message)}</div>`:''}<form onsubmit="login(event)"><label>Login ID or Mobile<input id="loginId" required autocomplete="username" placeholder="Enter Login ID or mobile number"></label><label>Password<input id="loginPassword" required type="password" autocomplete="current-password"></label><button class="primary auth-btn">Login</button></form><p class="auth-switch">New business? <button onclick="renderAuth('signup')">Create account</button></p>`;
 if(mode==='signup')el.innerHTML=`<div class="auth-title"><h1>Create your business account</h1><p>Setup your business and start billing.</p></div><form onsubmit="signup(event)"><div class="auth-grid"><label>Business Name<input id="suBusiness" required></label><label>Owner Name<input id="suOwner" required></label><label>Mobile<input id="suMobile" required inputmode="tel"></label><label>Email<input id="suEmail" required type="email"></label><label>Business Category<input id="suCategory" required placeholder="Garage / Retail / Service..."></label><label>GSTIN <span>(optional)</span><input id="suGst"></label></div><label>Password<input id="suPassword" required minlength="6" type="password"></label><button class="primary auth-btn">Continue to Plans</button></form><p class="auth-switch">Already registered? <button onclick="renderAuth('login')">Login</button></p>`;
 if(mode==='plans')el.innerHTML=`<div class="auth-title"><h1>Choose your plan</h1><p>Subscription activates billing.</p></div><div class="plans"><button class="plan" onclick="startSubscription('monthly')"><b>Monthly</b><strong>${money(PLAN_MONTHLY)}</strong><span>30 days</span></button><button class="plan featured" onclick="startSubscription('yearly')"><b>Yearly</b><strong>${money(PLAN_YEARLY)}</strong><span>12 months</span><em>Best value</em></button></div>${message?`<div class="notice">${esc(message)}</div>`:''}`;
 if(mode==='payment')el.innerHTML=`<div class="auth-title"><h1>Subscription payment</h1><p>${currentUser.pendingPlan==='yearly'?'Yearly':'Monthly'} — ${money(currentUser.pendingAmount)}</p></div><button class="primary auth-btn" onclick="openRazorpayCheckout()">Pay with Razorpay</button><button class="secondary auth-btn" onclick="renderAuth('plans')">Back</button>`;
}
function signup(e){e.preventDefault();const business=suBusiness.value.trim(),owner=suOwner.value.trim(),mobile=suMobile.value.trim(),email=suEmail.value.trim().toLowerCase(),category=suCategory.value.trim(),gst=suGst.value.trim(),password=suPassword.value;const users=readUsers();if(users.some(u=>u.email===email||u.mobile===mobile)){renderAuth('login','Account already exists.');return}currentUser={id:crypto.randomUUID(),business,owner,mobile,email,category,gst,password,status:'pending',plan:null,subscriptionEnds:null,pendingPlan:null,pendingAmount:0,lastPaymentId:null};users.push(currentUser);writeUsers(users);renderAuth('plans')}
function startSubscription(plan){currentUser.pendingPlan=plan;currentUser.pendingAmount=plan==='yearly'?PLAN_YEARLY:PLAN_MONTHLY;persistUser();renderAuth('payment')}
function persistUser(){writeUsers(readUsers().map(u=>u.id===currentUser.id?currentUser:u))}
async function openRazorpayCheckout(){if(!currentUser?.pendingPlan)return;if(typeof Razorpay==='undefined')return alert('Razorpay did not load. Refresh.');try{const r=await fetch('/api/create-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan:currentUser.pendingPlan,businessName:currentUser.business,email:currentUser.email,mobile:currentUser.mobile})}),o=await r.json();if(!r.ok)throw Error(o.error||'Could not create order');const z=new Razorpay({key:o.keyId,amount:o.amount,currency:o.currency,name:'NR BizPro',description:'Billing Software Subscription',order_id:o.orderId,prefill:{name:currentUser.owner,email:currentUser.email,contact:currentUser.mobile},handler:verifyRazorpayPayment});z.open()}catch(e){alert(e.message)}}
async function verifyRazorpayPayment(response){try{const r=await fetch('/api/verify-payment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(response)}),d=await r.json();if(!r.ok||!d.verified)throw Error(d.error||'Payment verification failed');activateAfterVerifiedPayment(d.paymentId)}catch(e){alert(e.message)}}
function activateAfterVerifiedPayment(paymentId){const days=currentUser.pendingPlan==='yearly'?365:30,base=new Date();base.setDate(base.getDate()+days);currentUser.status='active';currentUser.plan=currentUser.pendingPlan;currentUser.subscriptionEnds=base.toISOString();currentUser.pendingPlan=null;currentUser.pendingAmount=0;currentUser.lastPaymentId=paymentId;persistUser();localStorage.setItem(SESSION_KEY,currentUser.id);state=loadData(currentUser.id);state.settings.name=currentUser.business;state.settings.category=currentUser.category;state.settings.mobile=currentUser.mobile;state.settings.gst=currentUser.gst;save();showApp()}
function login(e){e.preventDefault();const id=loginId.value.trim().toLowerCase(),password=loginPassword.value,user=readUsers().find(u=>((u.user_id||u.loginId||u.mobile||'').toString().toLowerCase()===id||u.mobile===id)&&u.password===password);if(!user)return renderAuth('login','Invalid login details.');currentUser=user;if(user.status!=='active'||!user.subscriptionEnds||new Date(user.subscriptionEnds)<=new Date())return renderAuth('plans','Subscription required or expired.');localStorage.setItem(SESSION_KEY,user.id);state=loadData(id);showApp()}
function logout(){localStorage.removeItem(SESSION_KEY);currentUser=null;state=null;app.classList.add('hidden');authScreen.classList.remove('hidden');renderAuth('login')}
function checkSession(){const id=getSession();if(!id)return renderAuth('login');const user=readUsers().find(u=>u.id===id);if(!user)return logout();currentUser=user;if(user.status!=='active'||!user.subscriptionEnds||new Date(user.subscriptionEnds)<=new Date()){localStorage.removeItem(SESSION_KEY);return renderAuth('plans','Subscription expired. Renew to continue.')}state=loadData(id);showApp()}
function showApp(){authScreen.classList.add('hidden');app.classList.remove('hidden');accountStatus.textContent='Active';subscriptionStat.textContent=currentUser.plan==='yearly'?'Yearly':'Monthly';loadSettings();renderItems();renderBills();renderCustomers();updateStats()}
function showTab(id){document.querySelectorAll('.tab-panel').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));if(id==='items')renderItems();if(id==='bills')renderBills();if(id==='customers')renderCustomers()}document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
function openModal(t,b){modalTitle.textContent=t;modalBody.innerHTML=b;modal.classList.remove('hidden')}function closeModal(){modal.classList.add('hidden')}
