const KEY='nr-bizpro-demo-v1';
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{items:[],bills:[],settings:{name:'Your Business',category:'General Business',mobile:'',gst:'',address:''}};
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n)||0);
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
function showTab(id){document.querySelectorAll('.tab-panel').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));if(id==='items')renderItems();if(id==='bills')renderBills()}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
function openModal(title,body){document.getElementById('modalTitle').textContent=title;document.getElementById('modalBody').innerHTML=body;document.getElementById('modal').classList.remove('hidden')}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
function openItemModal(){openModal('Add Product / Service',`<div class="modal-grid"><label class="field">Item Name<input id="mName" placeholder="e.g. General Service"></label><label class="field">Type<select id="mType"><option>Product</option><option>Service</option></select></label><label class="field">Cost Price<input id="mCost" type="number" min="0" value="0"></label><label class="field">Margin Type<select id="mMarginType"><option value="percent">Percentage</option><option value="fixed">Fixed Amount</option></select></label><label class="field">Margin<input id="mMargin" type="number" min="0" value="0"></label><label class="field">GST %<input id="mGst" type="number" min="0" value="0"></label><label class="field wide">Selling Price <input id="mSell" type="number" min="0" value="0"></label></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="addItem()">Save Item</button></div>`);['mCost','mMargin','mMarginType'].forEach(id=>document.getElementById(id).addEventListener('input',calcSell));calcSell()}
function calcSell(){const c=+document.getElementById('mCost').value||0,m=+document.getElementById('mMargin').value||0,t=document.getElementById('mMarginType').value;document.getElementById('mSell').value=(c+(t==='percent'?c*m/100:m)).toFixed(2)}
function addItem(){const name=document.getElementById('mName').value.trim();if(!name)return alert('Enter item name');const cost=+document.getElementById('mCost').value||0,margin=+document.getElementById('mMargin').value||0,type=document.getElementById('mMarginType').value;const sell=+(document.getElementById('mSell').value||0);state.items.push({id:crypto.randomUUID(),name,type:document.getElementById('mType').value,cost,margin,marginType:type,sell,gst:+document.getElementById('mGst').value||0});save();closeModal();renderItems();updateStats()}
function renderItems(){const tb=document.getElementById('itemTable');if(!state.items.length){tb.innerHTML='<tr><td colspan="6" class="empty">No products or services yet. Add your first item.</td></tr>';return}tb.innerHTML=state.items.map(i=>`<tr><td><b>${esc(i.name)}</b></td><td>${i.type}</td><td>${money(i.cost)}</td><td>${i.margin}${i.marginType==='percent'?'%':' fixed'}</td><td><b>${money(i.sell)}</b></td><td><button class="secondary" onclick="deleteItem('${i.id}')">Delete</button></td></tr>`).join('')}
function deleteItem(id){state.items=state.items.filter(i=>i.id!==id);save();renderItems();updateStats()}
function openBillModal(){if(!state.items.length){alert('Add at least one product/service first.');showTab('items');return}openModal('Create New Bill',`<div class="modal-grid"><label class="field">Customer Name<input id="bCustomer" placeholder="Customer name"></label><label class="field">Customer Mobile<input id="bMobile" placeholder="Optional"></label><label class="field wide">Select Item<select id="bItem">${state.items.map(i=>`<option value="${i.id}">${esc(i.name)} — ${money(i.sell)}</option>`).join('')}</select></label><label class="field">Quantity<input id="bQty" type="number" min="1" value="1"></label><label class="field">Discount<input id="bDiscount" type="number" min="0" value="0"></label></div><div class="bill-lines"><div class="bill-line"><b>Item</b><b>Qty</b><b>Amount</b><span></span></div><div id="billPreview"></div></div><div class="bill-total">Total: <span id="bTotal" style="margin-left:8px">₹0</span></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveBill()">Generate Bill</button></div>`);['bItem','bQty','bDiscount'].forEach(id=>document.getElementById(id).addEventListener('input',updateBillPreview));updateBillPreview()}
function updateBillPreview(){const item=state.items.find(i=>i.id===document.getElementById('bItem').value),qty=Math.max(1,+document.getElementById('bQty').value||1),discount=Math.max(0,+document.getElementById('bDiscount').value||0),subtotal=(item?.sell||0)*qty,total=Math.max(0,subtotal-discount);document.getElementById('billPreview').innerHTML=item?`<div class="bill-line"><span>${esc(item.name)}</span><span>${qty}</span><span>${money(subtotal)}</span><span></span></div>`:'';document.getElementById('bTotal').textContent=money(total)}
function saveBill(){const item=state.items.find(i=>i.id===document.getElementById('bItem').value),qty=Math.max(1,+document.getElementById('bQty').value||1),discount=Math.max(0,+document.getElementById('bDiscount').value||0);const total=Math.max(0,item.sell*qty-discount);const no=`INV-${String(state.bills.length+1).padStart(4,'0')}`;state.bills.unshift({id:crypto.randomUUID(),invoice:no,date:new Date().toISOString(),customer:document.getElementById('bCustomer').value.trim()||'Walk-in Customer',mobile:document.getElementById('bMobile').value.trim(),items:[{name:item.name,qty,price:item.sell}],discount,total});save();closeModal();renderBills();updateStats();showTab('bills');}
function renderBills(){const q=(document.getElementById('billSearch')?.value||'').toLowerCase();const bills=state.bills.filter(b=>`${b.invoice} ${b.customer}`.toLowerCase().includes(q));const tb=document.getElementById('billTable');if(!bills.length){tb.innerHTML='<tr><td colspan="6" class="empty">No bills found.</td></tr>';return}tb.innerHTML=bills.map(b=>`<tr><td><b>${b.invoice}</b></td><td>${new Date(b.date).toLocaleDateString('en-IN')}</td><td>${esc(b.customer)}</td><td>${b.items.length}</td><td><b>${money(b.total)}</b></td><td><button class="secondary" onclick="printBill('${b.id}')">Print</button></td></tr>`).join('')}
function printBill(id){const b=state.bills.find(x=>x.id===id);const s=state.settings;const rows=b.items.map(i=>`<tr><td>${esc(i.name)}</td><td>${i.qty}</td><td>${money(i.price)}</td><td>${money(i.qty*i.price)}</td></tr>`).join('');const w=window.open('','_blank');w.document.write(`<html><head><title>${b.invoice}</title><style>body{font-family:Arial;padding:30px;color:#111}h1{margin:0 0 4px}table{width:100%;border-collapse:collapse;margin-top:25px}th,td{border-bottom:1px solid #ddd;padding:10px;text-align:left}.total{text-align:right;font-size:20px;font-weight:bold;margin-top:20px}</style></head><body><h1>${esc(s.name)}</h1><div>${esc(s.address||'')}</div><div>${esc(s.mobile||'')}</div><hr><h2>Invoice ${b.invoice}</h2><div>Customer: ${esc(b.customer)}</div><table><tr><th>Item</th><th>Qty</th><th>Price</th><th>Amount</th></tr>${rows}</table><div class="total">Total: ${money(b.total)}</div><script>window.print()<\/script></body></html>`);w.document.close()}
function saveSettings(){state.settings={name:document.getElementById('businessName').value.trim()||'Your Business',category:document.getElementById('businessCategory').value.trim(),mobile:document.getElementById('businessMobile').value.trim(),gst:document.getElementById('businessGst').value.trim(),address:document.getElementById('businessAddress').value.trim()};save();alert('Business settings saved.')}
function updateStats(){document.getElementById('billCount').textContent=state.bills.length;document.getElementById('itemCount').textContent=state.items.length;const d=new Date().toDateString();document.getElementById('todaySales').textContent=money(state.bills.filter(b=>new Date(b.date).toDateString()===d).reduce((a,b)=>a+b.total,0))}
function loadSettings(){document.getElementById('businessName').value=state.settings.name;document.getElementById('businessCategory').value=state.settings.category;document.getElementById('businessMobile').value=state.settings.mobile;document.getElementById('businessGst').value=state.settings.gst;document.getElementById('businessAddress').value=state.settings.address}
function esc(v){return String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#39;'}[m]))}
loadSettings();renderItems();renderBills();updateStats();
