const USERS_KEY='nr-bizpro-users-v1';
const SESSION_KEY='nr-bizpro-session-v1';
const DATA_PREFIX='nr-bizpro-data-v2:';
const PLAN_MONTHLY=199;
const PLAN_YEARLY=1999;
let currentUser=null;
let state=null;

const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n)||0);
const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#39;'}[m]));
const readUsers=()=>JSON.parse(localStorage.getItem(USERS_KEY)||'[]');
const writeUsers=u=>localStorage.setItem(USERS_KEY,JSON.stringify(u));
const save=()=>{if(currentUser&&state)localStorage.setItem(DATA_PREFIX+currentUser.id,JSON.stringify(state));};
const loadData=id=>JSON.parse(localStorage.getItem(DATA_PREFIX+id)||'null')||{items:[],bills:[],customers:[],settings:{name:'Your Business',category:'General Business',mobile:'',gst:'',address:''}};
const getSession=()=>localStorage.getItem(SESSION_KEY);

function renderAuth(mode='login',message=''){
 const el=document.getElementById('authContent');
 if(mode==='login')el.innerHTML=`<div class="auth-title"><h1>Welcome back</h1><p>Login to your NR BizPro business account.</p></div>${message?`<div class="notice">${esc(message)}</div>`:''}<form onsubmit="login(event)"><label>Email or Mobile<input id="loginId" required autocomplete="username"></label><label>Password<input id="loginPassword" required type="password" autocomplete="current-password"></label><button class="primary auth-btn">Login</button></form><p class="auth-switch">New business? <button onclick="renderAuth('signup')">Create account</button></p>`;
 if(mode==='signup')el.innerHTML=`<div class="auth-title"><h1>Create your business account</h1><p>Setup your business and start billing.</p></div><form onsubmit="signup(event)"><div class="auth-grid"><label>Business Name<input id="suBusiness" required></label><label>Owner Name<input id="suOwner" required></label><label>Mobile<input id="suMobile" required inputmode="tel"></label><label>Email<input id="suEmail" required type="email"></label><label>Business Category<input id="suCategory" required placeholder="Garage / Retail / Service..."></label><label>GSTIN <span>(optional)</span><input id="suGst"></label></div><label>Password<input id="suPassword" required minlength="6" type="password"></label><button class="primary auth-btn">Continue to Plans</button></form><p class="auth-switch">Already registered? <button onclick="renderAuth('login')">Login</button></p>`;
 if(mode==='plans')el.innerHTML=`<div class="auth-title"><h1>Choose your plan</h1><p>Subscription activates billing.</p></div><div class="plans"><button class="plan" onclick="startSubscription('monthly')"><b>Monthly</b><strong>${money(PLAN_MONTHLY)}</strong><span>30 days</span></button><button class="plan featured" onclick="startSubscription('yearly')"><b>Yearly</b><strong>${money(PLAN_YEARLY)}</strong><span>12 months</span><em>Best value</em></button></div>${message?`<div class="notice">${esc(message)}</div>`:''}`;
 if(mode==='payment')el.innerHTML=`<div class="auth-title"><h1>Subscription payment</h1><p>${currentUser.pendingPlan==='yearly'?'Yearly':'Monthly'} — ${money(currentUser.pendingAmount)}</p></div><button class="primary auth-btn" onclick="openRazorpayCheckout()">Pay with Razorpay</button><button class="secondary auth-btn" onclick="renderAuth('plans')">Back</button>`;
}
function signup(e){e.preventDefault();const business=suBusiness.value.trim(),owner=suOwner.value.trim(),mobile=suMobile.value.trim(),email=suEmail.value.trim().toLowerCase(),category=suCategory.value.trim(),gst=suGst.value.trim(),password=suPassword.value;const users=readUsers();if(users.some(u=>u.email===email||u.mobile===mobile)){renderAuth('login','Account already exists.');return}currentUser={id:crypto.randomUUID(),business,owner,mobile,email,category,gst,password,status:'pending',plan:null,subscriptionEnds:null,pendingPlan:null,pendingAmount:0,lastPaymentId:null};users.push(currentUser);writeUsers(users);renderAuth('plans')}
function startSubscription(plan){currentUser.pendingPlan=plan;currentUser.pendingAmount=plan==='yearly'?PLAN_YEARLY:PLAN_MONTHLY;persistUser();renderAuth('payment')}
function persistUser(){writeUsers(readUsers().map(u=>u.id===currentUser.id?currentUser:u))}
async function openRazorpayCheckout(){if(!currentUser?.pendingPlan)return;if(typeof Razorpay==='undefined')return alert('Razorpay did not load. Refresh.');try{const r=await fetch('/api/create-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan:currentUser.pendingPlan,businessName:currentUser.business,email:currentUser.email,mobile:currentUser.mobile})}),o=await r.json();if(!r.ok)throw Error(o.error||'Could not create order');const z=new Razorpay({key:o.keyId,amount:o.amount,currency:o.currency,name:'NR BizPro',description:'Billing Software Subscription',order_id:o.orderId,prefill:{name:currentUser.owner,email:currentUser.email,contact:currentUser.mobile},handler:verifyRazorpayPayment});z.open()}catch(e){alert(e.message)}}
async function verifyRazorpayPayment(response){try{const r=await fetch('/api/verify-payment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(response)}),d=await r.json();if(!r.ok||!d.verified)throw Error(d.error||'Payment verification failed');activateAfterVerifiedPayment(d.paymentId)}catch(e){alert(e.message)}}
function activateAfterVerifiedPayment(paymentId){const days=currentUser.pendingPlan==='yearly'?365:30,base=new Date();base.setDate(base.getDate()+days);currentUser.status='active';currentUser.plan=currentUser.pendingPlan;currentUser.subscriptionEnds=base.toISOString();currentUser.pendingPlan=null;currentUser.pendingAmount=0;currentUser.lastPaymentId=paymentId;persistUser();localStorage.setItem(SESSION_KEY,currentUser.id);state=loadData(currentUser.id);state.settings.name=currentUser.business;state.settings.category=currentUser.category;state.settings.mobile=currentUser.mobile;state.settings.gst=currentUser.gst;save();showApp()}
function login(e){e.preventDefault();const id=loginId.value.trim().toLowerCase(),password=loginPassword.value,user=readUsers().find(u=>(u.email===id||u.mobile===id)&&u.password===password);if(!user)return renderAuth('login','Invalid login details.');currentUser=user;if(user.status!=='active'||!user.subscriptionEnds||new Date(user.subscriptionEnds)<=new Date())return renderAuth('plans','Subscription required or expired.');localStorage.setItem(SESSION_KEY,user.id);state=loadData(user.id);showApp()}
function logout(){localStorage.removeItem(SESSION_KEY);currentUser=null;state=null;app.classList.add('hidden');authScreen.classList.remove('hidden');renderAuth('login')}
function checkSession(){const id=getSession();if(!id)return renderAuth('login');const user=readUsers().find(u=>u.id===id);if(!user)return logout();currentUser=user;if(user.status!=='active'||!user.subscriptionEnds||new Date(user.subscriptionEnds)<=new Date()){localStorage.removeItem(SESSION_KEY);return renderAuth('plans','Subscription expired. Renew to continue.')}state=loadData(id);showApp()}
function showApp(){authScreen.classList.add('hidden');app.classList.remove('hidden');accountStatus.textContent='Active';subscriptionStat.textContent=currentUser.plan==='yearly'?'Yearly':'Monthly';loadSettings();renderItems();renderBills();renderCustomers();updateStats()}
function showTab(id){document.querySelectorAll('.tab-panel').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));if(id==='items')renderItems();if(id==='bills')renderBills();if(id==='customers')renderCustomers()}document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
function openModal(t,b){modalTitle.textContent=t;modalBody.innerHTML=b;modal.classList.remove('hidden')}function closeModal(){modal.classList.add('hidden')}
function openItemModal(){openModal('Add Product / Service',`<div class="modal-grid"><label class="field">Product / Service<input id="mName" required placeholder="Engine Oil"></label><label class="field">Barcode<input id="mBarcode" placeholder="Scan barcode here"></label><label class="field">Type<select id="mType"><option>Product</option><option>Service</option></select></label><label class="field">Cost Price<input id="mCost" type="number" min="0" value="0"></label><label class="field">Margin Type<select id="mMarginType"><option value="percent">Percentage</option><option value="fixed">Fixed Amount</option></select></label><label class="field">Margin<input id="mMargin" type="number" min="0" value="0"></label><label class="field">GST %<input id="mGst" type="number" min="0" value="0"></label><label class="field">Opening Stock<input id="mStock" type="number" min="0" value="0"></label><label class="field wide">Selling Price<input id="mSell" type="number" min="0" value="0"></label></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="addItem()">Save Product</button></div>`);['mCost','mMargin','mMarginType'].forEach(id=>document.getElementById(id).addEventListener('input',calcSell));document.getElementById('mBarcode').focus();calcSell()}
function calcSell(){const c=+mCost.value||0,m=+mMargin.value||0,t=mMarginType.value;mSell.value=(c+(t==='percent'?c*m/100:m)).toFixed(2)}
function addItem(){const name=mName.value.trim();if(!name)return alert('Enter product name');const barcode=mBarcode.value.trim();if(barcode&&state.items.some(i=>i.barcode===barcode))return alert('Barcode already exists');state.items.push({id:crypto.randomUUID(),name,barcode,type:mType.value,cost:+mCost.value||0,margin:+mMargin.value||0,marginType:mMarginType.value,sell:+mSell.value||0,gst:+mGst.value||0,stock:+mStock.value||0});save();closeModal();renderItems();updateStats()}
function renderItems(){const tb=itemTable;if(!state.items.length){tb.innerHTML='<tr><td colspan="8" class="empty">No products yet.</td></tr>';return}tb.innerHTML=state.items.map(i=>`<tr><td><b>${esc(i.name)}</b></td><td>${esc(i.barcode||'—')}</td><td>${i.type}</td><td>${money(i.cost)}</td><td><b>${money(i.sell)}</b></td><td>${i.gst}%</td><td>${i.stock}</td><td><button class="secondary" onclick="deleteItem('${i.id}')">Delete</button></td></tr>`).join('')}
function deleteItem(id){state.items=state.items.filter(i=>i.id!==id);save();renderItems();updateStats()}
function openBillModal(){openModal('Create New Bill',`<label class="field">Customer Name<input id="bCustomer" placeholder="Walk-in Customer"></label><label class="field">Customer Mobile<input id="bMobile"></label><label class="field wide">🔎 Search Product / 📷 Barcode Scan<input id="bSearch" autofocus placeholder="Type product name or scan barcode" oninput="searchBillProducts()" onkeydown="handleBarcodeKey(event)"></label><div id="billSuggestions" class="suggestions"></div><div id="billLines" class="bill-lines"></div><div class="bill-total">Total: <span id="bTotal">₹0</span></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveBill()">Generate Bill</button></div>`);window.billCart=[];renderCart();document.getElementById('bSearch').focus()}
function searchBillProducts(){const q=bSearch.value.trim().toLowerCase(),box=billSuggestions;if(!q){box.innerHTML='';return}const found=state.items.filter(i=>i.name.toLowerCase().includes(q)||(i.barcode||'').toLowerCase()===q).slice(0,8);box.innerHTML=found.map(i=>`<button class="suggestion" onclick="addToCart('${i.id}')"><b>${esc(i.name)}</b><span>${i.barcode||'No barcode'} • ${money(i.sell)} • Stock ${i.stock}</span></button>`).join('')||'<div class="empty">No product found</div>';if(found.length===1&&(found[0].barcode||'')===q)addToCart(found[0].id)}
function handleBarcodeKey(e){if(e.key!=='Enter')return;e.preventDefault();const q=e.target.value.trim().toLowerCase(),i=state.items.find(x=>(x.barcode||'').toLowerCase()===q);if(i){addToCart(i.id);e.target.value='';billSuggestions.innerHTML=''}}
function addToCart(id){const i=state.items.find(x=>x.id===id);if(!i)return;const line=window.billCart.find(x=>x.id===id);if(line)line.qty++;else window.billCart.push({id:i.id,qty:1});bSearch.value='';billSuggestions.innerHTML='';renderCart();bSearch.focus()}
function renderCart(){const box=billLines;if(!window.billCart.length){box.innerHTML='<div class="empty">Scan a barcode or search for a product.</div>';bTotal.textContent=money(0);return}let total=0;box.innerHTML=window.billCart.map(l=>{const i=state.items.find(x=>x.id===l.id),amt=i.sell*l.qty;total+=amt;return `<div class="bill-line"><span><b>${esc(i.name)}</b><small>${i.barcode||''}</small></span><span><button onclick="changeQty('${i.id}',-1)">−</button> ${l.qty} <button onclick="changeQty('${i.id}',1)">+</button></span><b>${money(amt)}</b><button onclick="removeCart('${i.id}')">×</button></div>`}).join('');bTotal.textContent=money(total)}
function changeQty(id,d){const l=window.billCart.find(x=>x.id===id);if(!l)return;l.qty+=d;if(l.qty<1)removeCart(id);else renderCart()}function removeCart(id){window.billCart=window.billCart.filter(x=>x.id!==id);renderCart()}
function saveBill(){if(!window.billCart?.length)return alert('Add at least one product');let total=0;const lines=window.billCart.map(l=>{const i=state.items.find(x=>x.id===l.id);i.stock=Math.max(0,(+i.stock||0)-l.qty);total+=i.sell*l.qty;return{name:i.name,barcode:i.barcode||'',qty:l.qty,price:i.sell,gst:i.gst}});const no=`INV-${String(state.bills.length+1).padStart(4,'0')}`,customer=bCustomer.value.trim()||'Walk-in Customer',mobile=bMobile.value.trim();state.bills.unshift({id:crypto.randomUUID(),invoice:no,date:new Date().toISOString(),customer,mobile,items:lines,total});let c=state.customers.find(x=>x.mobile===mobile&&mobile);if(!c){c={id:crypto.randomUUID(),name:customer,mobile,email:'',bills:0,total:0};state.customers.push(c)}c.bills++;c.total+=total;save();closeModal();renderBills();renderCustomers();renderItems();updateStats();showTab('bills')}
function renderBills(){const q=(billSearch?.value||'').toLowerCase(),tb=document.getElementById('billTable');if(!tb)return;const bills=state.bills.filter(b=>`${b.invoice} ${b.customer} ${b.mobile}`.toLowerCase().includes(q));tb.innerHTML=bills.length?bills.map(b=>`<tr><td><b>${b.invoice}</b></td><td>${new Date(b.date).toLocaleDateString('en-IN')}</td><td>${esc(b.customer)}<br><small>${esc(b.mobile||'')}</small></td><td>${b.items.length}</td><td><b>${money(b.total)}</b></td><td><button class="secondary" onclick="printBill('${b.id}')">Print</button></td></tr>`).join(''):'<tr><td colspan="6" class="empty">No bills found.</td></tr>'}
function printBill(id){const b=state.bills.find(x=>x.id===id);if(!b)return;const s=state.settings,w=window.open('','_blank');w.document.write(`<html><head><title>${b.invoice}</title><style>body{font-family:Arial;padding:30px;max-width:700px;margin:auto}table{width:100%;border-collapse:collapse}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:left}.r{text-align:right}</style></head><body><h1>${esc(s.name)}</h1><p>${esc(s.address)}<br>${esc(s.mobile)} ${s.gst?'| GSTIN: '+esc(s.gst):''}</p><h2>Invoice ${b.invoice}</h2><p>Customer: ${esc(b.customer)} ${b.mobile?'| '+esc(b.mobile):''}</p><table><tr><th>Item</th><th>Qty</th><th class="r">Price</th><th class="r">Amount</th></tr>${b.items.map(i=>`<tr><td>${esc(i.name)}</td><td>${i.qty}</td><td class="r">${money(i.price)}</td><td class="r">${money(i.price*i.qty)}</td></tr>`).join('')}</table><h2 class="r">Total: ${money(b.total)}</h2><script>window.print()</script></body></html>`);w.document.close()}
function renderCustomers(){const tb=document.getElementById('customerTable');if(!tb)return;tb.innerHTML=state.customers.length?state.customers.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.mobile)}</td><td>${esc(c.email||'')}</td><td>${c.bills}</td><td>${money(c.total)}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">No customers yet.</td></tr>'}
function loadSettings(){businessName.value=state.settings.name||currentUser.business;businessCategory.value=state.settings.category||currentUser.category;businessMobile.value=state.settings.mobile||currentUser.mobile;businessGst.value=state.settings.gst||currentUser.gst;businessAddress.value=state.settings.address||''}function saveSettings(){state.settings={name:businessName.value.trim(),category:businessCategory.value,mobile:businessMobile.value.trim(),gst:businessGst.value.trim(),address:businessAddress.value.trim()};save();alert('Settings saved')}
function updateStats(){const today=new Date().toDateString();todaySales.textContent=money(state.bills.filter(b=>new Date(b.date).toDateString()===today).reduce((a,b)=>a+b.total,0));billCount.textContent=state.bills.length;itemCount.textContent=state.items.length}
document.addEventListener('DOMContentLoaded',checkSession);

// Start public authentication immediately after the core app loads. Optional modules
// must never block the login/signup screen from appearing.
(function installFastPublicAuth(){
 const open=(mode)=>{
  const landing=document.getElementById('publicLanding');
  const screen=document.getElementById('authScreen');
  if(landing)landing.style.display='none';
  if(screen)screen.classList.remove('hidden');
  if(typeof window.renderAuth==='function')window.renderAuth(mode);
 };
 const loginBtn=document.getElementById('publicLogin');
 const signupBtn=document.getElementById('publicSignup');
 const signup2Btn=document.getElementById('publicSignup2');
 if(loginBtn)loginBtn.addEventListener('click',()=>open('login'));
 if(signupBtn)signupBtn.addEventListener('click',()=>open('signup'));
 if(signup2Btn)signup2Btn.addEventListener('click',()=>open('signup'));
 if(new URLSearchParams(location.search).get('auth')==='login')open('login');
})();