// NR BizPro — stable common billing + product edit
(function(){
 function getState(){try{return typeof state!=='undefined'?state:null}catch(e){return null}}
 function getItems(){const s=getState();return s?.items||[]}
 function launchBill(){
  if(typeof window.openModal!=='function'){alert('Billing UI is still loading. Please refresh once.');return;}
  window.billCart=[];
  window.openModal('Create New Bill',`<label class="field">Customer Name<input id="bCustomer" placeholder="Walk-in Customer"></label><label class="field">Customer Mobile<input id="bMobile"></label><label class="field wide">🔎 Search Product / 📷 Barcode Scan<input id="bSearch" placeholder="Type product name or scan barcode"></label><div id="billSuggestions" class="suggestions"></div><div id="billLines" class="bill-lines"></div><div class="bill-adjustments"><label class="field">Discount Type<select id="billDiscountType"><option value="percent">Percentage (%)</option><option value="fixed">Fixed Amount (₹)</option></select></label><label class="field">Discount<input id="billDiscount" type="number" min="0" step="0.01" value="0"></label></div><div id="billSummary" class="bill-summary"></div><div class="modal-actions"><button class="secondary" type="button" onclick="closeModal()">Cancel</button><button class="primary" type="button" onclick="window.saveBillFixed()">Generate Bill</button></div>`);
  if(typeof window.renderCart==='function')window.renderCart();
  const s=document.getElementById('bSearch');
  if(s){s.oninput=()=>typeof window.searchBillProducts==='function'&&window.searchBillProducts();s.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();if(typeof window.handleBarcodeKey==='function')window.handleBarcodeKey(e)}};s.focus()}
  function recalc(){let sub=0,gst=0;const st=getState();(window.billCart||[]).forEach(l=>{const i=st?.items?.find(x=>x.id===l.id);if(i){const a=(Number(i.sell)||0)*(Number(l.qty)||0);sub+=a;gst+=a*(Number(i.gst)||0)/100}});const type=document.getElementById('billDiscountType')?.value||'percent',v=Math.max(0,Number(document.getElementById('billDiscount')?.value)||0),d=type==='fixed'?Math.min(v,sub):Math.min(sub,sub*v/100),tax=Math.max(0,sub-d),g=sub?gst*tax/sub:0,net=tax+g;const sm=document.getElementById('billSummary');if(sm)sm.innerHTML=`<div><span>Subtotal</span><b>${money(sub)}</b></div><div><span>Discount</span><b>− ${money(d)}</b></div><div><span>GST</span><b>${money(g)}</b></div><div class="bill-net"><span>Net Amount</span><strong>${money(net)}</strong></div>`;const total=document.getElementById('bTotal');if(total)total.textContent=money(net);return{discount:d,gst:g,subtotal:sub,total:net}}
  document.getElementById('billDiscount')?.addEventListener('input',recalc);document.getElementById('billDiscountType')?.addEventListener('change',recalc);recalc();window.__nrRecalcBill=recalc;
 }
 function saveBillFixed(){
  const st=getState();if(!st)return alert('Billing data is not ready. Please refresh once.');
  if(!window.billCart?.length)return alert('Add at least one product');
  const cart=window.billCart.map(l=>({id:l.id,qty:Math.max(1,Number(l.qty)||1)}));
  for(const l of cart){const i=st.items.find(x=>x.id===l.id);if(!i)return alert('Product not found.');if(String(i.type).toLowerCase()!=='service'&&Number(i.stock||0)<l.qty)return alert('Insufficient stock for '+i.name+'. Available: '+(Number(i.stock)||0));}
  let subtotal=0,gst=0;const lines=cart.map(l=>{const i=st.items.find(x=>x.id===l.id),price=Number(i.sell)||0,a=price*l.qty;subtotal+=a;gst+=a*(Number(i.gst)||0)/100;return{name:i.name,barcode:i.barcode||'',qty:l.qty,price,gst:Number(i.gst)||0,type:i.type||'Product',productId:i.id};});
  const dt=document.getElementById('billDiscountType')?.value||'percent',dv=Math.max(0,Number(document.getElementById('billDiscount')?.value)||0),discount=dt==='fixed'?Math.min(dv,subtotal):Math.min(subtotal,subtotal*dv/100),taxable=Math.max(0,subtotal-discount),tax=subtotal?gst*taxable/subtotal:0,total=taxable+tax;
  for(const l of cart){const i=st.items.find(x=>x.id===l.id);if(String(i.type).toLowerCase()!=='service')i.stock=Math.max(0,(Number(i.stock)||0)-l.qty)}
  const customer=(document.getElementById('bCustomer')?.value||'Walk-in Customer').trim()||'Walk-in Customer',mobile=(document.getElementById('bMobile')?.value||'').trim();
  const no=`INV-${String(st.bills.length+1).padStart(4,'0')}`;
  st.bills.unshift({id:crypto.randomUUID(),invoice:no,date:new Date().toISOString(),customer,mobile,items:lines,total,subtotal,discount,discountType:dt,gst:tax});
  let c=st.customers.find(x=>x.mobile===mobile&&mobile);if(!c){c={id:crypto.randomUUID(),name:customer,mobile,email:'',bills:0,total:0};st.customers.push(c)}c.name=customer;c.bills++;c.total+=total;
  if(typeof save==='function')save();if(typeof closeModal==='function')closeModal();if(typeof renderBills==='function')renderBills();if(typeof renderCustomers==='function')renderCustomers();if(typeof renderItems==='function')renderItems();if(typeof updateStats==='function')updateStats();if(typeof showTab==='function')showTab('bills');
 }
 function editItem(id){const st=getState(),i=st?.items?.find(x=>x.id===id);if(!i)return;if(typeof window.openModal!=='function')return;window.openModal('Edit Product / Service',`<div class="modal-grid"><label class="field">Product / Service<input id="eName" value="${esc(i.name)}"></label><label class="field">Barcode<input id="eBarcode" value="${esc(i.barcode||'')}"></label><label class="field">Type<select id="eType"><option ${i.type==='Product'?'selected':''}>Product</option><option ${i.type==='Service'?'selected':''}>Service</option></select></label><label class="field">Cost Price<input id="eCost" type="number" value="${i.cost||0}"></label><label class="field">Margin<input id="eMargin" type="number" value="${i.margin||0}"></label><label class="field">GST %<input id="eGst" type="number" value="${i.gst||0}"></label><label class="field">Stock<input id="eStock" type="number" value="${i.stock||0}"></label><label class="field wide">Selling Price<input id="eSell" type="number" value="${i.sell||0}"></label></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="updateProduct('${id}')">Update Product</button></div>`)}
 function updateProduct(id){const st=getState(),i=st?.items?.find(x=>x.id===id);if(!i)return;const barcode=document.getElementById('eBarcode').value.trim();if(barcode&&st.items.some(x=>x.id!==id&&x.barcode===barcode))return alert('Barcode already exists');i.name=document.getElementById('eName').value.trim();if(!i.name)return alert('Enter product name');i.barcode=barcode;i.type=document.getElementById('eType').value;i.cost=Number(document.getElementById('eCost').value)||0;i.margin=Number(document.getElementById('eMargin').value)||0;i.sell=Number(document.getElementById('eSell').value)||0;i.gst=Number(document.getElementById('eGst').value)||0;i.stock=Number(document.getElementById('eStock').value)||0;if(typeof save==='function')save();closeModal();renderItems();updateStats()}
 function install(){window.openBillModal=launchBill;window.saveBillFixed=saveBillFixed;window.editItem=editItem;window.updateProduct=updateProduct;document.addEventListener('click',e=>{const b=e.target.closest('button[onclick*="openBillModal"]');if(b){e.preventDefault();e.stopImmediatePropagation();launchBill()}});}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();