// Robust billing launcher + product edit
(function(){
 function launchBill(){
  if(typeof window.openModal!=='function'){alert('Billing UI is still loading. Please refresh once.');return;}
  window.billCart=[];
  window.openModal('Create New Bill',`<label class="field">Customer Name<input id="bCustomer" placeholder="Walk-in Customer"></label><label class="field">Customer Mobile<input id="bMobile"></label><label class="field wide">🔎 Search Product / 📷 Barcode Scan<input id="bSearch" placeholder="Type product name or scan barcode"></label><div id="billSuggestions" class="suggestions"></div><div id="billLines" class="bill-lines"></div><div class="bill-adjustments"><label class="field">Discount Type<select id="billDiscountType"><option value="percent">Percentage (%)</option><option value="fixed">Fixed Amount (₹)</option></select></label><label class="field">Discount<input id="billDiscount" type="number" min="0" step="0.01" value="0"></label></div><div id="billSummary" class="bill-summary"></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="window.saveBillFixed ? window.saveBillFixed() : window.saveBill()">Generate Bill</button></div>`);
  if(typeof window.renderCart==='function')window.renderCart();
  const s=document.getElementById('bSearch');
  if(s){s.oninput=()=>typeof window.searchBillProducts==='function'&&window.searchBillProducts();s.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();if(typeof window.handleBarcodeKey==='function')window.handleBarcodeKey(e)}};s.focus()}
  const recalc=()=>{let sub=0,gst=0;(window.billCart||[]).forEach(l=>{const i=window.state?.items?.find(x=>x.id===l.id);if(i){const a=(Number(i.sell)||0)*(Number(l.qty)||0);sub+=a;gst+=a*(Number(i.gst)||0)/100}});const type=document.getElementById('billDiscountType')?.value||'percent',v=Number(document.getElementById('billDiscount')?.value)||0,d=type==='fixed'?Math.min(v,sub):sub*v/100,tax=Math.max(0,sub-d),g=sub?gst*tax/sub:0,net=tax+g;const sm=document.getElementById('billSummary');if(sm)sm.innerHTML=`<div><span>Subtotal</span><b>${money(sub)}</b></div><div><span>Discount</span><b>− ${money(d)}</b></div><div><span>GST</span><b>${money(g)}</b></div><div class="bill-net"><span>Net Amount</span><strong>${money(net)}</strong></div>`;const total=document.getElementById('bTotal');if(total)total.textContent=money(net)};
  document.getElementById('billDiscount')?.addEventListener('input',recalc);document.getElementById('billDiscountType')?.addEventListener('input',recalc);recalc();
 }
 function editItem(id){const i=window.state?.items?.find(x=>x.id===id);if(!i)return;window.openModal('Edit Product / Service',`<div class="modal-grid"><label class="field">Product / Service<input id="eName" value="${esc(i.name)}"></label><label class="field">Barcode<input id="eBarcode" value="${esc(i.barcode||'')}"></label><label class="field">Type<select id="eType"><option ${i.type==='Product'?'selected':''}>Product</option><option ${i.type==='Service'?'selected':''}>Service</option></select></label><label class="field">Cost Price<input id="eCost" type="number" value="${i.cost||0}"></label><label class="field">Margin<input id="eMargin" type="number" value="${i.margin||0}"></label><label class="field">GST %<input id="eGst" type="number" value="${i.gst||0}"></label><label class="field">Stock<input id="eStock" type="number" value="${i.stock||0}"></label><label class="field wide">Selling Price<input id="eSell" type="number" value="${i.sell||0}"></label></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="updateProduct('${id}')">Update Product</button></div>`)}
 function updateProduct(id){const i=window.state?.items?.find(x=>x.id===id);if(!i)return;const barcode=document.getElementById('eBarcode').value.trim();if(barcode&&state.items.some(x=>x.id!==id&&x.barcode===barcode))return alert('Barcode already exists');i.name=document.getElementById('eName').value.trim();if(!i.name)return alert('Enter product name');i.barcode=barcode;i.type=document.getElementById('eType').value;i.cost=Number(document.getElementById('eCost').value)||0;i.margin=Number(document.getElementById('eMargin').value)||0;i.sell=Number(document.getElementById('eSell').value)||0;i.gst=Number(document.getElementById('eGst').value)||0;i.stock=Number(document.getElementById('eStock').value)||0;save();closeModal();renderItems();updateStats()}
 function install(){window.openBillModal=launchBill;window.editItem=editItem;window.updateProduct=updateProduct;document.addEventListener('click',e=>{const b=e.target.closest('button[onclick*="openBillModal"]');if(b){e.preventDefault();e.stopImmediatePropagation();launchBill()}});}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();