// NR BizPro industry profiles: core billing stays common; selected-business features are exposed.
(function(){
 const profiles={
  footwear:{label:'Footwear / Chappal Shop',features:['Footwear Products','Brand Management','Size / Variant','Color / Variant','Barcode Billing','Stock & Reorder','Purchase Register','Sales Returns','Customer History','Sales Reports']},
  fertilizer:{label:'Fertilizer / Agriculture',features:['Fertilizer Stock','Seeds','Pesticides','Batch / Lot Tracking','Farmer Ledger','Supplier Management','Purchase Register','Sales Register','Credit / Due','Stock Alerts','Agriculture Reports']},
  garage:{label:'Garage / Service Center',features:['Vehicle Customers','Vehicle Number','Job Cards','Service / Labour','Spare Parts','Estimates','Service History','Next Service Reminder','Technician / Staff']},
  spareparts:{label:'Spare Parts',features:['Part Number / SKU','Vehicle Compatibility','Brand Management','Stock & Reorder','Purchase Register','Supplier Ledger','Sales Register','Warranty / Returns']},
  retail:{label:'Retail / Supermarket',features:['Barcode Billing','Stock & Reorder','Offers / Discounts','Purchase Register','Supplier Ledger','Customer Loyalty','Daily Sales Report']},
  restaurant:{label:'Restaurant / Bakery',features:['Table / Order Management','Kitchen Orders','Menu Items','Recipe / Ingredients','Raw Material Stock','Takeaway Orders','Daily Sales Report']},
  hardware:{label:'Hardware / Building Materials',features:['Item / SKU','Unit Management','Stock & Reorder','Supplier Ledger','Customer Credit','Purchase Register','Sales Register']},
  medical:{label:'Medical / Pharmacy',features:['Medicine Stock','Batch / Expiry','Supplier Management','Customer Ledger','Purchase Register','Sales Register','Expiry Alerts']},
  electronics:{label:'Electronics',features:['Serial Number','Warranty Tracking','Brand / Model','Stock & Reorder','Customer History','Supplier Ledger','Sales Register']},
  wholesale:{label:'Wholesale / Distributor',features:['Bulk Pricing','Party Ledger','Purchase Register','Sales Register','Stock & Reorder','Outstanding Dues','Supplier Ledger','Delivery Records']},
  clothing:{label:'Clothing / Fashion',features:['Size / Variant','Color / Variant','Barcode','Stock & Reorder','Purchase Register','Customer History','Sales Report']},
  professional:{label:'Professional Services',features:['Service Catalogue','Client Management','Estimates','Invoices','Payment Tracking','Expense Records','Service Reports']},
  general:{label:'General Business',features:['Products / Services','Stock','Customers','Sales Reports','Business Settings']}
 };
 function key(v){v=String(v||'').toLowerCase();if(v.includes('foot')||v.includes('chappal')||v.includes('shoe')||v.includes('slipper'))return'footwear';if(v.includes('fertil')||v.includes('agri'))return'fertilizer';if(v.includes('garage')||v.includes('service center'))return'garage';if(v.includes('spare'))return'spareparts';if(v.includes('supermarket')||v.includes('retail'))return'retail';if(v.includes('restaurant')||v.includes('bakery'))return'restaurant';if(v.includes('hardware')||v.includes('building'))return'hardware';if(v.includes('medical')||v.includes('pharmacy'))return'medical';if(v.includes('electronic'))return'electronics';if(v.includes('wholesale')||v.includes('distributor'))return'wholesale';if(v.includes('cloth')||v.includes('fashion'))return'clothing';if(v.includes('professional'))return'professional';return'general'}
 function profile(){return profiles[key(window.currentUser?.category||window.state?.settings?.category)]||profiles.general}
 function renderIndustry(){const p=profile(),panel=document.getElementById('industryModule');if(!panel)return;panel.innerHTML=`<div class="panel-head"><div><p class="eyebrow">BUSINESS MODULE</p><h2>${p.label}</h2><p class="muted">Only relevant features are shown for this business.</p></div></div><div class="quick-grid">${p.features.map(x=>`<button type="button"><b>${x}</b><span>${p.label}</span></button>`).join('')}</div>`}
 function apply(){renderIndustry()}
 function addIndustryTab(){if(document.getElementById('industryTab'))return;const nav=document.querySelector('.tabs');if(!nav)return;const b=document.createElement('button');b.className='tab';b.id='industryTab';b.dataset.tab='industryModule';b.textContent=profile().label+' Features';b.onclick=()=>window.showTab('industryModule');nav.appendChild(b);const main=document.querySelector('.shell');const s=document.createElement('section');s.id='industryModule';s.className='panel tab-panel';main.appendChild(s);renderIndustry()}
 function convertCategory(){const input=document.getElementById('suCategory');if(!input||input.tagName==='SELECT')return;const s=document.createElement('select');s.id='suCategory';s.required=true;['General Business','Retail / Supermarket','Footwear / Chappal Shop','Fertilizer / Agriculture','Garage / Service Center','Spare Parts','Wholesale / Distributor','Restaurant / Bakery','Hardware / Building Materials','Medical / Pharmacy','Electronics','Clothing / Fashion','Professional Services'].forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;s.appendChild(o)});input.replaceWith(s)}
 const obs=new MutationObserver(convertCategory);obs.observe(document.body,{childList:true,subtree:true});
 window.NRBizProBusinessModules={profiles,apply,profile};window.addEventListener('load',()=>{addIndustryTab();apply()});setTimeout(()=>{addIndustryTab();apply()},500);
})();