// NR BizPro universal industry profiles + interactive module workspaces
(function(){
 const profiles={
  footwear:{label:'Footwear / Chappal Shop',features:['Footwear Products','Brand Management','Size / Variant','Color / Variant','Barcode Billing','Stock & Reorder','Purchase Register','Sales Returns','Customer History','Sales Reports']},
  grocery:{label:'Grocery / General Store',features:['Products','Barcode Billing','Units','Stock & Reorder','Purchases','Suppliers','Customers','Offers / Discounts','Returns','Sales Reports']},
  fertilizer:{label:'Fertilizer / Agriculture',features:['Fertilizer Stock','Seeds','Pesticides','Batch / Lot Tracking','Farmer Ledger','Supplier Management','Purchase Register','Sales Register','Credit / Due','Stock Alerts','Agriculture Reports']},
  garage:{label:'Garage / Service Center',features:['Vehicle Customers','Vehicle Number','Job Cards','Service / Labour','Spare Parts','Estimates','Service History','Next Service Reminder','Technician / Staff']},
  spareparts:{label:'Spare Parts',features:['Part Number / SKU','Vehicle Compatibility','Brand Management','Barcode Billing','Stock & Reorder','Purchase Register','Supplier Ledger','Sales Register','Warranty / Returns']},
  evtwo:{label:'EV Two-Wheeler Showroom',features:['EV Vehicle / Model Master','Brand & Variant','Battery Type & Capacity','Motor Power & Range','Colour / Variant','Vehicle Price & On-Road Price','Vehicle Stock','Customer Management','Enquiry / Lead Management','Follow-up & Reminders','Test Drive Management','Quotation','Vehicle Booking','Advance Payment','Sales Invoice / Billing','Discount Management','Finance / EMI','Insurance','RTO / Registration','Accessories','Vehicle Delivery','Delivery Checklist','Warranty Tracking','Battery Warranty','Service Management','Service Reminders','Customer Vehicle History','Salesperson Management','Daily / Monthly Sales Reports','Model-wise Sales','Enquiry & Test Drive Reports','Booking Report','Pending Payment Report','Finance Report','Delivery Report']},
  retail:{label:'Retail / Supermarket',features:['Barcode Billing','Stock & Reorder','Offers / Discounts','Purchase Register','Supplier Ledger','Customer Loyalty','Returns','Daily Sales Report']},
  restaurant:{label:'Restaurant / Bakery',features:['Table / Order Management','Kitchen Orders','Menu Items','Recipe / Ingredients','Raw Material Stock','Takeaway Orders','Daily Sales Report']},
  hardware:{label:'Hardware / Building Materials',features:['Item / SKU','Unit Management','Stock & Reorder','Supplier Ledger','Customer Credit','Purchase Register','Sales Register','Returns']},
  medical:{label:'Medical / Pharmacy',features:['Medicine Stock','Batch / Expiry','Supplier Management','Customer Ledger','Purchase Register','Sales Register','Expiry Alerts','Returns']},
  electronics:{label:'Electronics / Mobile',features:['Serial Number','Warranty Tracking','Brand / Model','Stock & Reorder','Customer History','Supplier Ledger','Sales Register','Returns']},
  wholesale:{label:'Wholesale / Distributor',features:['Bulk Pricing','Party Ledger','Purchase Register','Sales Register','Stock & Reorder','Outstanding Dues','Supplier Ledger','Delivery Records']},
  clothing:{label:'Clothing / Fashion',features:['Size / Variant','Color / Variant','Barcode Billing','Stock & Reorder','Purchase Register','Customer History','Sales Returns','Sales Report']},
  furniture:{label:'Furniture',features:['Products','Size / Dimensions','Material','Stock','Purchases','Suppliers','Delivery','Customers','Billing','Reports']},
  jewellery:{label:'Jewellery',features:['Items','Purity','Weight','Making Charges','Stock','Purchases','Customers','Billing','Reports']},
  stationery:{label:'Stationery / Book Store',features:['Books / Items','Barcode','Author / Publisher','Stock','Purchases','Suppliers','Customers','Billing','Reports']},
  dairy:{label:'Dairy / Milk Products',features:['Products','Daily Stock','Purchases','Customers','Credit / Due','Billing','Reports']},
  salon:{label:'Salon / Beauty Parlour',features:['Services','Products','Customers','Appointments','Staff','Packages','Payments','Billing','Reports']},
  printing:{label:'Printing / Xerox / Online Services',features:['Services','Print Orders','Xerox','Scanning','Customer Jobs','Payments','Billing','Reports']},
  professional:{label:'Professional Services',features:['Services','Clients','Appointments','Estimates','Invoices','Payments','Expenses','Reports']},
  construction:{label:'Construction / Building Materials',features:['Materials','Units','Stock','Purchases','Suppliers','Site / Project','Customer Credit','Delivery','Billing','Reports']},
  general:{label:'General Business',features:['Products / Services','Stock','Customers','Sales Reports','Business Settings']}
 };
 function key(v){const s=String(v||'').toLowerCase();if(s.includes('ev two')||s.includes('ev 2')||s.includes('electric two')||s.includes('ev scooter')||s.includes('ev bike'))return'evtwo';if(s.includes('foot')||s.includes('chappal')||s.includes('shoe')||s.includes('slipper'))return'footwear';if(s.includes('grocery')||s.includes('general store'))return'grocery';if(s.includes('fertil')||s.includes('agri'))return'fertilizer';if(s.includes('garage')||s.includes('service center'))return'garage';if(s.includes('spare'))return'spareparts';if(s.includes('supermarket')||s.includes('retail'))return'retail';if(s.includes('restaurant')||s.includes('bakery'))return'restaurant';if(s.includes('hardware')||s.includes('building'))return'hardware';if(s.includes('medical')||s.includes('pharmacy'))return'medical';if(s.includes('electronic')||s.includes('mobile'))return'electronics';if(s.includes('wholesale')||s.includes('distributor'))return'wholesale';if(s.includes('cloth')||s.includes('fashion'))return'clothing';if(s.includes('furniture'))return'furniture';if(s.includes('jewell'))return'jewellery';if(s.includes('stationery')||s.includes('book'))return'stationery';if(s.includes('dairy')||s.includes('milk'))return'dairy';if(s.includes('salon')||s.includes('beauty'))return'salon';if(s.includes('printing')||s.includes('xerox')||s.includes('online service'))return'printing';if(s.includes('professional'))return'professional';if(s.includes('construction'))return'construction';return'general'}
 function profile(){return profiles[key(window.currentUser?.category||window.state?.settings?.category)]||profiles.general}
 function moduleStore(){if(!window.state)return{};window.state.moduleData=window.state.moduleData||{};return window.state.moduleData}
 function save(){try{window.save&&window.save()}catch(e){}}
 function esc(v){return String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#39;'}[m]))}
 function fieldsFor(name){
  const n=name.toLowerCase();
  if(n.includes('vehicle / model'))return[['Brand','text'],['Model','text'],['Variant','text'],['Battery Capacity','text'],['Range','text'],['Motor Power','text'],['Price','number'],['Opening Stock','number']];
  if(n.includes('vehicle stock'))return[['Vehicle / Model','text'],['VIN / Chassis No','text'],['Colour','text'],['Stock Status','text']];
  if(n.includes('customer'))return[['Customer Name','text'],['Mobile','tel'],['Email','email'],['Address','text']];
  if(n.includes('enquiry')||n.includes('lead'))return[['Customer','text'],['Vehicle / Model','text'],['Mobile','tel'],['Lead Status','text'],['Follow-up Date','date']];
  if(n.includes('test drive'))return[['Customer','text'],['Vehicle / Model','text'],['Date','date'],['Time','time'],['Status','text']];
  if(n.includes('quotation'))return[['Customer','text'],['Vehicle / Model','text'],['Quoted Amount','number'],['Discount','number'],['Validity','date']];
  if(n.includes('booking'))return[['Customer','text'],['Vehicle / Model','text'],['Booking Amount','number'],['Booking Date','date'],['Status','text']];
  if(n.includes('finance')||n.includes('emi'))return[['Customer','text'],['Loan Amount','number'],['Down Payment','number'],['EMI','number'],['Tenure','text'],['Finance Company','text']];
  if(n.includes('insurance'))return[['Customer','text'],['Vehicle','text'],['Policy Number','text'],['Expiry Date','date']];
  if(n.includes('rto')||n.includes('registration'))return[['Customer','text'],['Vehicle','text'],['Registration No','text'],['RTO Status','text']];
  if(n.includes('accessor'))return[['Accessory','text'],['Quantity','number'],['Price','number'],['Stock','number']];
  if(n.includes('delivery'))return[['Customer','text'],['Vehicle','text'],['Delivery Date','date'],['Status','text']];
  if(n.includes('warranty'))return[['Customer','text'],['Vehicle','text'],['Warranty Start','date'],['Warranty End','date']];
  if(n.includes('service')||n.includes('job card'))return[['Customer','text'],['Vehicle','text'],['Service Date','date'],['Work Details','text'],['Amount','number'],['Next Service','date']];
  if(n.includes('product')||n.includes('stock')||n.includes('item')||n.includes('part')||n.includes('medicine')||n.includes('material'))return[['Item / Product','text'],['Code / Barcode','text'],['Quantity','number'],['Selling Price','number'],['Purchase Price','number']];
  if(n.includes('report'))return[['Report Note','text']];
  return[['Name / Party','text'],['Mobile','tel'],['Details','text'],['Amount','number']];
 }
 function openFeature(name){
  const box=document.getElementById('industryWorkspace');if(!box)return;
  const store=moduleStore(), rows=store[name]||[], fields=fieldsFor(name);
  box.innerHTML=`<div class="module-workspace"><div class="panel-head"><div><p class="eyebrow">WORKSPACE</p><h2>${esc(name)}</h2><p class="muted">Add, save and review test records for this business feature.</p></div><button class="secondary" type="button" id="closeWorkspace">Close</button></div><form id="moduleForm" class="form-grid">${fields.map((f,i)=>`<label>${esc(f[0])}<input id="mf${i}" type="${f[1]}" ${f[1]==='number'?'min="0" step="0.01"':''}></label>`).join('')}<div class="wide"><button class="primary" type="submit">Save Record</button></div></form><div class="table-wrap" style="margin-top:16px"><table><thead><tr>${fields.map(f=>`<th>${esc(f[0])}</th>`).join('')}<th>Action</th></tr></thead><tbody>${rows.map((r,ri)=>`<tr>${fields.map((f,i)=>`<td>${esc(r[i]||'—')}</td>`).join('')}<td><button type="button" class="secondary" data-del="${ri}">Delete</button></td></tr>`).join('')||`<tr><td colspan="${fields.length+1}" class="empty">No records yet.</td></tr>`}</tbody></table></div></div>`;
  document.getElementById('closeWorkspace').onclick=()=>{box.innerHTML='';};
  document.getElementById('moduleForm').onsubmit=e=>{e.preventDefault();const vals=fields.map((_,i)=>document.getElementById('mf'+i).value.trim());if(!vals.some(Boolean))return alert('Enter at least one value');store[name]=rows.concat([vals]);save();openFeature(name);};
  box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{rows.splice(+b.dataset.del,1);store[name]=rows;save();openFeature(name);});
  box.scrollIntoView({behavior:'smooth',block:'start'});
 }
 function renderIndustry(){const p=profile(),panel=document.getElementById('industryModule');if(!panel)return;panel.innerHTML=`<div class="panel-head"><div><p class="eyebrow">BUSINESS MODULE</p><h2>${esc(p.label)}</h2><p class="muted">Only relevant features are shown. Click any feature to open its working test workspace.</p></div><button class="secondary" type="button" id="featureTest">Feature Test</button></div><div class="quick-grid">${p.features.map((x,i)=>`<button type="button" class="industry-feature" data-feature="${i}"><b>✓ ${esc(x)}</b><span>Open workspace</span></button>`).join('')}</div><div id="industryWorkspace"></div>`;
  panel.querySelectorAll('.industry-feature').forEach(b=>b.onclick=()=>openFeature(p.features[+b.dataset.feature]));
  document.getElementById('featureTest').onclick=()=>runTest();
 }
 function runTest(){const p=profile(),store=moduleStore();const missing=p.features.filter(f=>!Array.isArray(store[f])||store[f].length===0);const existing=p.features.length-missing.length;alert(`${p.label} Feature Test\n\nConfigured features: ${p.features.length}\nWith test records: ${existing}\nPending test records: ${missing.length}\n\nOpen each feature and add a sample record to validate the workflow.`)}
 function apply(){renderIndustry();const tab=document.getElementById('industryTab');if(tab)tab.textContent=profile().label+' Features'}
 function addIndustryTab(){if(document.getElementById('industryTab'))return;const nav=document.querySelector('.tabs');if(!nav)return;const b=document.createElement('button');b.className='tab';b.id='industryTab';b.dataset.tab='industryModule';b.textContent=profile().label+' Features';b.onclick=()=>window.showTab('industryModule');nav.appendChild(b);const main=document.querySelector('.shell');if(!main)return;const s=document.createElement('section');s.id='industryModule';s.className='panel tab-panel';main.appendChild(s);renderIndustry()}
 function convertCategory(){const input=document.getElementById('suCategory');if(!input||input.tagName==='SELECT')return;const s=document.createElement('select');s.id='suCategory';s.required=true;const opts=['General Business','Grocery / General Store','Footwear / Chappal Shop','Fertilizer / Agriculture','Garage / Service Center','Spare Parts','EV Two-Wheeler Showroom','Retail / Supermarket','Restaurant / Bakery','Hardware / Building Materials','Medical / Pharmacy','Electronics / Mobile','Clothing / Fashion','Furniture','Jewellery','Stationery / Book Store','Dairy / Milk Products','Salon / Beauty Parlour','Printing / Xerox / Online Services','Wholesale / Distributor','Professional Services','Construction / Building Materials','Other Business'];opts.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;s.appendChild(o)});input.replaceWith(s)}
 const obs=new MutationObserver(()=>{convertCategory();if(window.currentUser||window.state)apply()});obs.observe(document.body,{childList:true,subtree:true});window.NRBizProBusinessModules={profiles,key,apply,profile,openFeature,runTest};window.addEventListener('load',()=>{addIndustryTab();apply();convertCategory()});setTimeout(()=>{addIndustryTab();apply();convertCategory()},700);
})();