// NR BizPro universal industry profiles
(function(){
 const profiles={
 footwear:{label:'Footwear / Chappal Shop',features:['Footwear Products','Brand Management','Size / Variant','Color / Variant','Barcode Billing','Stock & Reorder','Purchase Register','Sales Returns','Customer History','Sales Reports']},
 grocery:{label:'Grocery / General Store',features:['Products','Barcode Billing','Units','Stock & Reorder','Purchases','Suppliers','Customers','Offers / Discounts','Returns','Sales Reports']},
 fertilizer:{label:'Fertilizer / Agriculture',features:['Fertilizer Stock','Seeds','Pesticides','Batch / Lot Tracking','Farmer Ledger','Supplier Management','Purchase Register','Sales Register','Credit / Due','Stock Alerts','Agriculture Reports']},
 garage:{label:'Garage / Service Center',features:['Vehicle Customers','Vehicle Number','Job Cards','Service / Labour','Spare Parts','Estimates','Service History','Next Service Reminder','Technician / Staff']},
 spareparts:{label:'Spare Parts',features:['Part Number / SKU','Vehicle Compatibility','Brand Management','Barcode Billing','Stock & Reorder','Purchase Register','Supplier Ledger','Sales Register','Warranty / Returns']},
 retail:{label:'Retail / Supermarket',features:['Barcode Billing','Stock & Reorder','Offers / Discounts','Purchase Register','Supplier Ledger','Customer Loyalty','Returns','Daily Sales Report']},
 restaurant:{label:'Restaurant / Bakery',features:['Table / Order Management','Kitchen Orders','Menu Items','Recipe / Ingredients','Raw Material Stock','Takeaway Orders','Daily Sales Report']},
 hardware:{label:'Hardware / Building Materials',features:['Item / SKU','Unit Management','Stock & Reorder','Supplier Ledger','Customer Credit','Purchase Register','Sales Register','Returns']},
 medical:{label:'Medical / Pharmacy',features:['Medicine Stock','Batch / Expiry','Supplier Management','Customer Ledger','Purchase Register','Sales Register','Expiry Alerts','Returns']},
 electronics:{label:'Electronics / Mobile',features:['Serial Number','Warranty Tracking','Brand / Model','Stock & Reorder','Customer History','Supplier Ledger','Sales Register','Returns']},
 wholesale:{label:'Wholesale / Distributor',features:['Bulk Pricing','Party Ledger','Purchase Register','Sales Register','Stock & Reorder','Outstanding Dues','Supplier Ledger','Delivery Records']},
 clothing:{label:'Clothing / Fashion',features:['Size / Variant','Color / Variant','Barcode Billing','Stock & Reorder','Purchase Register','Customer History','Sales Returns','Sales Report']},
 furniture:{label:'Furniture',features:['Products','Size / Dimensions','Material','Stock','Purchases','Suppliers','Delivery','Customers','Billing','Reports']},
 jewellery:{label:'Jewellery',features:['Items','Purity','Weight','Making Charges','Stock','Purchases','Customers','Billing','Reports']},
 stationery:{label:'Stationery / Book Store',features:['Books / Items','Barcode','Author / Publisher','Stock','Purchases','Suppliers','Customers','Billing','Reports']},
 dairy:{label:'Dairy / Milk Products',features:['Products','Daily Stock','Purchases','Customers','Credit / Due','Billing','Reports']},
 salon:{label:'Salon / Beauty Parlour',features:['Services','Products','Customers','Appointments','Staff','Packages','Payments','Billing','Reports']},
 printing:{label:'Printing / Xerox / Online Services',features:['Services','Print Orders','Xerox','Scanning','Customer Jobs','Payments','Billing','Reports']},
 professional:{label:'Professional Services',features:['Services','Clients','Appointments','Estimates','Invoices','Payments','Expenses','Reports']},
 construction:{label:'Construction / Building Materials',features:['Materials','Units','Stock','Purchases','Suppliers','Site / Project','Customer Credit','Delivery','Billing','Reports']},
 general:{label:'General Business',features:['Products / Services','Stock','Customers','Sales Reports','Business Settings']}
 };
 function key(v){const s=String(v||'').toLowerCase();if(s.includes('foot')||s.includes('chappal')||s.includes('shoe')||s.includes('slipper'))return'footwear';if(s.includes('grocery')||s.includes('general store'))return'grocery';if(s.includes('fertil')||s.includes('agri'))return'fertilizer';if(s.includes('garage')||s.includes('service center'))return'garage';if(s.includes('spare'))return'spareparts';if(s.includes('supermarket')||s.includes('retail'))return'retail';if(s.includes('restaurant')||s.includes('bakery'))return'restaurant';if(s.includes('hardware')||s.includes('building'))return'hardware';if(s.includes('medical')||s.includes('pharmacy'))return'medical';if(s.includes('electronic')||s.includes('mobile'))return'electronics';if(s.includes('wholesale')||s.includes('distributor'))return'wholesale';if(s.includes('cloth')||s.includes('fashion'))return'clothing';if(s.includes('furniture'))return'furniture';if(s.includes('jewell'))return'jewellery';if(s.includes('stationery')||s.includes('book'))return'stationery';if(s.includes('dairy')||s.includes('milk'))return'dairy';if(s.includes('salon')||s.includes('beauty'))return'salon';if(s.includes('printing')||s.includes('xerox')||s.includes('online service'))return'printing';if(s.includes('professional'))return'professional';if(s.includes('construction'))return'construction';return'general'}
 function profile(){return profiles[key(window.currentUser?.category||window.state?.settings?.category)]||profiles.general}
 function renderIndustry(){const p=profile(),panel=document.getElementById('industryModule');if(!panel)return;panel.innerHTML=`<div class="panel-head"><div><p class="eyebrow">BUSINESS MODULE</p><h2>${p.label}</h2><p class="muted">Only relevant features are shown for this business.</p></div></div><div class="quick-grid">${p.features.map(x=>`<button type="button"><b>${x}</b><span>${p.label}</span></button>`).join('')}</div>`}
 function apply(){renderIndustry();const tab=document.getElementById('industryTab');if(tab)tab.textContent=profile().label+' Features'}
 function addIndustryTab(){if(document.getElementById('industryTab'))return;const nav=document.querySelector('.tabs');if(!nav)return;const b=document.createElement('button');b.className='tab';b.id='industryTab';b.dataset.tab='industryModule';b.textContent=profile().label+' Features';b.onclick=()=>window.showTab('industryModule');nav.appendChild(b);const main=document.querySelector('.shell');const s=document.createElement('section');s.id='industryModule';s.className='panel tab-panel';main.appendChild(s);renderIndustry()}
 function convertCategory(){const input=document.getElementById('suCategory');if(!input||input.tagName==='SELECT')return;const s=document.createElement('select');s.id='suCategory';s.required=true;['General Business','Grocery / General Store','Footwear / Chappal Shop','Fertilizer / Agriculture','Garage / Service Center','Spare Parts','Retail / Supermarket','Restaurant / Bakery','Hardware / Building Materials','Medical / Pharmacy','Electronics / Mobile','Clothing / Fashion','Furniture','Jewellery','Stationery / Book Store','Dairy / Milk Products','Salon / Beauty Parlour','Printing / Xerox / Online Services','Wholesale / Distributor','Professional Services','Construction / Building Materials','Other Business'].forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;s.appendChild(o)});input.replaceWith(s)}
 const obs=new MutationObserver(convertCategory);obs.observe(document.body,{childList:true,subtree:true});window.NRBizProBusinessModules={profiles,key,apply,profile};window.addEventListener('load',()=>{addIndustryTab();apply();convertCategory()});setTimeout(()=>{addIndustryTab();apply();convertCategory()},700);
})();