// NR BizPro Clothing / Fashion module. Loaded alongside the core business modules.
(function(){
  const brands=['Levis','Peter England','Allen Solly','Van Heusen','Louis Philippe','Puma','Adidas','Nike','Raymond','Mufti','Spykar','Manyavar','Biba','W for Woman','Aurelia','Fabindia','Max Fashion','Other Brand'];
  function active(){return /clothing|fashion/i.test(document.getElementById('businessCategory')?.value||'')}
  function panel(){let p=document.getElementById('clothingModule');if(p)return p;const shell=document.querySelector('#app main.shell');if(!shell)return null;p=document.createElement('section');p.id='clothingModule';p.className='panel';p.style.cssText='display:none;margin:0 0 18px';const tabs=shell.querySelector('.tabs');tabs?shell.insertBefore(p,tabs):shell.appendChild(p);return p}
  function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function list(){if(typeof state==='undefined'||!state)return brands;state.clothingBrands=Array.isArray(state.clothingBrands)?state.clothingBrands:[];return [...new Set(brands.concat(state.clothingBrands))]}
  function render(){const p=panel();if(!p)return;if(!active()){p.style.display='none';return}if(p.dataset.ready==='1'){p.style.display='block';return}p.dataset.ready='1';p.innerHTML='<div class="panel-head"><div><p class="eyebrow">FASHION BUSINESS</p><h2>👕 Clothing / Fashion</h2><p class="muted">Complete garment inventory with brand, size, color, design and collection-wise stock.</p></div></div><div class="card" style="padding:16px"><h3>Brand Management</h3><div style="display:flex;gap:10px;flex-wrap:wrap;align-items:end"><label style="flex:1;min-width:240px">Add Brand<input id="clNewBrand" placeholder="Enter any clothing brand"></label><button class="secondary" type="button" id="clAddBrand">+ Add Brand</button></div><div id="clBrandList" style="display:flex;gap:8px;flex-wrap:wrap;margin-top:12px"></div></div><div class="card" style="margin-top:16px;padding:16px"><h3>Size / Color / Design-wise Product Management</h3><div class="form-grid"><label>Product Name<input id="clName" placeholder="Shirt / T-Shirt / Saree"></label><label>Brand<select id="clBrand"></select></label><label>Segment<select id="clSegment"><option>Men</option><option>Women</option><option>Kids</option><option>Unisex</option></select></label><label>Category<select id="clCategory"><option>Shirts</option><option>T-Shirts</option><option>Trousers</option><option>Jeans</option><option>Sarees</option><option>Dresses</option><option>Kids Wear</option><option>Innerwear</option><option>Footwear</option><option>Accessories</option><option>Other</option></select></label><label>Size<input id="clSize" placeholder="S / M / L / XL / 32 / 34 / Free Size"></label><label>Color<input id="clColor" placeholder="Black / Blue / Red"></label><label>Design / Model<input id="clDesign" placeholder="Model / SKU / Design"></label><label>Season / Collection<input id="clSeason" placeholder="Festive / Summer / 2026"></label><label>MRP<input id="clMrp" type="number" min="0" step="0.01" value="0"></label><label>Purchase Price<input id="clCost" type="number" min="0" step="0.01" value="0"></label><label>Selling Price<input id="clSell" type="number" min="0" step="0.01" value="0"></label><label>GST %<input id="clGst" type="number" min="0" step="0.01" value="0"></label><label>Opening Stock<input id="clStock" type="number" min="0" step="1" value="0"></label></div><div style="display:flex;justify-content:flex-end;margin-top:12px"><button class="primary" type="button" id="clAddProduct">+ Add Clothing Variant</button></div><div class="table-wrap" style="margin-top:16px"><table><thead><tr><th>Product</th><th>Brand</th><th>Segment</th><th>Category</th><th>Size</th><th>Color</th><th>Design</th><th>Selling</th><th>Stock</th></tr></thead><tbody id="clTable"></tbody></table></div></div>';
    const select=document.getElementById('clBrand');select.innerHTML=list().map(b=>'<option value="'+esc(b)+'">'+esc(b)+'</option>').join('');const chips=document.getElementById('clBrandList');chips.innerHTML=list().map(b=>'<span style="padding:7px 10px;border:1px solid #dbe5f2;border-radius:999px;background:#f8fafc">'+esc(b)+'</span>').join('');
    document.getElementById('clAddBrand').onclick=function(){const input=document.getElementById('clNewBrand'),name=input.value.trim();if(!name)return alert('Enter a brand name.');if(typeof state==='undefined'||!state)return;if(list().some(b=>b.toLowerCase()===name.toLowerCase()))return alert('This brand already exists.');state.clothingBrands=Array.isArray(state.clothingBrands)?state.clothingBrands:[];state.clothingBrands.push(name);if(typeof save==='function')save();select.innerHTML=list().map(b=>'<option value="'+esc(b)+'">'+esc(b)+'</option>').join('');chips.innerHTML=list().map(b=>'<span style="padding:7px 10px;border:1px solid #dbe5f2;border-radius:999px;background:#f8fafc">'+esc(b)+'</span>').join('');input.value=''};
    function refresh(){const tb=document.getElementById('clTable');if(!tb)return;const rows=(typeof state!=='undefined'&&state.items||[]).filter(i=>i.businessType==='clothing');tb.innerHTML=rows.length?rows.map(i=>'<tr><td><b>'+esc(i.name)+'</b></td><td>'+esc(i.brand||'—')+'</td><td>'+esc(i.clSegment||'—')+'</td><td>'+esc(i.clCategory||'—')+'</td><td>'+esc(i.clSize||'—')+'</td><td>'+esc(i.clColor||'—')+'</td><td>'+esc(i.clDesign||'—')+'</td><td>₹'+Number(i.sell||0).toFixed(2)+'</td><td>'+Number(i.stock||0)+'</td></tr>').join(''):'<tr><td colspan="9" class="empty">No clothing variants added yet.</td></tr>'}
    document.getElementById('clAddProduct').onclick=function(){const name=clName.value.trim(),brand=clBrand.value,clSegment=document.getElementById('clSegment').value,clCategory=document.getElementById('clCategory').value,clSize=clSizeEl.value.trim(),clColor=clColorEl.value.trim(),clDesign=clDesignEl.value.trim(),clSeason=clSeasonEl.value.trim(),mrp=Number(clMrp.value||0),cost=Number(clCost.value||0),sell=Number(clSell.value||0),gst=Number(clGst.value||0),stock=Number(clStock.value||0);if(!name||!clSize||!clColor)return alert('Enter Product Name, Size and Color.');state.items=state.items||[];state.items.push({id:crypto.randomUUID(),name,brand,clSegment,clCategory,clSize,clColor,clDesign,clSeason,mrp,cost,sell,gst,stock,businessType:'clothing',type:'Product',barcode:'',margin:0,marginType:'fixed'});if(typeof save==='function')save();refresh();if(typeof renderItems==='function')renderItems();if(typeof updateStats==='function')updateStats();clName.value='';clSizeEl.value='';clColorEl.value='';clDesignEl.value='';clSeasonEl.value='';clStock.value='0'};
    const clSizeEl=document.getElementById('clSize'),clColorEl=document.getElementById('clColor');refresh();p.style.display='block';
  }
  function boot(){render();const app=document.getElementById('app');if(app)new MutationObserver(()=>{if(!app.classList.contains('hidden'))render()}).observe(app,{attributes:true,attributeFilter:['class']});const cat=document.getElementById('businessCategory');if(cat)cat.addEventListener('change',()=>{const p=document.getElementById('clothingModule');if(p)p.dataset.ready='';render()})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();