// NR BizPro — Dairy / Milk Products module
(function(){
  const category=()=>String((typeof currentUser!=='undefined'&&currentUser?.category)||(typeof state!=='undefined'&&state?.settings?.category)||'');
  const isDairy=()=>/dairy|milk products/i.test(category());
  const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n)||0);
  function render(){if(!isDairy())return;let p=document.getElementById('dairyModule');if(!p){const shell=document.querySelector('#app main.shell');if(!shell)return;p=document.createElement('section');p.id='dairyModule';p.className='panel';p.style.margin='0 0 18px';const nav=shell.querySelector('.tabs');nav?shell.insertBefore(p,nav):shell.appendChild(p)}
    p.innerHTML=`<div class="panel-head"><div><p class="eyebrow">DAIRY INVENTORY</p><h2>Milk & Dairy Product Management</h2><p class="muted">Manage milk, curd, paneer, butter, ghee, ice cream and other dairy products by pack, batch and stock.</p></div></div><div class="form-grid"><label>Product Name<input id="dairyName" placeholder="Milk / Curd / Paneer"></label><label>Brand / Manufacturer<input id="dairyBrand" placeholder="Amul / Heritage / Local"></label><label>Category<select id="dairyType"><option>Milk</option><option>Curd</option><option>Buttermilk</option><option>Paneer</option><option>Butter</option><option>Ghee</option><option>Cheese</option><option>Ice Cream</option><option>Flavoured Milk</option><option>Other</option></select></label><label>Pack Size<input id="dairyPack" placeholder="500 ml / 1 L / 200 g"></label><label>Unit<select id="dairyUnit"><option>Piece</option><option>Pack</option><option>Box</option><option>Kg</option><option>Gram</option><option>Litre</option><option>ML</option></select></label><label>Batch No.<input id="dairyBatch"></label><label>Expiry / Best Before<input id="dairyExpiry" type="date"></label><label>Cost Price<input id="dairyCost" type="number" min="0" step="0.01" value="0"></label><label>Selling Price<input id="dairySell" type="number" min="0" step="0.01" value="0"></label><label>GST %<input id="dairyGst" type="number" min="0" step="0.01" value="0"></label><label>Opening Stock<input id="dairyStock" type="number" min="0" step="0.01" value="0"></label></div><div style="display:flex;justify-content:flex-end;margin-top:12px"><button class="primary" type="button" id="addDairy">+ Add Dairy Product</button></div><div class="table-wrap" style="margin-top:16px"><table><thead><tr><th>Product</th><th>Brand</th><th>Category</th><th>Pack</th><th>Batch</th><th>Expiry</th><th>Selling</th><th>Stock</th></tr></thead><tbody id="dairyTable"></tbody></table></div>`;
    const refresh=()=>{const tb=document.getElementById('dairyTable');if(!tb)return;const list=(typeof state!=='undefined'&&state?.items||[]).filter(i=>i.businessType==='dairy');tb.innerHTML=list.length?list.map(i=>`<tr><td><b>${esc(i.name)}</b></td><td>${esc(i.brand||'—')}</td><td>${esc(i.dairyType||'—')}</td><td>${esc(i.packSize||'—')}</td><td>${esc(i.batchNo||'—')}</td><td>${esc(i.expiry||'—')}</td><td>${money(i.sell)}</td><td>${Number(i.stock||0)}</td></tr>`).join(''):'<tr><td colspan="8" class="empty">No dairy products added yet.</td></tr>'};
    document.getElementById('addDairy').onclick=()=>{const name=dairyName.value.trim();if(!name)return alert('Enter product name');state.items=state.items||[];state.items.push({id:crypto.randomUUID(),name,brand:dairyBrand.value.trim(),dairyType:dairyType.value,packSize:dairyPack.value.trim(),unit:dairyUnit.value,batchNo:dairyBatch.value.trim(),expiry:dairyExpiry.value,cost:+dairyCost.value||0,sell:+dairySell.value||0,gst:+dairyGst.value||0,stock:+dairyStock.value||0,type:'Product',businessType:'dairy'});save();refresh();renderItems();updateStats()};refresh();
  }
  window.addEventListener('load',()=>setTimeout(render,300));window.addEventListener('loginSuccess',()=>setTimeout(render,100));window.addEventListener('categoryChanged',()=>setTimeout(render,50));
})();