// NR BizPro production bridge: PostgreSQL auth/data plus phone + email verification.
let serverData={items:[],bills:[],settings:{name:'Your Business',category:'General Business',mobile:'',gst:'',address:''}};
const api=async(path,opts={})=>{const r=await fetch(path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||'Request failed');return j};
const localState=()=>serverData;
loadData=(id)=>localState();
save=()=>{if(currentUser&&state)api('/api/data',{method:'PUT',body:JSON.stringify({data:state})}).catch(e=>console.error(e));};
persistUser=()=>{};
async function fetchMe(){const r=await api('/api/auth?action=me');currentUser=r.user;const d=await api('/api/data');serverData=d.data||serverData;state=serverData;return currentUser}
function otpScreen(message=''){const el=document.getElementById('authContent');el.innerHTML=`<div class="auth-title"><h1>Verify your account</h1><p>We sent one OTP to <b>${esc(currentUser?.mobile||'your phone')}</b> and another to <b>${esc(currentUser?.email||'your email')}</b>.</p></div>${message?`<div class="notice">${esc(message)}</div>`:''}<div class="auth-grid"><label>Phone OTP<input id="phoneOtp" inputmode="numeric" maxlength="6" placeholder="6 digit OTP"></label><label>Email OTP<input id="emailOtp" inputmode="numeric" maxlength="6" placeholder="6 digit OTP"></label></div><div class="modal-actions" style="justify-content:stretch;flex-wrap:wrap"><button class="primary auth-btn" onclick="verifyBothOtps()">Verify Phone & Email</button><button class="secondary auth-btn" onclick="resendOtp('phone')">Resend Phone OTP</button><button class="secondary auth-btn" onclick="resendOtp('email')">Resend Email OTP</button></div><p class="small-note">OTP expires in 10 minutes. You can request a new OTP after 60 seconds.</p>`}
async function sendSignupOtps(){try{await api('/api/otp?action=send',{method:'POST',body:JSON.stringify({})});otpScreen('OTP sent successfully. Check your phone and email.')}catch(e){otpScreen(e.message)}}
async function verifyBothOtps(){const phone=document.getElementById('phoneOtp').value.trim(),email=document.getElementById('emailOtp').value.trim();if(!phone||!email)return otpScreen('Enter both OTPs.');try{const p=await api('/api/otp?action=verify',{method:'POST',body:JSON.stringify({channel:'phone',otp:phone})});if(!p.phoneVerified)throw new Error('Phone verification failed.');const m=await api('/api/otp?action=verify',{method:'POST',body:JSON.stringify({channel:'email',otp:email})});if(!m.verified)throw new Error('Email verification failed.');currentUser={...currentUser,phoneVerified:true,emailVerified:true};renderAuth('plans','Phone and email verified successfully. Choose your plan to activate billing.')}catch(e){otpScreen(e.message)}}
async function resendOtp(channel){try{const r=await api('/api/otp?action=resend',{method:'POST',body:JSON.stringify({channel})});otpScreen(r.message)}catch(e){otpScreen(e.message)}}
async function signup(e){e.preventDefault();try{const business=document.getElementById('suBusiness').value.trim(),owner=document.getElementById('suOwner').value.trim(),mobile=document.getElementById('suMobile').value.trim(),email=document.getElementById('suEmail').value.trim().toLowerCase(),category=document.getElementById('suCategory').value.trim(),gst=document.getElementById('suGst').value.trim(),password=document.getElementById('suPassword').value;const r=await api('/api/auth',{method:'POST',body:JSON.stringify({action:'signup',business,owner,mobile,email,category,gst,password})});currentUser=r.user;serverData={items:[],bills:[],settings:{name:business,category,mobile,gst,address:''}};state=serverData;await sendSignupOtps()}catch(err){renderAuth('signup',err.message)}}
async function login(e){e.preventDefault();try{const id=document.getElementById('loginId').value.trim().toLowerCase(),password=document.getElementById('loginPassword').value;const r=await api('/api/auth',{method:'POST',body:JSON.stringify({action:'login',id,password})});currentUser=r.user;if(r.verificationRequired){await sendSignupOtps();return}if(currentUser.status==='pending'||currentUser.status==='expired'){renderAuth('plans',currentUser.status==='expired'?'Your subscription has expired. Renew to continue billing.':'Your account is verified. Choose a subscription to activate billing.');return}const d=await api('/api/data');serverData=d.data;state=serverData;showApp()}catch(err){renderAuth('login',err.message)}}
async function startSubscription(plan){if(!currentUser)return;try{const r=await api('/api/auth',{method:'POST',body:JSON.stringify({action:'pending',plan})});currentUser=r.user;renderAuth('payment')}catch(err){alert(err.message)}}
async function verifyRazorpayPayment(response){try{const res=await fetch('/api/verify-payment',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(response)});const data=await res.json();if(!res.ok||!data.verified)throw new Error(data.error||'Payment verification failed.');currentUser={...currentUser,...data.user,subscriptionEnds:data.user.subscription_ends,pendingPlan:data.user.pending_plan,pendingAmount:Number(data.user.pending_amount||0),lastPaymentId:data.user.last_payment_id};serverData=(await api('/api/data')).data;state=serverData;showApp()}catch(error){alert(error.message||'Payment verification failed. Your account was not activated.')}}
async function logout(){try{await api('/api/auth',{method:'POST',body:JSON.stringify({action:'logout'})})}catch{}currentUser=null;state=null;serverData={items:[],bills:[],settings:{name:'Your Business',category:'General Business',mobile:'',gst:'',address:''}};document.getElementById('app').classList.add('hidden');document.getElementById('authScreen').classList.remove('hidden');renderAuth('login')}
async function checkSession(){try{await fetchMe();if(!currentUser.phoneVerified||!currentUser.emailVerified){await sendSignupOtps();return}if(currentUser.status!=='active'||!currentUser.subscriptionEnds||new Date(currentUser.subscriptionEnds)<=new Date()){if(currentUser.status==='active')currentUser.status='expired';renderAuth('plans','Your subscription is not active. Choose a plan to continue.');return}showApp()}catch{renderAuth('login')}}
checkSession();
