// NR BizPro production bridge: moves auth and business data from browser storage to PostgreSQL.
let serverData={items:[],bills:[],settings:{name:'Your Business',category:'General Business',mobile:'',gst:'',address:''}};
const api=async(path,opts={})=>{const r=await fetch(path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||'Request failed');return j};
const localState=()=>serverData;
loadData=(id)=>localState();
save=()=>{if(currentUser&&state)api('/api/data',{method:'PUT',body:JSON.stringify({data:state})}).catch(e=>console.error(e));};
persistUser=()=>{};
async function fetchMe(){const r=await api('/api/auth?action=me');currentUser=r.user;const d=await api('/api/data');serverData=d.data||serverData;state=serverData;return currentUser}
async function signup(e){e.preventDefault();try{const business=document.getElementById('suBusiness').value.trim(),owner=document.getElementById('suOwner').value.trim(),mobile=document.getElementById('suMobile').value.trim(),email=document.getElementById('suEmail').value.trim().toLowerCase(),category=document.getElementById('suCategory').value.trim(),gst=document.getElementById('suGst').value.trim(),password=document.getElementById('suPassword').value;const r=await api('/api/auth',{method:'POST',body:JSON.stringify({action:'signup',business,owner,mobile,email,category,gst,password})});currentUser=r.user;serverData={items:[],bills:[],settings:{name:business,category,mobile,gst,address:''}};state=serverData;renderAuth('plans')}catch(err){renderAuth('signup',err.message)}}
async function login(e){e.preventDefault();try{const id=document.getElementById('loginId').value.trim().toLowerCase(),password=document.getElementById('loginPassword').value;const r=await api('/api/auth',{method:'POST',body:JSON.stringify({action:'login',id,password})});currentUser=r.user;if(currentUser.status==='pending'||currentUser.status==='expired'){renderAuth('plans',currentUser.status==='expired'?'Your subscription has expired. Renew to continue billing.':'Your account is created. Choose a subscription to activate billing.');return}const d=await api('/api/data');serverData=d.data;state=serverData;showApp()}catch(err){renderAuth('login',err.message)}}
async function startSubscription(plan){if(!currentUser)return;try{const r=await api('/api/auth',{method:'POST',body:JSON.stringify({action:'pending',plan})});currentUser=r.user;renderAuth('payment')}catch(err){alert(err.message)}}
async function verifyRazorpayPayment(response){try{const res=await fetch('/api/verify-payment',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(response)});const data=await res.json();if(!res.ok||!data.verified)throw new Error(data.error||'Payment verification failed.');currentUser={...currentUser,...data.user,subscriptionEnds:data.user.subscription_ends,pendingPlan:data.user.pending_plan,pendingAmount:Number(data.user.pending_amount||0),lastPaymentId:data.user.last_payment_id};localStorage.removeItem(SESSION_KEY);serverData=(await api('/api/data')).data;state=serverData;showApp()}catch(error){alert(error.message||'Payment verification failed. Your account was not activated.')}}
async function logout(){try{await api('/api/auth',{method:'POST',body:JSON.stringify({action:'logout'})})}catch{}currentUser=null;state=null;serverData={items:[],bills:[],settings:{name:'Your Business',category:'General Business',mobile:'',gst:'',address:''}};document.getElementById('app').classList.add('hidden');document.getElementById('authScreen').classList.remove('hidden');renderAuth('login')}
async function checkSession(){try{await fetchMe();if(currentUser.status!=='active'||!currentUser.subscriptionEnds||new Date(currentUser.subscriptionEnds)<=new Date()){if(currentUser.status==='active'){currentUser.status='expired'}renderAuth('plans','Your subscription has expired. Renew to restore billing access.');return}showApp()}catch{renderAuth('login')}}
checkSession();
