// NR BizPro - Furniture / Home Furniture product module
(function(){
  'use strict';
  const CAT=/furniture/i;
  const brands=['Godrej Interio','Durian','Nilkamal','Wakefit','Pepperfry','IKEA','Zuari','Royaloak','HomeTown','Urban Ladder','WoodenStreet','Other Brand'];
  const categories=['Sofa','Sofa Set','Bed','Cot','Mattress','Wardrobe','Table','Dining Table','Chair','Dining Chair','Office Furniture','TV Unit','Bookshelf','Study Table','Cupboard','Other'];
  const materials=['Solid Wood','Engineered Wood','MDF','Plywood','Steel','Plastic','Glass','Fabric','Leatherette','Other'];
  function isFurniture(){const el=document.getElementById('businessCategory');return CAT.test(String(el?.value||''))}
  function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function listBrands(){if(typeof state==='undefined'||!state)return brands.slice();state.furnitureBrands=Array.isArray(state.furnitureBrands)?state.furnitureBrands:[];return [...new Set(brands.concat(state.furnitureBrands).map(x=>String(x).trim()).filter(Boolean))]}
  function panel(){let p=document.getElementById('furnitureModule');if(p)return p;const shell=document.querySelector('#app main.shell');if(!shell)return null;p=document.createElement('section');p.id='furnitureModule';p.className='panel';p.style.cssText='display:none;margin:0 0 18px';const nav=shell.querySelector('.tabs');nav?shell.insertBefore(p,nav):shell.appendChild(p);return p}
  function render(){const p=panel();if(!p)return;p.style.display=isFurniture()?'block':'none';if(!isFurniture())return;const bs=listBrands();p.innerHTML='<div class="panel-head"><div><p class="eyebrow">FURNITURE INVENTORY</p><h2 style="margin:0">Furniture Product Management</h2><p class="muted">Manage furniture by category, material, size, design, warranty, price and stock.</p></div></div><div class="card" style="padding:16px;margin-top:14px"><div style="display:flex;gap:10px;flex-wrap:wrap;align-items:end"><label style="flex:1;min-width:220px">Add Brand<input id="furBrandNew" placeholder="Enter brand / manufacturer"></label><button class="secondary" type="button" id="furAddBrand">+ Add Brand</button></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:12px">'+bs.map(b=>'<span style="display:inline-flex;padding:7px 10px;border:1px solid #dbe5f2;border-radius:999px;background:#f8fafc">'+esc(b)+'</span>').join('')+'</div></div><div class="card" style="padding:16px;margin-top:14px"><div class="form-grid"><label>Product / Furniture Name<input id="furName" placeholder="3 Door Wardrobe"></label><label>Brand / Manufacturer<select id="furBrand">'+bs.map(b=>'<option>'+esc(b)+'</option>').join('')+'</select></label><label>Category<select id="furCategory">'+categories.map(x=>'<option>'+esc(x)+'</option>').join('')+'</select></label><label>Material<select id="furMaterial">'+materials.map(x=>'<option>'+esc(x)+'</option>').join('')+'</select></label><label>Size / Dimensions<input id="furSize" placeholder="6 x 6.5 ft / 72 x 30 x 18 in"></label><label>Color / Finish<input id="furColor" placeholder="Teak / Walnut / Black"></label><label>Design / Model<input id="furDesign" placeholder="Model / Design No."></label><label>Warranty<input id="furWarranty" placeholder="1 Year / 5 Years"></label><label>MRP<input id="furMrp" type="number" min="0" step="0.01" value="0"></label><label>Purchase Price<input id="furCost" type="number" min="0" step="0.01" value="0"></label><label>Selling Price<input id="furSell" type="number" min="0" step="0.01" value="0"></label><label>GST %<input id="furGst" type="number" min="0" step="0.01" value="0"></label><label>Opening Stock<input id="furStock" type="number" min="0" step="1" value="0"></label></div><div style="display:flex;justify-content:flex-end;margin-top:12px"><button class="primary" type="button" id="furAdd">+ Add Furniture</button></div></div><div class="card" style="padding:16px;margin-top:14px"><div class="table-wrap"><table><thead><tr><th>Product</th><th>Brand</th><th>Category</th><th>Material</th><th>Size</th><th>Color</th><th>Model</th><th>Warranty</th><th>Selling</th><th>Stock</th></tr></thead><tbody id="furnitureTable"></tbody></table></div></div>';bind();table()}
  function bind(){const b=document.getElementById('furAddBrand');if(b)b.onclick=function(){const i=document.getElementById('furBrandNew'),v=String(i?.value||'').trim();if(!v)return;if(typeof state!=='undefined'){state.furnitureBrands=Array.isArray(state.furnitureBrands)?state.furnitureBrands:[];if(!state.furnitureBrands.includes(v))state.furnitureBrands.push(v);if(typeof save==='function')save()}render()};const a=document.getElementById('furAdd');if(a)a.onclick=function(){if(typeof state==='undefined'||!Array.isArray(state.items))return;const g=id=>document.getElementById(id);const name=String(g('furName')?.value||'').trim();if(!name){alert('Please enter Product / Furniture Name');g('furName')?.focus();return}const item={id:(crypto.randomUUID?crypto.randomUUID():String(Date.now())),name,brand:g('furBrand')?.value||'',furnitureCategory:g('furCategory')?.value||'',furnitureMaterial:g('furMaterial')?.value||'',furnitureSize:g('furSize')?.value||'',furnitureColor:g('furColor')?.value||'',furnitureDesign:g('furDesign')?.value||'',furnitureWarranty:g('furWarranty')?.value||'',mrp:Number(g('furMrp')?.value||0),cost:Number(g('furCost')?.value||0),sell:Number(g('furSell')?.value||0),gst:Number(g('furGst')?.value||0),stock:Number(g('furStock')?.value||0),businessType:'furniture',type:'Product',barcode:'',margin:0,marginType:'fixed'};state.items.push(item);if(typeof save==='function')save();table();if(typeof updateStats==='function')updateStats();['furName','furSize','furColor','furDesign','furWarranty','furMrp','furCost','furSell','furGst','furStock'].forEach(id=>{const e=g(id);if(e)e.value=(['furMrp','furCost','furSell','furGst','furStock'].includes(id)?'0':'')});};}
  function table(){const tb=document.getElementById('furnitureTable');if(!tb)return;const arr=(typeof state!=='undefined'&&Array.isArray(state.items)?state.items:[]).filter(i=>i.businessType==='furniture');tb.innerHTML=arr.length?arr.map(i=>'<tr><td><b>'+esc(i.name)+'</b></td><td>'+esc(i.brand||'—')+'</td><td>'+esc(i.furnitureCategory||'—')+'</td><td>'+esc(i.furnitureMaterial||'—')+'</td><td>'+esc(i.furnitureSize||'—')+'</td><td>'+esc(i.furnitureColor||'—')+'</td><td>'+esc(i.furnitureDesign||'—')+'</td><td>'+esc(i.furnitureWarranty||'—')+'</td><td>₹'+Number(i.sell||0).toFixed(2)+'</td><td>'+Number(i.stock||0)+'</td></tr>').join(''):'<tr><td colspan="10" class="empty">No furniture products added yet.</td></tr>'}
  function start(){const app=document.getElementById('app');if(!app)return;const obs=new MutationObserver(()=>{const c=document.getElementById('businessCategory')?.value||'';if(c!==start.last){start.last=c;render()}});obs.observe(app,{attributes:true,subtree:true,attributeFilter:['class','value']});document.addEventListener('change',e=>{if(e.target?.id==='businessCategory')render()});render()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();