(() => {
  const USERS_KEY='nr-bizpro-users-v1';
  const SESSION_KEY='nr-bizpro-session-v1';
  const REG_FEE=2500;
  const OWNER_EMAIL='abhishek.maskuri@gmail.com';
  const OWNER_MOBILE='9000264439';
  const PLANS={threeYear:{label:'3 Years',years:3,fee:3500},lifetime:{label:'Lifetime',years:99,fee:6000}};
  const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
  const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
  const isOwner=u=>!!u&&((u.email||'').toLowerCase()===OWNER_EMAIL||(u.mobile||'').replace(/\D/g,'')===OWNER_MOBILE);
  async function apiJson(url,options={}){const r=await fetch(url,options);const text=await r.text();let d={};try{d=JSON.parse(text)}catch{throw Error(r.ok?'Unexpected server response.':'Server is not configured yet. Please try again after backend setup.')}if(!r.ok)throw Error(d.error||'Request failed.');return d}
  let pendingUser=null;
  window.renderAuth=function(mode='login',message=''){
    const el=document.getElementById('authContent'); if(!el)return;
    if(mode==='login')el.innerHTML=`<div class="auth-title"><h1>Welcome to NR BizPro</h1><p>Universal billing & business management.</p></div>${message?`<div class="notice">${esc(message)}</div>`:''}<form onsubmit="login(event)"><label>Email or Mobile<input id="loginId" required autocomplete="username"></label><label>Password<input id="loginPassword" required type="password" autocomplete="current-password"></label><button class="primary auth-btn">Login</button></form><div class="auth-switch"><button class="secondary auth-btn" onclick="renderAuth('signup')">Create Business Account</button></div>`;
    if(mode==='signup')el.innerHTML=`<div class="auth-title"><h1>Create your business account</h1><p>Complete registration details before selecting a membership.</p></div><form onsubmit="signup(event)"><div class="auth-grid"><label>Business Name<input id="suBusiness" required></label><label>Owner Name<input id="suOwner" required></label><label>Mobile<input id="suMobile" required inputmode="tel"></label><label>Email<input id="suEmail" required type="email"></label><label>Business Category<input id="suCategory" required placeholder="Garage / Retail / Service..."></label><label>GSTIN <span>(optional)</span><input id="suGst"></label></div><label>Password<input id="suPassword" required minlength="6" type="password"></label><button class="primary auth-btn">Continue to Membership</button></form><div class="auth-switch"><button class="secondary auth-btn" onclick="renderAuth('login')">Back to Login</button></div>`;
    if(mode==='plans')el.innerHTML=`<div class="auth-title"><h1>Activate Membership</h1><p>One-time registration + selected membership.</p></div><div class="registration-fee"><span>One-time Registration Fee</span><strong>${money(REG_FEE)}</strong></div><div class="plans">${Object.entries(PLANS).map(([key,p])=>`<button class="plan ${key==='lifetime'?'featured':''}" onclick="startSubscription('${key}')"><b>${p.label}</b><strong>${money(p.fee)}</strong><span>Membership fee</span><em>Total payable: ${money(REG_FEE+p.fee)}</em></button>`).join('')}</div>${message?`<div class="notice">${esc(message)}</div>`:''}`;
    if(mode==='payment'){const p=PLANS[pendingUser?.pendingPlan];if(!p)return renderAuth('plans');el.innerHTML=`<div class="auth-title"><h1>Complete Registration</h1><p>${p.label} Membership</p></div><div class="summary"><div><span>Registration Fee</span><b>${money(REG_FEE)}</b></div><div><span>${p.label} Plan</span><b>${money(p.fee)}</b></div><div class="total"><span>Total Payable</span><b>${money(REG_FEE+p.fee)}</b></div></div><button class="primary auth-btn" onclick="openRazorpayCheckout()">Pay ${money(REG_FEE+p.fee)} with Razorpay</button><button class="secondary auth-btn" onclick="renderAuth('plans')">Back to Plans</button>`;}
  };
  window.signup=async function(e){e.preventDefault();const body={action:'signup',business:suBusiness.value.trim(),owner:suOwner.value.trim(),mobile:suMobile.value.trim(),email:suEmail.value.trim().toLowerCase(),category:suCategory.value.trim(),gst:suGst.value.trim(),password:suPassword.value};if(!body.business||!body.owner||!body.mobile||!body.email||!body.category||body.password.length<6)return alert('Please complete all required registration details.');try{const d=await apiJson('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});pendingUser=d.user;if(isOwner(pendingUser)){pendingUser.status='active';pendingUser.plan='lifetime';pendingUser.subscriptionEnds='2099-12-31T23:59:59.000Z';pendingUser.pendingPlan=null;pendingUser.pendingAmount=0;localStorage.setItem(USERS_KEY,JSON.stringify([pendingUser]));localStorage.setItem(SESSION_KEY,pendingUser.id);location.reload();return}localStorage.setItem(USERS_KEY,JSON.stringify([d.user]));renderAuth('plans')}catch(err){alert(err.message)}};
  window.startSubscription=async function(plan){if(!pendingUser||!PLANS[plan])return alert('Complete registration first.');try{const d=await apiJson('/api/auth?action=pending',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'pending',plan})});pendingUser=d.user;pendingUser.pendingPlan=plan;pendingUser.pendingAmount=REG_FEE+PLANS[plan].fee;localStorage.setItem(USERS_KEY,JSON.stringify([pendingUser]));renderAuth('payment')}catch(err){alert(err.message)}};
  window.openRazorpayCheckout=async function(){if(!pendingUser?.pendingPlan)return alert('Select a membership plan first.');if(typeof Razorpay==='undefined')return alert('Razorpay checkout did not load. Please refresh.');try{const p=PLANS[pendingUser.pendingPlan],o=await apiJson('/api/create-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan:pendingUser.pendingPlan,businessName:pendingUser.business,email:pendingUser.email,mobile:pendingUser.mobile,registrationFee:true})});new Razorpay({key:o.keyId,amount:o.amount,currency:o.currency,name:'NR BizPro',description:`Registration + ${p.label} Membership`,order_id:o.orderId,prefill:{name:pendingUser.owner,email:pendingUser.email,contact:pendingUser.mobile},notes:{business:pendingUser.business,plan:pendingUser.pendingPlan},handler:window.verifyRazorpayPayment}).open()}catch(err){alert(err.message)}};
  window.verifyRazorpayPayment=async function(response){try{const d=await apiJson('/api/verify-payment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(response)});if(!d.verified)throw Error(d.error||'Payment verification failed.');localStorage.setItem(USERS_KEY,JSON.stringify([d.user||pendingUser]));localStorage.setItem(SESSION_KEY,(d.user||pendingUser).id);pendingUser=null;alert('Payment verified. Membership activated successfully.');location.reload()}catch(err){alert(err.message)}};
  window.login=async function(e){e.preventDefault();const id=loginId.value.trim().toLowerCase(),password=loginPassword.value;try{const d=await apiJson('/api/auth?action=login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'login',id,password})});if(isOwner(d.user)){d.user.status='active';d.user.plan='lifetime';d.user.subscriptionEnds='2099-12-31T23:59:59.000Z';d.user.pendingPlan=null;d.user.pendingAmount=0;localStorage.setItem(USERS_KEY,JSON.stringify([d.user]));localStorage.setItem(SESSION_KEY,d.user.id);location.reload();return}if(d.paymentRequired&&d.user){pendingUser=d.user;localStorage.setItem(USERS_KEY,JSON.stringify([d.user]));return renderAuth('plans','Membership payment is required before using NR BizPro.')}localStorage.setItem(USERS_KEY,JSON.stringify([d.user]));localStorage.setItem(SESSION_KEY,d.user.id);location.reload()}catch(err){alert(err.message)}};
  renderAuth('login');
})();