(() => {
  const USERS_KEY='nr-bizpro-users-v1';
  const SESSION_KEY='nr-bizpro-session-v1';
  const REG_FEE=3500;
  const PLANS={year3:{label:'3 Years',years:3,fee:3500},lifetime:{label:'Lifetime',years:0,fee:6000}};
  const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
  const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
  async function apiJson(url,options={}){const r=await fetch(url,{credentials:'same-origin',...options});const text=await r.text();let d={};try{d=JSON.parse(text)}catch{throw Error(r.ok?'Unexpected server response.':'Server is not configured yet. Please try again after backend setup.')}if(!r.ok)throw Error(d.error||'Request failed.');return d}
  let pendingUser=null;
  const portalCss=`<style>
  .nr-portal{background:linear-gradient(135deg,#eef5ff 0%,#fff 48%,#f1f6ff 100%);border-radius:18px;padding:4px;}
  .nr-portal .portal-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:18px;gap:12px}
  .nr-portal .portal-brand{display:flex;align-items:center;gap:10px;font-weight:800;color:#10233f}.nr-portal .portal-mark{width:42px;height:42px;border-radius:11px;background:#10233f;color:#fff;display:grid;place-items:center;font-weight:900}.nr-portal .portal-brand small{display:block;color:#607089;font-size:11px;font-weight:600;margin-top:2px}
  .nr-portal .home-btn{border:1px solid #cbd7e8;background:#fff;color:#1559d6;border-radius:9px;padding:8px 13px;font-weight:700;cursor:pointer}
  .nr-portal .portal-form{background:#fff;border:1px solid #dce6f2;border-radius:16px;padding:22px;box-shadow:0 14px 35px rgba(25,64,120,.08)}
  .nr-portal .portal-form h1{margin:0 0 5px;color:#10233f;font-size:26px}.nr-portal .portal-form p{color:#607089;margin:0 0 18px}
  .nr-portal .portal-form label{display:block;margin:12px 0 0;color:#10233f;font-weight:700;font-size:14px}.nr-portal .portal-form input,.nr-portal .portal-form select{width:100%;box-sizing:border-box;margin-top:7px;border:1px solid #cbd7e8;border-radius:9px;padding:11px 12px;background:#fff;color:#10233f;font-size:14px}.nr-portal .portal-form input:focus,.nr-portal .portal-form select:focus{outline:2px solid #dbe8ff;border-color:#1559d6}
  .nr-portal .portal-primary{width:100%;margin-top:18px;background:#1559d6;color:#fff;border:0;border-radius:9px;padding:12px;font-weight:800;cursor:pointer}.nr-portal .portal-secondary{width:100%;margin-top:10px;background:#fff;color:#1559d6;border:1px solid #cbd7e8;border-radius:9px;padding:11px;font-weight:700;cursor:pointer}.nr-portal .portal-switch{text-align:center;margin-top:14px;color:#607089;font-size:13px}.nr-portal .portal-link{border:0;background:none;color:#1559d6;font-weight:800;cursor:pointer}.nr-portal .portal-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.nr-portal .notice{margin-top:12px}.nr-portal .plans{display:grid;grid-template-columns:1fr 1fr;gap:12px}.nr-portal .plan{position:relative;text-align:left;border:1px solid #cbd7e8;background:#fff;border-radius:14px;padding:17px;cursor:pointer;min-height:130px}.nr-portal .plan.featured{border-color:#10233f;box-shadow:0 8px 22px rgba(25,64,120,.10)}.nr-portal .plan b,.nr-portal .plan strong,.nr-portal .plan span{display:block}.nr-portal .plan strong{font-size:25px;margin:7px 0}.nr-portal .plan span{font-size:12px;color:#607089}.nr-portal .plan em{position:absolute;right:10px;top:10px;background:#10233f;color:#fff;border-radius:999px;padding:4px 8px;font-size:10px;font-style:normal;font-weight:700}.nr-portal .summary{border:1px solid #dce6f2;border-radius:12px;padding:12px;background:#f8fbff}.nr-portal .summary>div{display:flex;justify-content:space-between;padding:6px 0}.nr-portal .summary .total{border-top:1px solid #dce6f2;margin-top:5px;padding-top:10px;font-size:17px}.nr-portal .upi-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.nr-portal .upi-actions .portal-secondary{width:auto;margin:0}.nr-portal .wide{grid-column:1/-1}@media(max-width:650px){.nr-portal .portal-grid,.nr-portal .plans{grid-template-columns:1fr}.nr-portal .portal-head{align-items:flex-start}}
  </style>`;
  function wrap(content){const el=document.getElementById('authContent');if(!el)return;el.innerHTML=portalCss+`<div class="nr-portal">${content}</div>`}
  function head(){return `<div class="portal-head"><div class="portal-brand"><span class="portal-mark">NR</span><div><strong>NR BizPro</strong><small>One Platform. Every Business.</small></div></div><button class="home-btn" type="button" onclick="document.getElementById('authBack').click()">← Home</button></div>`}
  window.renderAuth=function(mode='login',message=''){
    if(mode==='login')wrap(`${head()}<div class="portal-form"><h1>Login</h1><p>Access your NR BizPro business workspace.</p>${message?`<div class="notice">${esc(message)}</div>`:''}<form onsubmit="login(event)"><label>Email or Mobile<input id="loginId" required autocomplete="username" placeholder="Enter email or mobile number"></label><label>Password<input id="loginPassword" required type="password" autocomplete="current-password" placeholder="Enter password"></label><button class="portal-primary" type="submit">Login</button></form><div class="portal-switch">New business? <button class="portal-link" type="button" onclick="renderAuth('signup')">Create Business Account</button></div><div class="portal-switch"><a class="portal-link" href="admin.html" style="text-decoration:none">Admin Login</a></div></div>`);
    if(mode==='signup')wrap(`${head()}<div class="portal-form"><h1>Create Business Account</h1><p>Register your business and select a membership plan.</p><form onsubmit="signup(event)"><div class="portal-grid"><label>Business Name<input id="suBusiness" required></label><label>Owner Name<input id="suOwner" required></label><label>Mobile<input id="suMobile" required inputmode="tel"></label><label>Email<input id="suEmail" required type="email"></label><label>Business Category<select id="suCategory" required><option value="">Select Business Category</option><option>Grocery / General Store</option><option>Footwear / Chappal Shop</option><option>Fertilizer / Agriculture</option><option>Garage / Service Center</option><option>Spare Parts</option><option>EV Two-Wheeler Showroom</option><option>Retail / Supermarket</option><option>Restaurant / Bakery</option><option>Hardware / Building Materials</option><option>Medical / Pharmacy</option><option>Electronics / Mobile</option><option>Clothing / Fashion</option><option>Furniture</option><option>Jewellery</option><option>Stationery / Book Store</option><option>Dairy / Milk Products</option><option>Salon / Beauty Parlour</option><option>Printing / Xerox / Online Services</option><option>Wholesale / Distributor</option><option>Professional Services</option><option>Construction / Building Materials</option><option>Other Business</option></select></label><label>GSTIN <span>(optional)</span><input id="suGst"></label></div><label>Password<input id="suPassword" required minlength="6" type="password" placeholder="Minimum 6 characters"></label><button class="portal-primary" type="submit">Continue to Membership</button></form><div class="portal-switch"><button class="portal-link" type="button" onclick="renderAuth('login')">Back to Login</button></div></div>`);
    if(mode==='plans')wrap(`${head()}<div class="portal-form"><h1>Activate Membership</h1><p>Registration fee is mandatory. Select one membership plan.</p><div class="registration-fee" style="display:flex;justify-content:space-between;padding:12px 0"><span>One-time Registration Fee</span><strong>${money(REG_FEE)}</strong></div><div class="plans">${Object.entries(PLANS).map(([key,p])=>`<button type="button" class="plan ${key==='year3'?'featured':''}" onclick="startSubscription('${key}')"><b>${p.label}</b><strong>${money(p.fee)}</strong><span>Membership fee • ${p.years?`${p.years} years`:'Lifetime access'}</span><em>Total payable: ${money(REG_FEE+p.fee)}</em></button>`).join('')}</div>${message?`<div class="notice">${esc(message)}</div>`:''}</div>`);
    if(mode==='payment')renderDirectPayment();
  };
  window.signup=async function(e){e.preventDefault();const body={action:'signup',business:document.getElementById('suBusiness').value.trim(),owner:document.getElementById('suOwner').value.trim(),mobile:document.getElementById('suMobile').value.trim(),email:document.getElementById('suEmail').value.trim().toLowerCase(),category:document.getElementById('suCategory').value.trim(),gst:document.getElementById('suGst').value.trim(),password:document.getElementById('suPassword').value};if(!body.business||!body.owner||!body.mobile||!body.email||!body.category||body.password.length<6)return alert('Please complete all required registration details.');try{const d=await apiJson('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});pendingUser=d.user;localStorage.setItem(USERS_KEY,JSON.stringify([d.user]));renderAuth('plans')}catch(err){alert(err.message)}};
  window.startSubscription=async function(plan){if(!pendingUser||!PLANS[plan])return alert('Complete registration first.');try{const d=await apiJson('/api/auth?action=pending',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'pending',plan})});pendingUser=d.user;pendingUser.pendingPlan=plan;pendingUser.pendingAmount=REG_FEE+PLANS[plan].fee;localStorage.setItem(USERS_KEY,JSON.stringify([pendingUser]));renderAuth('payment')}catch(err){alert(err.message)}};
  async function renderDirectPayment(){const p=PLANS[pendingUser?.pendingPlan];if(!p)return renderAuth('plans');wrap(`${head()}<div class="portal-form"><h1>Direct UPI Payment</h1><p>${p.label} Membership</p><div class="summary"><div><span>Registration Fee</span><b>${money(REG_FEE)}</b></div><div><span>${p.label} Plan</span><b>${money(p.fee)}</b></div><div class="total"><span>Total Payable</span><b>${money(REG_FEE+p.fee)}</b></div></div><div id="upiBox" class="notice">Loading UPI payment details...</div><label style="display:block;margin-top:12px">UTR / Transaction ID<input id="directUtr" required maxlength="40" placeholder="Enter UTR after payment"></label><button id="upiSubmit" class="portal-primary" disabled>Submit Payment for Verification</button><button class="portal-secondary" onclick="renderAuth('plans')">Back to Plans</button><div id="directStatus" style="margin-top:12px"></div></div>`);try{const d=await apiJson('/api/direct-payment?action=config');const box=document.getElementById('upiBox');if(!d.configured){box.innerHTML='<b>UPI payment is not configured yet.</b><br>Please contact NR BizPro support.';return}const upi=d.upiId;const intent=`upi://pay?pa=${encodeURIComponent(upi)}&pn=${encodeURIComponent(d.upiName||'NR BizPro')}&am=${encodeURIComponent(REG_FEE+p.fee)}&cu=INR&tn=${encodeURIComponent(`NR BizPro ${p.label} Membership`)}`;box.innerHTML=`<b>Pay ₹${REG_FEE+p.fee} via UPI</b><br><span>UPI ID: <strong>${esc(upi)}</strong></span><div class="upi-actions"><button id="copyUpiBtn" type="button" class="portal-secondary">Copy UPI ID</button><a class="portal-secondary" href="${intent}" style="text-decoration:none;display:inline-flex;align-items:center;justify-content:center">Open UPI App</a></div><small style="display:block;margin-top:8px">After payment, enter the UTR / transaction ID below.</small>`;const copyBtn=document.getElementById('copyUpiBtn');copyBtn.onclick=async()=>{try{await navigator.clipboard.writeText(upi);copyBtn.textContent='UPI ID Copied ✓';setTimeout(()=>{if(copyBtn)copyBtn.textContent='Copy UPI ID'},1800)}catch{try{const ta=document.createElement('textarea');ta.value=upi;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();copyBtn.textContent='UPI ID Copied ✓';setTimeout(()=>{if(copyBtn)copyBtn.textContent='Copy UPI ID'},1800)}catch{alert('Please copy the UPI ID manually: '+upi)}}};document.getElementById('upiSubmit').disabled=false}catch(err){document.getElementById('upiBox').innerHTML=`<b>Unable to load UPI details.</b><br>${esc(err.message)}`;return}document.getElementById('upiSubmit').onclick=submitDirectPayment}
  async function submitDirectPayment(){const btn=document.getElementById('upiSubmit'),utr=document.getElementById('directUtr')?.value.trim();if(!/^[A-Za-z0-9-]{8,40}$/.test(utr||''))return alert('Enter a valid UTR / transaction reference (8-40 characters).');btn.disabled=true;btn.textContent='Submitting...';try{await apiJson('/api/direct-payment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'submit',plan:pendingUser.pendingPlan,utr})});document.getElementById('directStatus').innerHTML='<div class="notice">Payment details submitted successfully. Your account will be activated after admin verification.</div>';btn.textContent='Submitted ✓'}catch(err){btn.disabled=false;btn.textContent='Submit Payment for Verification';alert(err.message)}}
  window.login=async function(e){e.preventDefault();const id=document.getElementById('loginId').value.trim().toLowerCase(),password=document.getElementById('loginPassword').value;try{const d=await apiJson('/api/auth?action=login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'login',id,password})});if(d.paymentRequired&&d.user){pendingUser=d.user;localStorage.setItem(USERS_KEY,JSON.stringify([d.user]));return renderAuth('plans','Membership payment is required before using NR BizPro.')}localStorage.setItem(USERS_KEY,JSON.stringify([d.user]));localStorage.setItem(SESSION_KEY,d.user.id);location.reload()}catch(err){alert(err.message)}};
  function ensureAuthVisible(){const screen=document.getElementById('authScreen'),el=document.getElementById('authContent');if(screen&&el&&!screen.classList.contains('hidden')&&!el.innerHTML.trim())window.renderAuth('login')}
  ensureAuthVisible();setTimeout(ensureAuthVisible,50);setTimeout(ensureAuthVisible,300);
})();