// NR BizPro — Printing / Xerox / Online Services module
(function(){
 const category=()=>String((typeof currentUser!=='undefined'&&currentUser?.category)||(typeof state!=='undefined'&&state?.settings?.category)||'');
 const isPrinting=()=>/printing|xerox|online services/i.test(category());
 const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
 const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n)||0);
 function render(){if(!isPrinting())return;let p=document.getElementById('printingModule');if(!p){const shell=document.querySelector('#app main.shell');if(!shell)return;p=document.createElement('section');p.id='printingModule';p.className='panel';p.style.margin='0 0 18px';const nav=shell.querySelector('.tabs');nav?shell.insertBefore(p,nav):shell.appendChild(p)}
 p.innerHTML=`<div class="panel-head"><div><p class="eyebrow">PRINTING & ONLINE SERVICES</p><h2>Printing / Xerox / Online Services</h2><p class="muted">Manage print jobs, Xerox, scanning, lamination, binding, photo services and online application services.</p></div></div><div class="quick-grid"><button type="button" class="industry-feature" id="printJobFocus"><b>🖨️ Print / Xerox</b><span>B&W, colour, copies and paper size</span></button><button type="button" class="industry-feature" id="printFinishFocus"><b>📚 Binding / Lamination</b><span>Binding, lamination and finishing jobs</span></button><button type="button" class="industry-feature" id="printPhotoFocus"><b>📷 Photo / Scan</b><span>Passport photos, scanning and document work</span></button><button type="button" class="industry-feature" id="printOnlineFocus"><b>🌐 Online Services</b><span>Applications, forms, tickets and digital services</span></button></div><div class="card" style="margin-top:16px;padding:16px"><div class="panel-head"><div><p class="eyebrow">JOB ENTRY</p><h3 style="margin:0">Add Service / Job</h3></div></div><div class="form-grid"><label>Service Type<select id="prType"><option>Xerox - B&W</option><option>Xerox - Colour</option><option>Printing - B&W</option><option>Printing - Colour</option><option>Scanning</option><option>Passport Photo</option><option>Photo Print</option><option>Lamination</option><option>Spiral Binding</option><option>Hard Binding</option><option>Online Application</option><option>Ticket Booking</option><option>Other Online Service</option><option>Other</option></select></label><label>Job / Service Name<input id="prName" placeholder="A4 Colour Print / Passport Photo"></label><label>Paper Size<select id="prPaper"><option>Not Applicable</option><option>A4</option><option>A3</option><option>A5</option><option>Legal</option><option>Letter</option><option>Photo 4x6</option><option>Photo 6x8</option></select></label><label>Colour Mode<select id="prMode"><option>Not Applicable</option><option>B&W</option><option>Colour</option></select></label><label>Unit<select id="prUnit"><option>Page</option><option>Copy</option><option>Photo</option><option>Job</option><option>Document</option><option>Set</option></select></label><label>Rate<input id="prRate" type="number" min="0" step="0.01" value="0"></label><label>GST %<input id="prGst" type="number" min="0" step="0.01" value="0"></label><label>Opening Stock<input id="prStock" type="number" min="0" step="1" value="0"></label></div><div style="display:flex;justify-content:flex-end;margin-top:12px"><button class="primary" type="button" id="addPrintService">+ Add Service</button></div></div><div class="card" style="margin-top:16px;padding:16px"><div class="panel-head"><div><h3 style="margin:0">Services / Rates</h3></div></div><div class="table-wrap"><table><thead><tr><th>Service</th><th>Type</th><th>Paper</th><th>Mode</th><th>Unit</th><th>Rate</th></tr></thead><tbody id="printingTable"></tbody></table></div></div>`;
 const refresh=()=>{const tb=document.getElementById('printingTable');if(!tb)return;const list=(typeof state!=='undefined'&&state?.items||[]).filter(i=>i.businessType==='printing');tb.innerHTML=list.length?list.map(i=>`<tr><td><b>${esc(i.name)}</b></td><td>${esc(i.printType||'—')}</td><td>${esc(i.paperSize||'—')}</td><td>${esc(i.colorMode||'—')}</td><td>${esc(i.unit||'—')}</td><td>${money(i.sell)}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">No printing services added yet.</td></tr>'};
 document.getElementById('addPrintService').onclick=()=>{const name=prName.value.trim();if(!name)return alert('Enter job/service name');state.items=state.items||[];state.items.push({id:crypto.randomUUID(),name,type:'Service',printType:prType.value,paperSize:prPaper.value,colorMode:prMode.value,unit:prUnit.value,cost:0,sell:+prRate.value||0,gst:+prGst.value||0,stock:+prStock.value||0,businessType:'printing'});save();refresh();renderItems();updateStats()};
 document.getElementById('printJobFocus').onclick=()=>{prName.focus()};document.getElementById('printFinishFocus').onclick=()=>{prType.value='Lamination';prName.focus()};document.getElementById('printPhotoFocus').onclick=()=>{prType.value='Scanning';prName.focus()};document.getElementById('printOnlineFocus').onclick=()=>{prType.value='Online Application';prName.focus()};refresh();
 }
 window.addEventListener('load',()=>setTimeout(render,300));window.addEventListener('loginSuccess',()=>setTimeout(render,100));window.addEventListener('categoryChanged',()=>setTimeout(render,50));
})();