// NR BizPro — Salon / Beauty Parlour module
(function(){
 const category=()=>String((typeof currentUser!=='undefined'&&currentUser?.category)||(typeof state!=='undefined'&&state?.settings?.category)||'');
 const isSalon=()=>/salon|beauty parlour|beauty salon/i.test(category());
 const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
 const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n)||0);
 function render(){if(!isSalon())return;let p=document.getElementById('salonModule');if(!p){const shell=document.querySelector('#app main.shell');if(!shell)return;p=document.createElement('section');p.id='salonModule';p.className='panel';p.style.margin='0 0 18px';const nav=shell.querySelector('.tabs');nav?shell.insertBefore(p,nav):shell.appendChild(p)}
 p.innerHTML=`<div class="panel-head"><div><p class="eyebrow">SALON & BEAUTY</p><h2>Salon / Beauty Parlour Management</h2><p class="muted">Manage services, products, staff, appointments and service billing from one place.</p></div></div><div class="quick-grid"><button type="button" class="industry-feature" id="salonServiceAction"><b>💇 Services</b><span>Haircut, styling, facial, bridal & other services</span></button><button type="button" class="industry-feature" id="salonProductAction"><b>🧴 Products</b><span>Shampoo, cosmetics, skincare and salon retail items</span></button><button type="button" class="industry-feature" id="salonStaffAction"><b>👩‍💼 Staff</b><span>Beauticians, stylists and service staff</span></button><button type="button" class="industry-feature" id="salonAppointmentAction"><b>📅 Appointments</b><span>Customer booking and follow-up details</span></button></div><div class="card" style="margin-top:16px;padding:16px"><div class="panel-head"><div><p class="eyebrow">SERVICE / PRODUCT ENTRY</p><h3 style="margin:0">Add Salon Service or Product</h3></div></div><div class="form-grid"><label>Type<select id="salonItemType"><option>Service</option><option>Product</option></select></label><label>Name<input id="salonName" placeholder="Haircut / Facial / Shampoo"></label><label>Category<select id="salonCategory"><option>Hair</option><option>Skin Care</option><option>Makeup</option><option>Bridal</option><option>Manicure / Pedicure</option><option>Spa</option><option>Cosmetics</option><option>Hair Product</option><option>Other</option></select></label><label>Staff / Specialist<input id="salonStaff" placeholder="Staff name"></label><label>Duration (minutes)<input id="salonDuration" type="number" min="0" value="30"></label><label>Cost Price<input id="salonCost" type="number" min="0" step="0.01" value="0"></label><label>Selling / Service Price<input id="salonSell" type="number" min="0" step="0.01" value="0"></label><label>GST %<input id="salonGst" type="number" min="0" step="0.01" value="0"></label><label>Opening Stock (products)<input id="salonStock" type="number" min="0" step="1" value="0"></label></div><div style="display:flex;justify-content:flex-end;margin-top:12px"><button class="primary" type="button" id="addSalonItem">+ Add Service / Product</button></div></div><div class="card" style="margin-top:16px;padding:16px"><div class="panel-head"><div><h3 style="margin:0">Salon Items & Services</h3></div></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Category</th><th>Staff</th><th>Duration</th><th>Price</th><th>Stock</th></tr></thead><tbody id="salonTable"></tbody></table></div></div>`;
 const refresh=()=>{const tb=document.getElementById('salonTable');if(!tb)return;const list=(typeof state!=='undefined'&&state?.items||[]).filter(i=>i.businessType==='salon');tb.innerHTML=list.length?list.map(i=>`<tr><td><b>${esc(i.name)}</b></td><td>${esc(i.type)}</td><td>${esc(i.salonCategory||'—')}</td><td>${esc(i.staff||'—')}</td><td>${Number(i.duration||0)} min</td><td>${money(i.sell)}</td><td>${i.type==='Service'?'—':Number(i.stock||0)}</td></tr>`).join(''):'<tr><td colspan="7" class="empty">No salon services/products added yet.</td></tr>'};
 document.getElementById('addSalonItem').onclick=()=>{const name=salonName.value.trim();if(!name)return alert('Enter service/product name');state.items=state.items||[];state.items.push({id:crypto.randomUUID(),name,type:salonItemType.value,cost:+salonCost.value||0,sell:+salonSell.value||0,gst:+salonGst.value||0,stock:salonItemType.value==='Service'?0:(+salonStock.value||0),salonCategory:salonCategory.value,staff:salonStaff.value.trim(),duration:+salonDuration.value||0,businessType:'salon'});save();refresh();renderItems();updateStats()};
 document.getElementById('salonServiceAction').onclick=()=>document.getElementById('salonName')?.focus();document.getElementById('salonProductAction').onclick=()=>{salonItemType.value='Product';salonName.focus()};document.getElementById('salonStaffAction').onclick=()=>salonStaff.focus();document.getElementById('salonAppointmentAction').onclick=()=>alert('Appointment workflow is ready for integration with customer bookings.');refresh();
 }
 window.addEventListener('load',()=>setTimeout(render,300));window.addEventListener('loginSuccess',()=>setTimeout(render,100));window.addEventListener('categoryChanged',()=>setTimeout(render,50));
})();