const KEY='nr-bizpro-smart-print-v1',USERS_KEY='nr-bizpro-users-v1',SESSION_KEY='nr-bizpro-session-v1';
const TRIAL_LIMIT=3,PRICE=2000;
const CUSTOMER_TEST=new URLSearchParams(location.search).get('customerTest')==='1';
const CUSTOMER_TEST_KEY='nr-bizpro-smart-print-customer-test-v1',CUSTOMER_LIMIT=3;
let type='document',originalFile=null,originalDataUrl=null,sourcePages=[],processedPages=[],account=null,data=null,pdfLib=null;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function getAccount(){try{const id=localStorage.getItem(SESSION_KEY),users=JSON.parse(localStorage.getItem(USERS_KEY)||'[]');return users.find(u=>u.id===id)||null}catch{return null}}
function loadData(){if(CUSTOMER_TEST){try{const all=JSON.parse(localStorage.getItem(CUSTOMER_TEST_KEY)||'{}');data=all.test||{licensed:false,expires:null,trialCopies:0};return data}catch{return null}}account=getAccount();if(!account)return null;const all=JSON.parse(localStorage.getItem(KEY)||'{}');data=all[account.id]||{licensed:false,expires:null,trialCopies:0,staff:['Admin','Staff 1','Staff 2']};return data}
function save(){if(CUSTOMER_TEST){const all=JSON.parse(localStorage.getItem(CUSTOMER_TEST_KEY)||'{}');all.test=data;localStorage.setItem(CUSTOMER_TEST_KEY,JSON.stringify(all));return}if(!account)return;const all=JSON.parse(localStorage.getItem(KEY)||'{}');all[account.id]=data;localStorage.setItem(KEY,JSON.stringify(all))}
function isLicensed(){return !!(data?.licensed&&data.expires&&new Date(data.expires)>new Date())}
function init(){if(!loadData()){showGate('Please login to your NR BizPro account first.');return}if(CUSTOMER_TEST){showGate();return}if(isLicensed())showWorkspace();else showGate()}
function showGate(message=''){const remaining=CUSTOMER_TEST?Math.max(0,CUSTOMER_LIMIT-(data?.trialCopies||0)):Math.max(0,TRIAL_LIMIT-(data?.trialCopies||0));$('gate').innerHTML=`<div class="gate"><h1>NR BizPro Smart Print</h1><p>Clean WhatsApp documents and make them print-ready without rewriting their content.</p><div class="price">₹${PRICE.toLocaleString('en-IN')} + GST</div><p>2 Years • Unlimited Printing • Registered Customers Only</p><div class="warn">${message||`Free trial: ${remaining} successful test copies remaining. Passport-size photos are not included in trial.`}</div><p><b>Business:</b> ${esc(account?account.business||'Registered Business':'Customer Trial')}<br><b>Customer:</b> ${esc(account?account.mobile||account.email:'Demo Customer')}</p><select id="staffName"><option>Admin</option><option>Staff 1</option><option>Staff 2</option></select><button class="primary" onclick="enterPrint()">Continue to Smart Print</button></div>`}
function enterPrint(){if(CUSTOMER_TEST){showWorkspace();return}if(!account)return showGate('Please login to your NR BizPro account first.');showWorkspace()}
function showWorkspace(){$('gate').classList.add('hidden');$('workspace').classList.remove('hidden');updateLicense();selectType(type)}
function updateLicense(){const active=isLicensed();if(CUSTOMER_TEST){const left=Math.max(0,CUSTOMER_LIMIT-(data?.trialCopies||0));$('licenseText').textContent='Customer Test';$('licenseSub').textContent=`${left} test pages left`;$('trialNote').textContent='Customer Test: 3 successful document/ID test pages. After activation: unlimited printing for 2 years.';return}$('licenseText').textContent=active?'2-Year Unlimited':'Trial';$('licenseSub').textContent=active?`Valid until ${new Date(data.expires).toLocaleDateString('en-IN')}`:`${Math.max(0,TRIAL_LIMIT-(data.trialCopies||0))} trial copies left`;$('trialNote').textContent=active?'Licensed: unlimited Smart Print for 2 years. 1 Admin + 2 Staff logins.':'Trial: 3 successful test copies. Passport-size photos excluded.'}
function selectType(t){type=t;document.querySelectorAll('.types button').forEach(b=>b.classList.toggle('active',b.dataset.type===t));if(t==='passport'){$('copies').value=1;$('paper').value='A4';$('mode').value='Color';$('typeHint').textContent='📸 1-Click Passport Photo: upload one photo → automatically create 8 × 35×45 mm photos on one A4 sheet.'}else $('typeHint').textContent=t==='id'?'ID card print with clean crop and front/back-ready preview.':'A4/A5 document or PDF with safe cleanup and straightening.'}
async function ensurePdf(){if(pdfLib)return pdfLib;pdfLib=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.min.mjs');pdfLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.worker.min.mjs';return pdfLib}
function readAsDataURL(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
function loadImage(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=src})}
function estimateSkew(canvas){return 0}
function rotateCanvas(src,deg){if(!deg)return src;const r=deg*Math.PI/180,sw=src.width,sh=src.height,c=document.createElement('canvas');const cs=Math.abs(Math.cos(r)),sn=Math.abs(Math.sin(r));c.width=Math.ceil(sw*cs+sh*sn);c.height=Math.ceil(sw*sn+sh*cs);const x=c.getContext('2d');x.imageSmoothingEnabled=true;x.imageSmoothingQuality='high';x.translate(c.width/2,c.height/2);x.rotate(r);x.drawImage(src,-sw/2,-sh/2);return c}
function resizeCanvas(src){const maxW=2480,maxH=3508,scale=Math.min(1.5,maxW/src.width,maxH/src.height,src.width<1800&&src.height<2500?1.6:1);const out=document.createElement('canvas');out.width=Math.max(1,Math.round(src.width*scale));out.height=Math.max(1,Math.round(src.height*scale));const ctx=out.getContext('2d');ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(src,0,0,out.width,out.height);return out}
function buildIllumination(src){const w=src.width,h=src.height,sw=Math.max(64,Math.min(160,Math.round(w/32))),sh=Math.max(80,Math.min(220,Math.round(h/32)));const sm=document.createElement('canvas');sm.width=sw;sm.height=sh;const sx=sm.getContext('2d',{willReadFrequently:true});sx.drawImage(src,0,0,sw,sh);const sd=sx.getImageData(0,0,sw,sh).data,lum=new Float32Array(sw*sh);for(let i=0;i<lum.length;i++){const j=i*4;lum[i]=.2126*sd[j]+.7152*sd[j+1]+.0722*sd[j+2]}return {lum,sw,sh}}
function correctedColor(src){
  const out=resizeCanvas(src),ctx=out.getContext('2d',{willReadFrequently:true}),im=ctx.getImageData(0,0,out.width,out.height),d=im.data;
  const map=buildIllumination(out),lum=map.lum,sw=map.sw,sh=map.sh;
  // Only the camera-shadow side is corrected. The centre/right of the document is left alone.
  for(let y=0;y<out.height;y++){
    const fy=y*(sh-1)/Math.max(1,out.height-1),y0=Math.floor(fy),y1=Math.min(sh-1,y0+1),ty=fy-y0;
    for(let x=0;x<out.width;x++){
      const xn=x/Math.max(1,out.width-1);
      // Strongest on the left edge, fading completely by ~38% of the page width.
      let zone=1-Math.min(1,Math.max(0,(xn-.015)/.37));
      zone=zone*zone*(3-2*zone);
      if(zone<=0)continue;
      const fx=x*(sw-1)/Math.max(1,out.width-1),x0=Math.floor(fx),x1=Math.min(sw-1,x0+1),tx=fx-x0;
      const a=lum[y0*sw+x0]*(1-tx)+lum[y0*sw+x1]*tx,b=lum[y1*sw+x0]*(1-tx)+lum[y1*sw+x1]*tx,local=Math.max(28,a*(1-ty)+b*ty);
      // Estimate the nearby paper level from the brighter right half of the same row.
      let ref=0,count=0;for(let q=Math.floor(sw*.68);q<sw;q++){ref+=lum[Math.min(sh-1,Math.max(0,Math.round(fy)))*sw+q];count++}ref=count?ref/count:210;
      // Never turn the page pure white; correction is luminance-only, preserving colour ratios.
      const target=Math.min(222,Math.max(170,ref));
      let gain=target/Math.max(45,local);gain=Math.max(1,Math.min(1.72,gain));gain=1+(gain-1)*zone;
      const i=(y*out.width+x)*4,r=d[i],g=d[i+1],bl=d[i+2],l=.2126*r+.7152*g+.0722*bl;
      // Protect black ink, signatures, borders and other genuinely dark printed detail.
      const inkProtect=Math.max(0,Math.min(1,(l-48)/90));
      const eg=1+(gain-1)*inkProtect;
      d[i]=Math.min(255,r*eg);d[i+1]=Math.min(255,g*eg);d[i+2]=Math.min(255,bl*eg);
    }
  }
  ctx.putImageData(im,0,0);return out;
}
function cleanBW(src){const out=correctedColor(src),ctx=out.getContext('2d',{willReadFrequently:true}),im=ctx.getImageData(0,0,out.width,out.height),d=im.data;for(let i=0;i<d.length;i+=4){let v=.2126*d[i]+.7152*d[i+1]+.0722*d[i+2];v=Math.max(0,Math.min(255,(v-18)*1.10));d[i]=d[i+1]=d[i+2]=v}ctx.putImageData(im,0,0);return out}
function cleanColor(src){return correctedColor(src)}
async function loadPhoto(e){const f=e.target.files[0];if(!f)return;originalFile=f;originalDataUrl=null;sourcePages=[];processedPages=[];$('quality').classList.add('hidden');$('quality').textContent='';try{if(f.type==='application/pdf'||/\.pdf$/i.test(f.name)){const pdf=await ensurePdf();const buf=await f.arrayBuffer();const doc=await pdf.getDocument({data:buf}).promise;for(let n=1;n<=doc.numPages;n++){const page=await doc.getPage(n),base=page.getViewport({scale:2});const c=document.createElement('canvas');c.width=Math.ceil(base.width);c.height=Math.ceil(base.height);await page.render({canvasContext:c.getContext('2d'),viewport:base}).promise;sourcePages.push(c.toDataURL('image/png'))}$('quality').textContent=`✓ PDF loaded: ${doc.numPages} page${doc.numPages>1?'s':''}. Original PDF is untouched.`;$('quality').classList.remove('hidden')}else{originalDataUrl=await readAsDataURL(f);const im=await loadImage(originalDataUrl);sourcePages=[originalDataUrl];const low=im.width<1200||im.height<1200;$('quality').textContent=low?'⚠ Source is low-resolution.':'✓ Original source loaded. Color preserved; left camera-shadow correction is limited to the shadow zone.';$('quality').classList.remove('hidden')}}catch(err){console.error(err);alert('Could not read this file. Please try the original WhatsApp download again.');clearSensitive(false);return}await prepareProcessedPages()}
async function prepareProcessedPages(){if(!sourcePages.length)return;processedPages=[];const deskew=$('autoStraighten')?.checked===true,mode=$('mode')?.value||'Color';for(const src of sourcePages){const im=await loadImage(src);const c=document.createElement('canvas');c.width=im.naturalWidth||im.width;c.height=im.naturalHeight||im.height;c.getContext('2d').drawImage(im,0,0);let work=c;if(deskew&&type==='document'){const angle=estimateSkew(c);if(Math.abs(angle)>=2)work=rotateCanvas(c,angle)}const out=mode==='Black & White'?cleanBW(work):cleanColor(work);processedPages.push(out.toDataURL('image/png'))}$('typeHint').textContent=`✓ ${processedPages.length} print-ready page${processedPages.length>1?'s':''} prepared. Original file remains unchanged.`}
function canPrint(){if(CUSTOMER_TEST){if(type==='passport'){alert('Passport-size photos are Premium only. Please activate Smart Print Premium.');return false}const copies=Math.max(1,+$('copies').value||1),left=CUSTOMER_LIMIT-(data?.trialCopies||0);if(copies>left){alert(`Customer test limit reached. Only ${Math.max(0,left)} test pages remain.`);return false}return true}if(!account)return false;const active=isLicensed();if(!active){if(type==='passport'){alert('Passport-size photos are not available in the free trial.');return false}const copies=Math.max(1,+$('copies').value||1),left=TRIAL_LIMIT-(data.trialCopies||0);if(copies>left){alert(`Trial limit reached. Only ${Math.max(0,left)} test copies remain. License: ₹${PRICE.toLocaleString('en-IN')} + GST for 2 years.`);return false}}return true}
async function previewPrint(){if(!sourcePages.length)return alert('Upload a WhatsApp image or PDF first.');if(!canPrint())return;await prepareProcessedPages();const copies=Math.max(1,+$('copies').value||1);$('previewBody').innerHTML=`<div class="ai-badge">✓ Xerox Preview — left camera shadow reduced; original colour preserved; document details protected.</div>${processedPages.map((p,i)=>`<div class="preview-sheet"><p><b>${type==='passport'?'Passport Photo':type==='id'?'ID Card':'Document'} • Page ${i+1}${processedPages.length>1?` of ${processedPages.length}`:''} • ${copies} copy/copies</b></p><img src="${p}" alt="Print preview page ${i+1}"></div>`).join('')}`;$('preview').classList.remove('hidden')}
function closePreview(){$('preview').classList.add('hidden')}
async function printNow(){if(!sourcePages.length)return alert('Upload a WhatsApp image or PDF first.');if(!canPrint())return;await previewPrint()}
function confirmPrint(){if(!processedPages.length)return alert('Prepare the preview first.');const active=isLicensed(),copies=Math.max(1,+$('copies').value||1),paper=$('paper').value,w=window.open('','_blank');if(!w)return alert('Allow pop-ups to print.');const pages=[];for(let c=0;c<copies;c++)pages.push(...processedPages);w.document.write(`<html><head><title>NR BizPro Smart Print</title><style>@page{size:${paper};margin:10mm}body{font-family:Arial;margin:0}.page{page-break-after:always;display:flex;justify-content:center;align-items:center;min-height:calc(297mm - 20mm)}img{max-width:100%;max-height:277mm;object-fit:contain}</style></head><body>${pages.map(p=>`<div class="page"><img src="${p}"></div>`).join('')}<script>window.onload=()=>setTimeout(()=>window.print(),250);window.onafterprint=()=>window.close();<\/script></body></html>`);w.document.close();setTimeout(()=>{if(CUSTOMER_TEST||!active){data.trialCopies=(data.trialCopies||0)+copies;save()}closePreview();clearSensitive(true);updateLicense()},1200)}
function clearSensitive(clearFile=true){originalFile=null;originalDataUrl=null;sourcePages=[];processedPages=[];$('fileInput').value='';$('quality').classList.add('hidden');if($('copies'))$('copies').value=1;if(clearFile)$('typeHint').textContent='Upload the next WhatsApp document or photo.'}
window.selectType=selectType;window.loadPhoto=loadPhoto;window.previewPrint=previewPrint;window.closePreview=closePreview;window.printNow=printNow;window.confirmPrint=confirmPrint;window.canPrint=canPrint;window.enterPrint=enterPrint;
init();