(() => {
  const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
  async function api(url,opts={}){const r=await fetch(url,{credentials:'include',...opts});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
  window.renderStaffLogin=function(message=''){const el=document.getElementById('authContent');if(!el)return;el.innerHTML=`<div class="auth-title"><h1>Staff Login</h1><p>Login to your business account as staff.</p></div>${message?`<div class="notice">${esc(message)}</div>`:''}<form onsubmit="staffLogin(event)"><label>Staff Username<input id="staffLoginUsername" required autocomplete="username"></label><label>Password<input id="staffLoginPassword" required type="password" autocomplete="current-password"></label><button class="primary auth-btn">Staff Login</button></form><div class="auth-switch"><button class="secondary auth-btn" onclick="renderAuth('login')">Back to Business Login</button></div>`};
  window.staffLogin=async function(e){e.preventDefault();try{const d=await api('/api/staff',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'login',username:staffLoginUsername.value.trim(),password:staffLoginPassword.value})});window.currentUser=d.user;window.state=typeof window.loadData==='function'?window.loadData(d.user.id):window.state;if(typeof window.showApp==='function')window.showApp()}catch(err){renderStaffLogin(err.message)}};
  window.openStaffManager=async function(){try{const d=await api('/api/staff?action=list');const can=d.role==='owner';openModal('Staff Accounts',`<div class="staff-head"><p>Up to <b>3 staff logins</b> can use this business account.</p><p class="muted">Staff can work on the same business data; the owner controls staff access.</p></div><div id="staffList">${d.staff.map(s=>`<div class="staff-row"><div><b>${esc(s.name)}</b><small>@${esc(s.username)} • ${s.active?'Active':'Disabled'}</small></div>${can?`<div><button class="secondary" onclick="toggleStaff('${s.id}')">${s.active?'Disable':'Enable'}</button><button class="secondary" onclick="deleteStaff('${s.id}')">Delete</button></div>`:''}</div>`).join('')||'<div class="empty">No staff accounts yet.</div>'}</div>${can&&d.staff.length<3?`<hr><h3>Add Staff Login</h3><div class="modal-grid"><label class="field">Staff Name<input id="staffName"></label><label class="field">Username<input id="staffUsername" autocomplete="off"></label><label class="field">Password<input id="staffPassword" type="password" minlength="6" autocomplete="new-password"></label></div><div class="modal-actions"><button class="primary" onclick="createStaff()">Add Staff</button></div>`:''}`)}catch(err){alert(err.message)}};
  window.createStaff=async function(){try{const d=await api('/api/staff',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create',name:staffName.value.trim(),username:staffUsername.value.trim(),password:staffPassword.value})});alert(`Staff account ${d.staff.username} created.`);closeModal();openStaffManager()}catch(err){alert(err.message)}};
  window.toggleStaff=async function(id){try{await api('/api/staff',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'toggle',staffId:id})});closeModal();openStaffManager()}catch(err){alert(err.message)}};
  window.deleteStaff=async function(id){if(!confirm('Delete this staff login?'))return;try{await api('/api/staff',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'delete',staffId:id})});closeModal();openStaffManager()}catch(err){alert(err.message)}};
  window.showStaffTab=function(){if(typeof showTab==='function')showTab('staff');openStaffManager()};
})();
