// NR BizPro - Stationery / Book Store module
(function(){
'use strict';
const CAT=/stationery|book store/i;
const cats=['Notebooks','Books','Textbooks','School Supplies','Pens & Pencils','Art & Craft','Office Supplies','Files & Folders','Paper','Printing Material','Computer Stationery','Other'];
const brands=['Classmate','Camlin','Cello','Reynolds','Navneet','Luxor','Flair','DOMS','Apsara','Faber-Castell','HP','JK Paper','Paperkraft','Other Brand'];
const units=['Piece','Box','Pack','Dozen','Set','Ream','Kg'];
function active(){return CAT.test(String(document.getElementById('businessCategory')?.value||''))}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function getBrands(){if(typeof state==='undefined'||!state)return brands.slice();state.stationeryBrands=Array.isArray(state.stationeryBrands)?state.stationeryBrands:[];return [...new Set(brands.concat(state.stationeryBrands).map(x=>String(x).trim()).filter(Boolean))]}
function panel(){let p=document.getElementById('stationeryModule');if(p)return p;const shell=document.querySelector('#app main.shell');if(!shell)return null;p=document.createElement('section');p.id='stationeryModule';p.className='panel';p.style.cssText='display:none;margin:0 0 18px';const nav=shell.querySelector('.tabs');nav?shell.insertBefore(p,nav):shell.appendChild(p);return p}
function render(){const p=panel();if(!p)return;p.style.display=active()?'block':'none';if(!active())return;const bs=getBrands();p.innerHTML='<div class="panel-head"><div><p class="eyebrow">STATIONERY & BOOK STORE</p><h2 style="margin:0">Stationery / Book Product Management</h2><p class="muted">Manage books and stationery item-wise with category, class/subject, edition, ISBN, price and stock.</p></div></div><div class="card" style="padding:16px;margin-top:14px"><div style="display:flex;gap:10px;flex-wrap:wrap;align-items:end"><label style="flex:1;min-width:220px">Add Brand / Publisher<input id="stBrandNew" placeholder="Enter brand or publisher"></label><button class="secondary" type="button" id="stAddBrand">+ Add Brand</button></div></div><div class="card" style="padding:16px;margin-top:14px"><div class="form-grid"><label>Product / Book Name<input id="stName" placeholder="Notebook / Textbook"></label><label>Brand / Publisher<select id="stBrand">'+bs.map(x=>'<option>'+esc(x)+'</option>').join('')+'</select></label><label>Category<select id="stCategory">'+cats.map(x=>'<option>'+esc(x)+'</option>').join('')+'</select></label><label>Class / Subject<input id="stSubject" placeholder="Class 10 / Mathematics"></label><label>Author<input id="stAuthor" placeholder="Author name"></label><label>ISBN / SKU<input id="stIsbn" placeholder="ISBN or SKU"></label><label>Edition / Year<input id="stEdition" placeholder="2026 Edition"></label><label>Unit<select id="stUnit">'+units.map(x=>'<option>'+x+'</option>').join('')+'</select></label><label>MRP<input id="stMrp" type="number" min="0" step="0.01" value="0"></label><label>Purchase Price<input id="stCost" type="number" min="0" step="0.01" value="0"></label><label>Selling Price<input id="stSell" type="number" min="0" step="0.01" value="0"></label><label>GST %<input id="stGst" type="number" min="0" step="0.01" value="0"></label><label>Opening Stock<input id="stStock" type="number" min="0" step="1" value="0"></label></div><div style="display:flex;justify-content:flex-end;margin-top:12px"><button class="primary" type="button" id="stAdd">+ Add Product</button></div></div><div class="card" style="padding:16px;margin-top:14px"><div class="table-wrap"><table><thead><tr><th>Product</th><th>Brand / Publisher</th><th>Category</th><th>Class / Subject</th><th>ISBN / SKU</th><th>Edition</th><th>Unit</th><th>Selling</th><th>Stock</th></tr></thead><tbody id="stTable"></tbody></table></div></div>';bind();table()}
function bind(){const g=id=>document.getElementById(id);g('stAddBrand')?.addEventListener('click',()=>{const v=String(g('stBrandNew')?.value||'').trim();if(!v)return;if(typeof state!=='undefined'){state.stationeryBrands=Array.isArray(state.stationeryBrands)?state.stationeryBrands:[];if(!state.stationeryBrands.includes(v))state.stationeryBrands.push(v);if(typeof save==='function')save()}render()});g('stAdd')?.addEventListener('click',()=>{if(typeof state==='undefined'||!Array.isArray(state.items))return;const name=String(g('stName')?.value||'').trim();if(!name){alert('Please enter Product / Book Name');g('stName')?.focus();return}const item={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),name,brand:g('stBrand')?.value||'',stationeryCategory:g('stCategory')?.value||'',stSubject:g('stSubject')?.value||'',stAuthor:g('stAuthor')?.value||'',stIsbn:g('stIsbn')?.value||'',stEdition:g('stEdition')?.value||'',stUnit:g('stUnit')?.value||'Piece',mrp:Number(g('stMrp')?.value||0),cost:Number(g('stCost')?.value||0),sell:Number(g('stSell')?.value||0),gst:Number(g('stGst')?.value||0),stock:Number(g('stStock')?.value||0),businessType:'stationery',type:'Product',barcode:'',margin:0,marginType:'fixed'};state.items.push(item);if(typeof save==='function')save();table();if(typeof updateStats==='function')updateStats();['stName','stSubject','stAuthor','stIsbn','stEdition','stMrp','stCost','stSell','stGst','stStock'].forEach(id=>{const e=g(id);if(e)e.value=['stName','stSubject','stAuthor','stIsbn','stEdition'].includes(id)?'':'0'})})}
function table(){const tb=document.getElementById('stTable');if(!tb)return;const arr=(typeof state!=='undefined'&&Array.isArray(state.items)?state.items:[]).filter(i=>i.businessType==='stationery');tb.innerHTML=arr.length?arr.map(i=>'<tr><td><b>'+esc(i.name)+'</b></td><td>'+esc(i.brand||'—')+'</td><td>'+esc(i.stationeryCategory||'—')+'</td><td>'+esc(i.stSubject||'—')+'</td><td>'+esc(i.stIsbn||'—')+'</td><td>'+esc(i.stEdition||'—')+'</td><td>'+esc(i.stUnit||'Piece')+'</td><td>₹'+Number(i.sell||0).toFixed(2)+'</td><td>'+Number(i.stock||0)+'</td></tr>').join(''):'<tr><td colspan="9" class="empty">No stationery / book products added yet.</td></tr>'}
function start(){if(!document.getElementById('app'))return;document.addEventListener('change',e=>{if(e.target?.id==='businessCategory')render()});render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();