module.exports = async function handler(req,res){
  const upstream="https://letmytrip-1k8eqgagd-maskuri-ravindhars-projects.vercel.app/";
  try{
    const r=await fetch(upstream,{cache:"no-store"});
    if(!r.ok)return res.status(502).send("LETMYTRIP upstream unavailable");
    let s=await r.text();
    const old="<div class=\"modal\" id=\"modal\"><div class=\"modalbox\"><button class=\"close\" onclick=\"closeModal()\">×</button><h2>Welcome to LETMYTRIP</h2><p class=\"lead\" style=\"font-size:14px\">Mobile OTP login will be compulsory.</p><input placeholder=\"Mobile number\"><button class=\"btn primary\" style=\"width:100%;margin-top:7px\" onclick=\"alert('OTP backend integration is the next step.')\">Send OTP</button></div></div>";
    const modal="<div class=\"modal\" id=\"modal\"><div class=\"modalbox\"><button class=\"close\" onclick=\"closeModal()\">×</button><div class=\"eyebrow\">Secure access</div><h2>Welcome to LETMYTRIP</h2><p class=\"lead\" style=\"font-size:14px\">Login / Sign Up with your mobile number. OTP verification is compulsory.</p><div class=\"field\"><label>Mobile Number</label><input id=\"otpMobile\" inputmode=\"numeric\" maxlength=\"10\" placeholder=\"10-digit mobile number\" autocomplete=\"tel\"></div><button class=\"btn primary\" style=\"width:100%;margin-top:10px\" onclick=\"sendLetmytripOtp()\">Send OTP</button><div id=\"otpStage\" style=\"display:none;margin-top:12px\"><div class=\"field\"><label>Enter OTP</label><input id=\"otpCode\" inputmode=\"numeric\" maxlength=\"6\" placeholder=\"6-digit OTP\" autocomplete=\"one-time-code\"></div><div style=\"display:flex;gap:8px;margin-top:8px\"><button class=\"btn primary\" style=\"flex:1\" onclick=\"verifyLetmytripOtp()\">Verify & Continue</button><button class=\"btn\" style=\"flex:1\" onclick=\"retryLetmytripOtp()\">Resend OTP</button></div></div><p id=\"otpStatus\" style=\"font-size:12px;font-weight:800;margin:10px 0 0\"></p></div></div>";
    if(!s.includes(old))return res.status(500).send("LETMYTRIP login marker not found");
    s=s.replace(old,modal);
    s=s.replace("</body></html>","<script>(function(){let loaded=false,ready=false,mobile=\"\";function st(m,ok){const e=document.getElementById(\"otpStatus\");if(e){e.textContent=m;e.style.color=ok?\"#087a55\":\"#a23b2a\"}}async function sdk(){if(loaded)return;loaded=true;const c=await fetch(\"/api/config\").then(r=>r.json());if(!c.configured)throw Error(\"MSG91 OTP is not configured yet.\");await new Promise((ok,no)=>{window.__ltotp={widgetId:c.widgetId,tokenAuth:c.tokenAuth,exposeMethods:true,captchaRenderId:\"\",success:()=>{},failure:()=>{}};const x=document.createElement(\"script\");x.src=\"https://verify.msg91.com/otp-provider.js\";x.onload=()=>{try{initSendOTP(window.__ltotp);ready=true;ok()}catch(e){no(e)}};x.onerror=()=>no(Error(\"Unable to load MSG91 OTP service.\"));document.head.appendChild(x)})}window.sendLetmytripOtp=async()=>{const n=(document.getElementById(\"otpMobile\").value||\"\").replace(/\\D/g,\"\");if(!/^[6-9]\\d{9}$/.test(n)){st(\"Please enter a valid 10-digit Indian mobile number.\");return}mobile=\"91\"+n;st(\"Connecting to secure OTP service...\");try{await sdk();window.sendOtp(mobile,()=>{document.getElementById(\"otpStage\").style.display=\"block\";st(\"OTP sent successfully. Please check your mobile.\",true)},()=>st(\"OTP could not be sent. Please try again.\"))}catch(e){st(e.message||\"OTP service unavailable.\")}};window.retryLetmytripOtp=()=>{if(!window.retryOtp){st(\"OTP service is not ready.\");return}window.retryOtp(null,()=>st(\"New OTP sent successfully.\",true),()=>st(\"Could not resend OTP.\"))};window.verifyLetmytripOtp=()=>{const n=(document.getElementById(\"otpCode\").value||\"\").replace(/\\D/g,\"\");if(!/^\\d{6}$/.test(n)){st(\"Please enter the 6-digit OTP.\");return}if(!window.verifyOtp){st(\"OTP service is not ready.\");return}st(\"Verifying OTP...\");window.verifyOtp(Number(n),async d=>{const t=d?.accessToken||d?.access_token||d?.token||d?.message?.accessToken||d?.message?.access_token;if(!t){st(\"OTP verified, but secure access token was not returned.\");return}try{const r=await fetch(\"/api/verify-access-token\",{method:\"POST\",headers:{\"Content-Type\":\"application/json\"},body:JSON.stringify({accessToken:t})});const o=await r.json().catch(()=>({}));if(!r.ok){st(o.error||\"Server verification failed.\");return}localStorage.setItem(\"letmytrip_verified_mobile\",mobile.slice(2));localStorage.setItem(\"letmytrip_verified\",\"1\");st(\"Mobile verified successfully. Welcome to LETMYTRIP.\",true);setTimeout(closeModal,700)}catch(e){st(\"Network error while confirming verification.\")}},()=>st(\"Invalid or expired OTP. Please try again.\"))}}})()</script>"+"</body></html>");
    res.setHeader("Content-Type","text/html; charset=utf-8");
    res.setHeader("Cache-Control","no-store, max-age=0");
    return res.status(200).send(s);
  }catch(e){return res.status(502).send("LETMYTRIP service error")}
}
