-- LETMYTRIP service-wise pricing settings
create table if not exists public.letmytrip_service_pricing (
  id bigint generated by default as identity primary key,
  service_type text not null unique check (service_type in ('BUS','FLIGHT','HOTEL','PACKAGE')),
  platform_fee numeric not null default 0 check (platform_fee >= 0),
  company_markup_mode text not null default 'FIXED' check (company_markup_mode in ('FIXED','PERCENT')),
  company_markup numeric not null default 0 check (company_markup >= 0),
  company_markup_max numeric not null default 0 check (company_markup_max >= 0),
  customer_markup_mode text not null default 'FIXED' check (customer_markup_mode in ('FIXED','PERCENT')),
  customer_markup numeric not null default 0 check (customer_markup >= 0),
  customer_markup_max numeric not null default 0 check (customer_markup_max >= 0),
  updated_at timestamptz not null default now()
);
alter table public.letmytrip_service_pricing enable row level security;
insert into public.letmytrip_service_pricing (service_type, platform_fee)
values ('BUS',0),('FLIGHT',0),('HOTEL',0),('PACKAGE',0)
on conflict (service_type) do nothing;
