import {sql,initDb,ensureAdmin,hashPassword,verifyPassword,token,cookie,clearCookie,sessionAdmin} from './db.js';
function send(res,c,b){res.setHeader('Content-Type','application/json');res.status(c).json(b)}
function addDays(days){const d=new Date();d.setDate(d.getDate()+days);return d.toISOString()}
export default async function handler(req,res){await initDb();try{
 if(req.method==='POST'&&req.body?.action==='login'){const cfg=await ensureAdmin();const r=await sql`SELECT * FROM admins WHERE email=${req.body.email?.trim().toLowerCase()}`;if(!r.rows[0]||!(await verifyPassword(req.body.password||'',r.rows[0].password_hash)))return send(res,401,{error:'Invalid admin credentials.'});const t=token();await sql`INSERT INTO sessions(token,admin,expires_at) VALUES(${t},true,now()+interval '12 hours')`;res.setHeader('Set-Cookie',`nr_admin=${t}; Path=/; HttpOnly; Secure; SameSite=Lax`);return send(res,200,{ok:true,email:r.rows[0].email,defaulted:cfg.defaulted})}
 if(req.method==='POST'&&req.body?.action==='logout'){clearCookie(res,'nr_admin');return send(res,200,{ok:true})}
 if(req.method==='GET'&&req.query.action==='session'){if(!(await sessionAdmin(req)))return send(res,401,{error:'Admin login required'});return send(res,200,{ok:true})}
 if(!(await sessionAdmin(req)))return send(res,401,{error:'Admin login required'});
 if(req.method==='GET'&&req.query.action==='businesses'){const r=await sql`SELECT id,business,owner,mobile,email,category,gst,status,plan,subscription_ends,created_at FROM businesses ORDER BY created_at DESC`;return send(res,200,{businesses:r.rows})}
 if(req.method==='GET'&&req.query.action==='direct-payments'){const status=String(req.query.status||'').trim();const r=status?await sql`SELECT p.id,p.business_id,p.plan,p.amount,p.utr,p.status,p.admin_note,p.created_at,p.reviewed_at,b.business,b.owner,b.mobile,b.email FROM direct_payments p JOIN businesses b ON b.id=p.business_id WHERE p.status=${status} ORDER BY p.created_at DESC`:await sql`SELECT p.id,p.business_id,p.plan,p.amount,p.utr,p.status,p.admin_note,p.created_at,p.reviewed_at,b.business,b.owner,b.mobile,b.email FROM direct_payments p JOIN businesses b ON b.id=p.business_id ORDER BY p.created_at DESC`;return send(res,200,{payments:r.rows})}
 if(req.method==='GET'&&req.query.action==='payment-config'){const r=await sql`SELECT key,value FROM platform_settings WHERE key IN ('upi_id','upi_name')`;const s=Object.fromEntries(r.rows.map(x=>[x.key,x.value]));return send(res,200,{upiId:s.upi_id||process.env.NRBIZPRO_UPI_ID||'',upiName:s.upi_name||process.env.NRBIZPRO_UPI_NAME||'NR BizPro'})}
 if(req.method==='POST'&&req.body?.action==='payment-config'){const upi=String(req.body?.upiId||'').trim();const name=String(req.body?.upiName||'NR BizPro').trim()||'NR BizPro';if(!/^[A-Za-z0-9._-]{2,80}@[A-Za-z0-9._-]{2,80}$/.test(upi))return send(res,400,{error:'Enter a valid UPI ID, e.g. business@bank'});await sql`INSERT INTO platform_settings(key,value) VALUES('upi_id',${upi}) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=now()`;await sql`INSERT INTO platform_settings(key,value) VALUES('upi_name',${name}) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=now()`;return send(res,200,{ok:true,upiId:upi,upiName:name})}
 if(req.method==='POST'&&req.body?.action==='create-business'){const {business,owner,mobile,email,category,gst,password}=req.body||{};if(!business||!owner||!mobile||!email||!category||!password||String(password).length<6)return send(res,400,{error:'Business, owner, mobile, email, category and password are required. Password must be at least 6 characters.'});const exists=await sql`SELECT id FROM businesses WHERE lower(email)=lower(${String(email).trim()}) OR mobile=${String(mobile).trim()}`;if(exists.rowCount)return send(res,409,{error:'A business already exists with this email or mobile.'});const id=globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;const h=await hashPassword(String(password));await sql`INSERT INTO businesses(id,business,owner,mobile,email,category,gst,password_hash,status) VALUES(${id},${String(business).trim()},${String(owner).trim()},${String(mobile).trim()},${String(email).trim().toLowerCase()},${String(category).trim()},${String(gst||'').trim()},${h},'pending')`;await sql`INSERT INTO business_data(business_id,settings) VALUES(${id},${JSON.stringify({name:String(business).trim(),category:String(category).trim(),mobile:String(mobile).trim(),gst:String(gst||'').trim(),address:''})}::jsonb)`;return send(res,200,{ok:true,businessId:id,status:'pending'})}
 if(req.method==='POST'&&req.body?.action==='business-status'){const businessId=String(req.body?.businessId||'');const status=String(req.body?.status||'');if(!businessId||!['active','suspended','pending'].includes(status))return send(res,400,{error:'Invalid business status.'});const r=await sql`SELECT * FROM businesses WHERE id=${businessId}`;const b=r.rows[0];if(!b)return send(res,404,{error:'Business not found.'});if(status==='active'){const days=Math.max(1,Math.min(3650,Number(req.body?.days||365)));const ends=addDays(days);await sql`UPDATE businesses SET status='active',plan=${String(req.body?.plan||'admin')},subscription_ends=${ends},pending_plan=null,pending_amount=0,updated_at=now() WHERE id=${businessId}`;return send(res,200,{ok:true,status:'active',subscriptionEnds:ends})}if(status==='suspended'){await sql`UPDATE businesses SET status='suspended',updated_at=now() WHERE id=${businessId}`;await sql`DELETE FROM sessions WHERE business_id=${businessId}`;return send(res,200,{ok:true,status:'suspended'})}await sql`UPDATE businesses SET status='pending',plan=null,subscription_ends=null,updated_at=now() WHERE id=${businessId}`;await sql`DELETE FROM sessions WHERE business_id=${businessId}`;return send(res,200,{ok:true,status:'pending'})}
 if(req.method==='POST'&&req.body?.action==='reject-business'){const businessId=String(req.body?.businessId||'');if(!businessId)return send(res,400,{error:'Business ID is required.'});const r=await sql`SELECT id FROM businesses WHERE id=${businessId}`;if(!r.rows[0])return send(res,404,{error:'Business not found.'});await sql`UPDATE businesses SET status='rejected',updated_at=now() WHERE id=${businessId}`;await sql`DELETE FROM sessions WHERE business_id=${businessId}`;return send(res,200,{ok:true,status:'rejected'})}
 if(req.method==='POST'&&req.body?.action==='delete-business'){const businessId=String(req.body?.businessId||'');if(!businessId)return send(res,400,{error:'Business ID is required.'});const r=await sql`SELECT id,business,email FROM businesses WHERE id=${businessId}`;if(!r.rows[0])return send(res,404,{error:'Business not found.'});await sql`DELETE FROM businesses WHERE id=${businessId}`;return send(res,200,{ok:true,deletedBusiness:r.rows[0]})}
 if(req.method==='POST'&&req.body?.action==='approve-business'){const businessId=String(req.body?.businessId||'');if(!businessId)return send(res,400,{error:'Business ID is required.'});const r=await sql`SELECT id FROM businesses WHERE id=${businessId}`;if(!r.rows[0])return send(res,404,{error:'Business not found.'});const ends=addDays(365);await sql`UPDATE businesses SET status='active',plan='admin',subscription_ends=${ends},pending_plan=null,pending_amount=0,updated_at=now() WHERE id=${businessId}`;return send(res,200,{ok:true,status:'active',subscriptionEnds:ends})}
 if(req.method==='POST'&&req.body?.action==='approve-direct-payment'){const paymentId=String(req.body?.paymentId||'');if(!paymentId)return send(res,400,{error:'Payment ID is required.'});const r=await sql`SELECT * FROM direct_payments WHERE id=${paymentId}`;const p=r.rows[0];if(!p)return send(res,404,{error:'Payment not found.'});if(p.status!=='pending')return send(res,409,{error:`Payment is already ${p.status}.`});const b=await sql`SELECT * FROM businesses WHERE id=${p.business_id}`;if(!b.rows[0])return send(res,404,{error:'Business not found.'});const years={year3:3}[p.plan];const lifetime=p.plan==='lifetime';if(!years&&!lifetime)return send(res,400,{error:'Invalid plan on payment.'});const base=(b.rows[0].subscription_ends&&new Date(b.rows[0].subscription_ends)>new Date())?new Date(b.rows[0].subscription_ends):new Date();let ends=null;if(!lifetime){base.setFullYear(base.getFullYear()+years);ends=base.toISOString();}await sql`UPDATE direct_payments SET status='approved',reviewed_at=now(),admin_note=${String(req.body?.note||'Payment verified and approved.')} WHERE id=${paymentId}`;await sql`UPDATE businesses SET status='active',plan=${p.plan},subscription_ends=${ends},pending_plan=null,pending_amount=0,last_payment_id=${paymentId},updated_at=now() WHERE id=${p.business_id}`;return send(res,200,{ok:true,status:'approved',businessId:p.business_id,subscriptionEnds:ends})}
 if(req.method==='POST'&&req.body?.action==='reject-direct-payment'){const paymentId=String(req.body?.paymentId||'');if(!paymentId)return send(res,400,{error:'Payment ID is required.'});const r=await sql`SELECT id,status FROM direct_payments WHERE id=${paymentId}`;if(!r.rows[0])return send(res,404,{error:'Payment not found.'});if(r.rows[0].status!=='pending')return send(res,409,{error:`Payment is already ${r.rows[0].status}.`});await sql`UPDATE direct_payments SET status='rejected',reviewed_at=now(),admin_note=${String(req.body?.note||'Payment could not be verified.')} WHERE id=${paymentId}`;return send(res,200,{ok:true,status:'rejected'})}
 return send(res,404,{error:'Unknown action'});
}catch(e){console.error(e);return send(res,500,{error:'Admin server error'})}}
