import { sql,initDb,hashPassword,verifyPassword,token,cookie,clearCookie,sessionBusiness } from './db.js';
function send(res,c,b){res.setHeader('Content-Type','application/json');res.status(c).json(b)}
const PLAN_FEES={year3:3500,lifetime:6000};
function pub(b){if(!b)return null;return {id:b.id,userId:b.user_id,business:b.business,owner:b.owner,mobile:b.mobile,email:b.email,category:b.category,gst:b.gst,status:b.status,plan:b.plan,subscriptionEnds:b.subscription_ends,pendingPlan:b.pending_plan,pendingAmount:Number(b.pending_amount||0),lastPaymentId:b.last_payment_id,phoneVerified:!!b.phone_verified,emailVerified:!!b.email_verified,registrationFee:3500}}
export default async function handler(req,res){await initDb();const a=req.body?.action||req.query?.action;try{
 if(req.method==='POST'&&a==='signup'){const {business,owner,mobile,email,category,gst,password}=req.body||{};if(!business||!owner||!mobile||!email||!category||!password||String(password).length<6)return send(res,400,{error:'Please fill all required fields. Password must be at least 6 characters.'});const exists=await sql`SELECT id FROM businesses WHERE lower(email)=lower(${email}) OR mobile=${mobile}`;if(exists.rowCount)return send(res,409,{error:'An account already exists with this email or mobile.'});const id=cryptoRandom();const base=String(email).toLowerCase().split('@')[0].replace(/[^a-z0-9._-]/g,'').slice(0,40)||'user';let userId=base;for(let i=0;i<5;i++){const u=await sql`SELECT id FROM businesses WHERE lower(user_id)=lower(${userId})`;if(!u.rowCount)break;userId=`${base}-${Math.random().toString(36).slice(2,7)}`}const h=await hashPassword(password);await sql`INSERT INTO businesses(id,user_id,business,owner,mobile,email,category,gst,password_hash,phone_verified,email_verified,status) VALUES(${id},${userId},${business},${owner},${mobile},${email.toLowerCase()},${category},${gst||''},${h},false,false,'pending')`;await sql`INSERT INTO business_data(business_id,settings) VALUES(${id},${JSON.stringify({name:business,category,mobile,gst:gst||'',address:''})}::jsonb)`;const t=token();await sql`INSERT INTO sessions(token,business_id,expires_at) VALUES(${t},${id},now()+interval '30 days')`;cookie(res,'nr_session',t);const user={id,user_id:userId,business,owner,mobile,email:email.toLowerCase(),category,gst,status:'pending',plan:null,subscription_ends:null,pending_plan:null,pending_amount:0,last_payment_id:null,phone_verified:false,email_verified:false};return send(res,200,{user:pub(user),registrationFee:3500,verificationRequired:false,paymentRequired:true})}
 if(req.method==='POST'&&a==='login'){const id=String(req.body?.id||'').trim().toLowerCase(),password=String(req.body?.password||'');const r=await sql`SELECT * FROM businesses WHERE lower(user_id)=${id} OR lower(email)=${id} OR mobile=${id} ORDER BY created_at DESC LIMIT 1`;const b=r.rows[0];if(!b||!(await verifyPassword(password,b.password_hash)))return send(res,401,{error:'Invalid login details.'});const t=token();await sql`INSERT INTO sessions(token,business_id,expires_at) VALUES(${t},${b.id},now()+interval '30 days')`;cookie(res,'nr_session',t);if(b.status!=='active')return send(res,403,{error:'Membership payment is required before using NR BizPro.',paymentRequired:true,user:pub(b)});if(b.status==='active'&&b.subscription_ends&&new Date(b.subscription_ends)<=new Date())await sql`UPDATE businesses SET status='expired',updated_at=now() WHERE id=${b.id}`;const rr=await sql`SELECT * FROM businesses WHERE id=${b.id}`;return send(res,200,{user:pub(rr.rows[0])})}
 if(req.method==='GET'&&a==='me'){const b=await sessionBusiness(req);if(!b)return send(res,401,{error:'Not logged in'});return send(res,200,{user:pub(b)})}
 if(req.method==='POST'&&a==='logout'){const t=req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith('nr_session='))?.slice(11);if(t)await sql`DELETE FROM sessions WHERE token=${t}`;clearCookie(res,'nr_session');return send(res,200,{ok:true})}
 if(req.method==='POST'&&a==='pending'){const b=await sessionBusiness(req);if(!b)return send(res,401,{error:'Please complete registration first.'});const plan=req.body?.plan;if(!Object.prototype.hasOwnProperty.call(PLAN_FEES,plan))return send(res,400,{error:'Select a valid membership plan.'});const amount=PLAN_FEES[plan]+3500;await sql`UPDATE businesses SET pending_plan=${plan},pending_amount=${amount},updated_at=now() WHERE id=${b.id}`;const r=await sql`SELECT * FROM businesses WHERE id=${b.id}`;return send(res,200,{user:pub(r.rows[0]),registrationFee:3500,planFee:PLAN_FEES[plan],total:amount})}
 if(req.method==='POST'&&a==='business-settings'){const b=await sessionBusiness(req);if(!b)return send(res,401,{error:'Not logged in'});const s=req.body?.settings||{};await sql`UPDATE businesses SET business=${s.name||b.business},category=${s.category||b.category},mobile=${s.mobile||b.mobile},gst=${s.gst||''},updated_at=now() WHERE id=${b.id}`;await sql`INSERT INTO business_data(business_id,settings) VALUES(${b.id},${JSON.stringify(s)}::jsonb) ON CONFLICT(business_id) DO UPDATE SET settings=EXCLUDED.settings,updated_at=now()`;return send(res,200,{ok:true})}
 return send(res,404,{error:'Unknown action'});
}catch(e){console.error(e);return send(res,500,{error:'Server error'})}}
function cryptoRandom(){return globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`}
