import {sql,initDb,hashPassword,verifyPassword,token,getCookie,cookie,clearCookie} from './db.js';

async function hospital(req){const t=getCookie(req,'nr_hms_session');if(!t)return null;const r=await sql`SELECT h.* FROM hms_sessions s JOIN hms_hospitals h ON h.id=s.hospital_id WHERE s.token=${t} AND s.expires_at>now() LIMIT 1`;return r.rows[0]||null}
async function pro(req){const t=getCookie(req,'nr_hms_pro_session');if(!t)return null;const r=await sql`SELECT p.* FROM hms_pro_sessions s JOIN hms_pros p ON p.id=s.pro_id WHERE s.token=${t} AND s.expires_at>now() LIMIT 1`;return r.rows[0]||null}
async function setup(){await initDb();await sql`CREATE TABLE IF NOT EXISTS hms_pros (id text PRIMARY KEY,hospital_id text NOT NULL,pro_id text NOT NULL,name text NOT NULL,mobile text NOT NULL,password_hash text NOT NULL,can_negotiate boolean NOT NULL DEFAULT false,max_discount numeric(12,2) NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(hospital_id,pro_id))`;await sql`CREATE TABLE IF NOT EXISTS hms_pro_sessions (token text PRIMARY KEY,pro_id text NOT NULL,expires_at timestamptz NOT NULL)`;await sql`CREATE TABLE IF NOT EXISTS hms_package_negotiations (id text PRIMARY KEY,hospital_id text NOT NULL,patient_opd text NOT NULL,patient_name text NOT NULL,standard_amount numeric(12,2) NOT NULL,final_amount numeric(12,2) NOT NULL,discount numeric(12,2) NOT NULL,reason text NOT NULL,pro_id text NOT NULL,pro_name text NOT NULL,created_at timestamptz NOT NULL DEFAULT now())`}
export default async function handler(req,res){try{await setup();const a=req.query.action||'';if(a==='create-pro'){const h=await hospital(req);if(!h)return res.status(401).json({error:'Hospital login required'});const b=req.body||{};if(!b.proId||!b.name||!b.mobile||!b.password)return res.status(400).json({error:'PRO ID, name, mobile and password are required'});const ph=await hashPassword(b.password);await sql`INSERT INTO hms_pros(id,hospital_id,pro_id,name,mobile,password_hash,can_negotiate,max_discount) VALUES(${token()},${h.id},${b.proId.trim()},${b.name.trim()},${b.mobile.trim()},${ph},${!!b.canNegotiate},${Number(b.maxDiscount||0)}) ON CONFLICT(hospital_id,pro_id) DO UPDATE SET name=EXCLUDED.name,mobile=EXCLUDED.mobile,password_hash=EXCLUDED.password_hash,can_negotiate=EXCLUDED.can_negotiate,max_discount=EXCLUDED.max_discount`;return res.json({ok:true})}
if(a==='pro-login'){const b=req.body||{};const r=await sql`SELECT * FROM hms_pros WHERE hospital_id=${b.hospitalId} AND pro_id=${b.proId} LIMIT 1`;const p=r.rows[0];if(!p||!(await verifyPassword(b.password||'',p.password_hash)))return res.status(401).json({error:'Invalid PRO login'});const t=token();await sql`INSERT INTO hms_pro_sessions(token,pro_id,expires_at) VALUES(${t},${p.id},now()+interval '30 days')`;cookie(res,'nr_hms_pro_session',t);return res.json({ok:true,pro:{id:p.pro_id,name:p.name,hospitalId:p.hospital_id,canNegotiate:p.can_negotiate,maxDiscount:Number(p.max_discount)}})}
if(a==='pro-me'){const p=await pro(req);if(!p)return res.status(401).json({error:'PRO login required'});return res.json({ok:true,pro:{id:p.pro_id,name:p.name,hospitalId:p.hospital_id,canNegotiate:p.can_negotiate,maxDiscount:Number(p.max_discount)}})}
if(a==='negotiate'){const p=await pro(req);if(!p)return res.status(401).json({error:'PRO login required'});if(!p.can_negotiate)return res.status(403).json({error:'Negotiated package permission not enabled for this PRO'});const b=req.body||{}, standard=Number(b.standardAmount), final=Number(b.finalAmount), discount=standard-final;if(!b.patientOpd||!b.patientName||!b.reason||!Number.isFinite(standard)||!Number.isFinite(final)||final<=0||discount<0)return res.status(400).json({error:'Patient, standard amount, final amount and reason are required'});if(Number(p.max_discount)>0&&discount>Number(p.max_discount))return res.status(403).json({error:'Discount exceeds this PRO approval limit'});const id=token();await sql`INSERT INTO hms_package_negotiations(id,hospital_id,patient_opd,patient_name,standard_amount,final_amount,discount,reason,pro_id,pro_name) VALUES(${id},${p.hospital_id},${b.patientOpd},${b.patientName},${standard},${final},${discount},${b.reason.trim()},${p.pro_id},${p.name})`;return res.json({ok:true,negotiation:{id,patientOpd:b.patientOpd,patientName:b.patientName,standardAmount:standard,finalAmount:final,discount,reason:b.reason,negotiatedBy:p.name}})}
if(a==='list'){const p=await pro(req);if(!p)return res.status(401).json({error:'PRO login required'});const r=await sql`SELECT id,patient_opd AS "patientOpd",patient_name AS "patientName",standard_amount AS "standardAmount",final_amount AS "finalAmount",discount,reason,pro_name AS "negotiatedBy",created_at AS "createdAt" FROM hms_package_negotiations WHERE hospital_id=${p.hospital_id} ORDER BY created_at DESC LIMIT 200`;return res.json({ok:true,items:r.rows})}
if(a==='pro-logout'){clearCookie(res,'nr_hms_pro_session');return res.json({ok:true})}
return res.json({ok:true})}catch(e){console.error('hms-pro',e);return res.status(500).json({error:e.message||'Server error'})}}