import { sql, initDb, hashPassword, verifyPassword, token, getCookie } from './db.js';
const send=(res,c,b)=>{res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');res.status(c).json(b)};
const pub=h=>h&&({id:h.id,hospital:h.hospital,owner:h.owner,mobile:h.mobile,email:h.email,userId:h.user_id,address:h.address||''});
async function setup(){await initDb();await sql\`CREATE TABLE IF NOT EXISTS hms_hospitals (id text PRIMARY KEY,hospital text NOT NULL,owner text NOT NULL,mobile text NOT NULL,email text NOT NULL,user_id text NOT NULL UNIQUE,address text NOT NULL DEFAULT '',password_hash text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())\`;await sql\`CREATE TABLE IF NOT EXISTS hms_sessions (token text PRIMARY KEY,hospital_id text NOT NULL REFERENCES hms_hospitals(id) ON DELETE CASCADE,expires_at timestamptz NOT NULL)\`;await sql\`CREATE TABLE IF NOT EXISTS hms_data (hospital_id text PRIMARY KEY REFERENCES hms_hospitals(id) ON DELETE CASCADE,patients jsonb NOT NULL DEFAULT '[]',doctors jsonb NOT NULL DEFAULT '[]',appointments jsonb NOT NULL DEFAULT '[]',bills jsonb NOT NULL DEFAULT '[]',updated_at timestamptz NOT NULL DEFAULT now())\`}
async function session(req){const t=getCookie(req,'nr_hms_session');if(!t)return null;const r=await sql\`SELECT h.* FROM hms_sessions s JOIN hms_hospitals h ON h.id=s.hospital_id WHERE s.token=\${t} AND s.expires_at>now() LIMIT 1\`;return r.rows[0]||null}
export default async function handler(req,res){await setup();try{const a=req.body?.action||req.query?.action;
if(req.method==='POST'&&a==='signup'){const x=req.body||{};const hospital=String(x.hospital||'').trim(),owner=String(x.owner||'').trim(),mobile=String(x.mobile||'').trim(),email=String(x.email||'').trim().toLowerCase(),userId=String(x.userId||'').trim().toLowerCase(),address=String(x.address||'').trim(),password=String(x.password||'');if(!hospital||!owner||!mobile||!email||!/^[a-z0-9._-]{4,40}$/.test(userId)||password.length<8||!address)return send(res,400,{error:'Please fill all hospital details. Login ID must be 4-40 characters and password must be at least 8 characters.'});const ex=await sql\`SELECT id FROM hms_hospitals WHERE lower(user_id)=lower(\${userId}) OR lower(email)=lower(\${email}) OR mobile=\${mobile} LIMIT 1\`;if(ex.rowCount)return send(res,409,{error:'Hospital account already exists with this Login ID, email or mobile.'});const id=cryptoRandom(),h=await hashPassword(password);await sql\`INSERT INTO hms_hospitals(id,hospital,owner,mobile,email,user_id,address,password_hash) VALUES(\${id},\${hospital},\${owner},\${mobile},\${email},\${userId},\${address},\${h})\`;await sql\`INSERT INTO hms_data(hospital_id) VALUES(\${id})\`;const t=token();await sql\`INSERT INTO hms_sessions(token,hospital_id,expires_at) VALUES(\${t},\${id},now()+interval '30 days')\`;res.setHeader('Set-Cookie',['nr_hms_session='+t+'; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000']);return send(res,200,{user:pub({id,hospital,owner,mobile,email,user_id:userId,address})})}
if(req.method==='POST'&&a==='login'){const id=String(req.body?.id||'').trim().toLowerCase(),password=String(req.body?.password||'');const r=await sql\`SELECT * FROM hms_hospitals WHERE lower(user_id)=\${id} OR mobile=\${id} LIMIT 1\`;const h=r.rows[0];if(!h||!(await verifyPassword(password,h.password_hash)))return send(res,401,{error:'Invalid Hospital Login ID or password.'});const t=token();await sql\`INSERT INTO hms_sessions(token,hospital_id,expires_at) VALUES(\${t},\${h.id},now()+interval '30 days')\`;res.setHeader('Set-Cookie',['nr_hms_session='+t+'; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000']);return send(res,200,{user:pub(h)})}
if(req.method==='GET'&&a==='me'){const h=await session(req);if(!h)return send(res,401,{error:'Not logged in'});return send(res,200,{user:pub(h)})}
if(req.method==='GET'&&a==='data'){const h=await session(req);if(!h)return send(res,401,{error:'Please log in to continue.'});const r=await sql\`SELECT patients,doctors,appointments,bills FROM hms_data WHERE hospital_id=\${h.id} LIMIT 1\`;const x=r.rows[0]||{};return send(res,200,{patients:Array.isArray(x.patients)?x.patients:[],doctors:Array.isArray(x.doctors)?x.doctors:[],appointments:Array.isArray(x.appointments)?x.appointments:[],bills:Array.isArray(x.bills)?x.bills:[]})}
if(req.method==='PUT'&&a==='data'){const h=await session(req);if(!h)return send(res,401,{error:'Please log in to continue.'});const b=req.body||{},patients=Array.isArray(b.patients)?b.patients:[],doctors=Array.isArray(b.doctors)?b.doctors:[],appointments=Array.isArray(b.appointments)?b.appointments:[],bills=Array.isArray(b.bills)?b.bills:[];await sql\`INSERT INTO hms_data(hospital_id,patients,doctors,appointments,bills,updated_at) VALUES(\${h.id},\${JSON.stringify(patients)}::jsonb,\${JSON.stringify(doctors)}::jsonb,\${JSON.stringify(appointments)}::jsonb,\${JSON.stringify(bills)}::jsonb,now()) ON CONFLICT(hospital_id) DO UPDATE SET patients=EXCLUDED.patients,doctors=EXCLUDED.doctors,appointments=EXCLUDED.appointments,bills=EXCLUDED.bills,updated_at=now()\`;return send(res,200,{ok:true})}
if(req.method==='POST'&&a==='logout'){const t=getCookie(req,'nr_hms_session');if(t)await sql\`DELETE FROM hms_sessions WHERE token=\${t}\`;res.setHeader('Set-Cookie',['nr_hms_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0']);return send(res,200,{ok:true})}
return send(res,404,{error:'Unknown action'})}catch(e){console.error(e);return send(res,500,{error:'HMS server error'})}}
function cryptoRandom(){return globalThis.crypto?.randomUUID?.()||String(Date.now())+'-'+Math.random().toString(36).slice(2)}
