import {sql,initDb,hashPassword,verifyPassword,token,cookie,sessionBusiness} from './db.js';
function send(res,c,b){res.setHeader('Content-Type','application/json');res.status(c).json(b)}
function id(){return globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`}
function publicStaff(s){return {id:s.id,name:s.name,username:s.username,active:s.active,createdAt:s.created_at}}
export default async function handler(req,res){await initDb();try{
 const a=req.body?.action||req.query?.action;
 if(a==='login'&&req.method==='POST'){const username=String(req.body?.username||'').trim(),password=String(req.body?.password||'');if(!username||!password)return send(res,400,{error:'Enter staff username and password.'});const r=await sql`SELECT s.*,b.status,b.plan,b.subscription_ends,b.business,b.owner,b.mobile,b.email,b.category,b.gst FROM staff_users s JOIN businesses b ON b.id=s.business_id WHERE lower(s.username)=lower(${username}) AND s.active=true LIMIT 1`;const s=r.rows[0];if(!s||!(await verifyPassword(password,s.password_hash)))return send(res,401,{error:'Invalid staff login details.'});if(s.status!=='active')return send(res,403,{error:'Business membership is not active.'});if(s.plan!=='lifetime'&&(!s.subscription_ends||new Date(s.subscription_ends)<=new Date()))return send(res,403,{error:'Business membership has expired.'});const t=token();await sql`INSERT INTO sessions(token,business_id,admin,role,expires_at) VALUES(${t},${s.business_id},false,'staff',now()+interval '30 days')`;cookie(res,'nr_session',t);return send(res,200,{user:{id:s.business_id,business:s.business,owner:s.owner,mobile:s.mobile,email:s.email,category:s.category,gst:s.gst,status:s.status,plan:s.plan,subscriptionEnds:s.subscription_ends,role:'staff',staffId:s.id,staffName:s.name,staffUsername:s.username}})}
 const b=await sessionBusiness(req);if(!b)return send(res,401,{error:'Login required.'});
 if(a==='list'&&req.method==='GET'){const r=await sql`SELECT id,name,username,active,created_at FROM staff_users WHERE business_id=${b.id} ORDER BY created_at`;return send(res,200,{staff:r.rows.map(publicStaff),limit:3,role:b.role})}
 if(a==='create'&&req.method==='POST'){if(b.role!=='owner')return send(res,403,{error:'Only the business owner can add staff.'});const count=await sql`SELECT COUNT(*)::int AS n FROM staff_users WHERE business_id=${b.id}`;if(Number(count.rows[0].n)>=3)return send(res,409,{error:'Maximum 3 staff logins are allowed for this business.'});const name=String(req.body?.name||'').trim(),username=String(req.body?.username||'').trim(),password=String(req.body?.password||'');if(!name||!username||password.length<6)return send(res,400,{error:'Name, username and password (minimum 6 characters) are required.'});const dup=await sql`SELECT 1 FROM staff_users WHERE business_id=${b.id} AND lower(username)=lower(${username})`;if(dup.rowCount)return send(res,409,{error:'That staff username already exists.'});const h=await hashPassword(password),r=await sql`INSERT INTO staff_users(id,business_id,name,username,password_hash) VALUES(${id()},${b.id},${name},${username},${h}) RETURNING id,name,username,active,created_at`;return send(res,200,{staff:publicStaff(r.rows[0]),limit:3})}
 if(a==='toggle'&&req.method==='POST'){if(b.role!=='owner')return send(res,403,{error:'Only the business owner can manage staff.'});const staffId=String(req.body?.staffId||'');const r=await sql`UPDATE staff_users SET active=NOT active,updated_at=now() WHERE id=${staffId} AND business_id=${b.id} RETURNING id,name,username,active,created_at`;if(!r.rowCount)return send(res,404,{error:'Staff member not found.'});return send(res,200,{staff:publicStaff(r.rows[0])})}
 if(a==='delete'&&req.method==='POST'){if(b.role!=='owner')return send(res,403,{error:'Only the business owner can manage staff.'});const staffId=String(req.body?.staffId||'');const r=await sql`DELETE FROM staff_users WHERE id=${staffId} AND business_id=${b.id} RETURNING id`;if(!r.rowCount)return send(res,404,{error:'Staff member not found.'});await sql`DELETE FROM sessions WHERE business_id=${b.id} AND role='staff'`;return send(res,200,{ok:true})}
 return send(res,404,{error:'Unknown staff action.'});
}catch(e){console.error(e);return send(res,500,{error:'Staff service error.'})}}
